### UK Access, Watch, Reserve, and Other classification for antibiotics in dmd

The ["UK Access, Watch, Reserve, and Other classification for antibiotics"](https://www.gov.uk/government/publications/uk-aware-antibiotic-classification/uk-access-watch-reserve-and-other-classification-for-antibiotics-uk-aware-antibiotic-classification) categorises antibiotics into groups such as Access, Watch, and Reserve to guide healthcare professionals in optimising their use and mitigating antimicrobial resistance.

The existing list on the UKHSA site is not machine readable. To facilitate research, it is helpful to link this categorisation to the [dm+d standard](https://www.nhsbsa.nhs.uk/pharmacies-gp-practices-and-appliance-contractors/dictionary-medicines-and-devices-dmd).

### Imports
We need to import some libaries to help with the code

In [1]:
import pandas as pd
import requests
from ebmdatalab import bq
import os

### Getting the AWaRe list
The AWaRe list is currently available on the following webpage. We can read the html page directly into Pandas to retrieve the first table.

In [2]:
# Set URL to scrape
url = "https://www.gov.uk/government/publications/uk-aware-antibiotic-classification/uk-access-watch-reserve-and-other-classification-for-antibiotics-uk-aware-antibiotic-classification"

# Read the first HTML table from the page into a DataFrame using the HTML content
df_scrape = pd.read_html(url)[0]

# Display the DataFrame
df_scrape

,Antibiotic,England-adapted 2019 AWaRe category,UK-adapted 2024 AWaRe category
0,Amikacin,Watch,Watch
1,Amoxicillin,Access,Access
2,Amoxicillin/ clavulanic-acid,Watch,Watch
3,Ampicillin,Access,Access
4,Azithromycin,Watch,Watch
...,...,...,...
85,Tigecycline,Reserve,Reserve
86,Tinidazole #,Other,Access
87,Tobramycin,Watch,Watch
88,Trimethoprim,Access,Access
89,Vancomycin,Watch,Watch

### Cleaning up the list
The list contains some characters or identifiers that could break matching, we need to clean these up.

The # symbol is used to denote where category has changed, remove this

In [3]:
df_scrape['Antibiotic'] = df_scrape['Antibiotic'].str.replace(" #", "", regex=False)

We can review remaining rows that contain non-alphabetical characters

In [4]:
df_scrape[df_scrape['Antibiotic'].str.contains(r'[^A-Za-z ]', na=False)]

,Antibiotic,England-adapted 2019 AWaRe category,UK-adapted 2024 AWaRe category
2,Amoxicillin/ clavulanic-acid,Watch,Watch
6,Benzathine-benzylpenicillin,Access,Access
20,Ceftaroline-fosamil,Reserve,Reserve
22,Ceftazidime/ avibactam,Reserve,Reserve
23,Ceftobiprole-medocaril,Reserve,Reserve
24,Ceftolozane/ tazobactam,Reserve,Reserve
31,"Colistin, intravenous",Reserve,Reserve
32,"Colistin, oral",Reserve,Reserve
34,Dalfopristin/ quinupristin,Reserve,Reserve
46,"Fosfomycin, intravenous",Reserve,Reserve
49,Imipenem/cilastatin,Reserve,Reserve
50,Imipenem/cilastatin/relebactam,Reserve,Reserve
55,Meropenem/ vaborbactam,Reserve,Reserve
69,Piperacillin/tazobactam,Watch,Watch
72,Procaine-benzylpenicillin,Access,Access
75,"Streptomycin, intravenous",Other,Other
77,Sulfamethoxazole/ trimethoprim,Access,Access

Some rows specify a route. Sometimes there is a comma between antibiotic and route, sometimes there isn't. We can pull any specified route into a seperate column.

In [5]:
# List of routes to check.
route_list = ["oral", "intravenous"]

# Function to extract the route if the Antibiotic entry ends with a route.
def extract_route(antibiotic):
    for route in route_list:
        if antibiotic.endswith(" " + route):
            return route
    return ""  # Return empty string if no route is found.

# Apply the function to create a new 'Route' column.
df_scrape['Route_specific'] = df_scrape['Antibiotic'].apply(extract_route)

# Remove any route names from the 'Antibiotic' column only if they appear at the end
# and are preceded by either ", " or " ".
for route in route_list:
    df_scrape['Antibiotic'] = df_scrape['Antibiotic'].str.replace(fr'(, | ){route}$', '', regex=True)

In [6]:
df_scrape[df_scrape['Antibiotic'].str.contains(r'[^A-Za-z ]', na=False)]

,Antibiotic,England-adapted 2019 AWaRe category,UK-adapted 2024 AWaRe category,Route_specific
2,Amoxicillin/ clavulanic-acid,Watch,Watch,
6,Benzathine-benzylpenicillin,Access,Access,
20,Ceftaroline-fosamil,Reserve,Reserve,
22,Ceftazidime/ avibactam,Reserve,Reserve,
23,Ceftobiprole-medocaril,Reserve,Reserve,
24,Ceftolozane/ tazobactam,Reserve,Reserve,
34,Dalfopristin/ quinupristin,Reserve,Reserve,
49,Imipenem/cilastatin,Reserve,Reserve,
50,Imipenem/cilastatin/relebactam,Reserve,Reserve,
55,Meropenem/ vaborbactam,Reserve,Reserve,
69,Piperacillin/tazobactam,Watch,Watch,
72,Procaine-benzylpenicillin,Access,Access,
77,Sulfamethoxazole/ trimethoprim,Access,Access,

Some items contain a dash between words where as in dm+d there is a space. Replace the dash with a space to follow the common format.

In [7]:
df_scrape['Antibiotic'] = df_scrape['Antibiotic'].str.replace("-", " ", regex=False)

Some items contain a forward slash between words to indicate a combination where as in dm+d there is a + symbol. Replace the dash with a + ensuring appropriately spaced to follow the common dm+d format.

In [8]:
# Replace / with a + ensuring it is appropriately spaced and 2nd drug name is capitalised
df_scrape['Antibiotic'] = (
    df_scrape['Antibiotic']
    .str.replace(r'\s*/\s*', ' + ', regex=True)
    .str.replace(r'(\+\s+)(\w)', lambda m: m.group(1) + m.group(2).upper(), regex=True)
)
# Create a new column 'Combo' that is True if 'Antibiotic' contains a plus between two words.
df_scrape['Combo'] = df_scrape['Antibiotic'].str.contains(r'\b\w+\s*\+\s*\w+\b', regex=True)

In [9]:
df_scrape[df_scrape['Antibiotic'].str.contains(r'[^A-Za-z ]', na=False)]

,Antibiotic,England-adapted 2019 AWaRe category,UK-adapted 2024 AWaRe category,Route_specific,Combo
2,Amoxicillin + Clavulanic acid,Watch,Watch,,True
22,Ceftazidime + Avibactam,Reserve,Reserve,,True
24,Ceftolozane + Tazobactam,Reserve,Reserve,,True
34,Dalfopristin + Quinupristin,Reserve,Reserve,,True
49,Imipenem + Cilastatin,Reserve,Reserve,,True
50,Imipenem + Cilastatin + Relebactam,Reserve,Reserve,,True
55,Meropenem + Vaborbactam,Reserve,Reserve,,True
69,Piperacillin + Tazobactam,Watch,Watch,,True
77,Sulfamethoxazole + Trimethoprim,Access,Access,,True

Some antibiotic combinations are referred to as different names or in a different order in dm+d. Convert to use these. (Found these issues via dm+d manual search)

In [10]:
df_scrape['Antibiotic'] = df_scrape['Antibiotic'].str.replace("Amoxicillin + Clavulanic acid", "Co-amoxiclav", regex=False)
df_scrape['Antibiotic'] = df_scrape['Antibiotic'].str.replace("Sulfamethoxazole + Trimethoprim", "Co-trimoxazole", regex=False)
df_scrape['Antibiotic'] = df_scrape['Antibiotic'].str.replace("Dalfopristin + Quinupristin", "Quinupristin + Dalfopristin", regex=False)
df_scrape['Antibiotic'] = df_scrape['Antibiotic'].str.replace("Imipenem + Cilastatin + Relebactam", "Cilastatin + Imipenem + Relebactam", regex=False)
df_scrape['Antibiotic'] = df_scrape['Antibiotic'].str.replace("Ceftobiprole medocaril", "Ceftobiprole", regex=False)

Reorder the columns

Ensure 'Route_specific' is a string by replacing NaN with an empty string
Add a column 'ATC_Route_specific' mapping 'Route_specific' to ATC route

In [11]:
# Define mapping
route_map = {'oral': 'O', 'intravenous': 'P'}

# Replace NaN with empty strings just to be safe
df_scrape['Route_specific'] = df_scrape['Route_specific'].fillna('')

# Map values using a dictionary, and fill any unmapped entries with empty string
df_scrape['ATC_Route_specific'] = df_scrape['Route_specific'].map(route_map).fillna('')

Reorder the columns and rename to simplify

In [12]:
df_scrape = df_scrape[['Antibiotic', 'Route_specific', 'ATC_Route_specific', 'Combo'] + [col for col in df_scrape.columns if col not in ['Antibiotic', 'Route_specific', 'ATC_Route_specific', 'Combo']]]

df_scrape.rename(columns={'England-adapted 2019 AWaRe category': 'aware_2019'}, inplace=True)
df_scrape.rename(columns={'UK-adapted 2024 AWaRe category': 'aware_2024'}, inplace=True)
df_scrape.rename(columns={'Route_specific': 'route'}, inplace=True)
df_scrape.rename(columns={'ATC_Route_specific': 'atc_route'}, inplace=True)

# Drop un-needed column
df_scrape.drop(columns='Combo', inplace=True)

In [13]:
df_prepared = df_scrape

with pd.option_context('display.max_rows', None):
    display(df_prepared)

,Antibiotic,route,atc_route,aware_2019,aware_2024
0,Amikacin,,,Watch,Watch
1,Amoxicillin,,,Access,Access
2,Co-amoxiclav,,,Watch,Watch
3,Ampicillin,,,Access,Access
4,Azithromycin,,,Watch,Watch
5,Aztreonam,,,Reserve,Reserve
6,Benzathine benzylpenicillin,,,Access,Access
7,Benzylpenicillin,,,Access,Access
8,Cefaclor,,,Watch,Watch
9,Cefadroxil,,,Watch,Access
10,Cefalexin,,,Watch,Access
11,Cefalotin,,,Watch,Access
12,Cefamandole,,,Watch,Watch
13,Cefazolin,,,Watch,Access
14,Cefepime,,,Watch,Watch
15,Cefiderocol,,,Reserve,Reserve
16,Cefixime,,,Watch,Watch
17,Cefotaxime,,,Watch,Watch
18,Cefoxitin,,,Watch,Watch
19,Cefradine,,,Watch,Access
20,Ceftaroline fosamil,,,Reserve,Reserve
21,Ceftazidime,,,Watch,Watch
22,Ceftazidime + Avibactam,,,Reserve,Reserve
23,Ceftobiprole,,,Reserve,Reserve
24,Ceftolozane + Tazobactam,,,Reserve,Reserve
25,Ceftriaxone,,,Watch,Watch
26,Cefuroxime,,,Watch,Watch
27,Chloramphenicol,,,Watch,Watch
28,Ciprofloxacin,,,Watch,Watch
29,Clarithromycin,,,Watch,Watch
30,Clindamycin,,,Watch,Watch
31,Colistin,intravenous,P,Reserve,Reserve
32,Colistin,oral,O,Reserve,Reserve
33,Dalbavancin,,,Reserve,Reserve
34,Quinupristin + Dalfopristin,,,Reserve,Reserve
35,Daptomycin,,,Reserve,Reserve
36,Delafloxacin,,,Watch,Watch
37,Demeclocycline,,,Watch,Other
38,Doripenem,,,Reserve,Reserve
39,Doxycycline,,,Access,Access
40,Eravacycline,,,Reserve,Reserve
41,Ertapenem,,,Reserve,Reserve
42,Erythromycin,,,Watch,Watch
43,Fidaxomicin,,,Watch,Watch
44,Flucloxacillin,,,Access,Access
45,Fosfomycin,oral,O,Access,Access
46,Fosfomycin,intravenous,P,Reserve,Reserve
47,Fusidic acid,,,Access,Watch
48,Gentamicin,,,Access,Access
49,Imipenem + Cilastatin,,,Reserve,Reserve
50,Cilastatin + Imipenem + Relebactam,,,Reserve,Reserve
51,Levofloxacin,,,Watch,Watch
52,Linezolid,,,Reserve,Reserve
53,Lymecycline,,,Watch,Watch
54,Meropenem,,,Reserve,Reserve
55,Meropenem + Vaborbactam,,,Reserve,Reserve
56,Methenamine,,,Other,Other
57,Metronidazole,,,Access,Access
58,Minocycline,oral,O,Watch,Watch
59,Moxifloxacin,,,Watch,Watch
60,Nalidixic Acid,,,Other,Other
61,Neomycin,,,Watch,Watch
62,Nitrofurantoin,,,Access,Access
63,Norfloxacin,,,Watch,Watch
64,Ofloxacin,,,Watch,Watch
65,Oritavancin,,,Reserve,Reserve
66,Oxytetracycline,,,Watch,Watch
67,Phenoxymethylpenicillin,,,Access,Access
68,Piperacillin,,,Watch,Watch
69,Piperacillin + Tazobactam,,,Watch,Watch
70,Pivmecillinam,,,Access,Access
71,Pristinamycin,,,Watch,Other
72,Procaine benzylpenicillin,,,Access,Access
73,Spectinomycin,,,Other,Other
74,Spiramycin,,,Other,Other
75,Streptomycin,intravenous,P,Other,Other
76,Sulfadiazine,,,Other,Other
77,Co-trimoxazole,,,Access,Access
78,Sulfamethoxypyridazine,,,Other,Other
79,Sulfapyridine,,,Other,Other
80,Tedizolid,,,Reserve,Reserve
81,Teicoplanin,,,Watch,Watch
82,Telavancin,,,Reserve,Reserve
83,Temocillin,,,Watch,Watch
84,Tetracycline,,,Access,Access
85,Tigecycline,,,Reserve,Reserve
86,Tinidazole,,,Other,Access
87,Tobramycin,,,Watch,Watch
88,Trimethoprim,,,Access,Access
89,Vancomycin,,,Watch,Watch

We can save this as a CSV amd upload as a table in BigQuery for further processing. `ebmdatalab.chris.aware_prepared`

In [14]:
csv_path = os.path.join('..', 'data', 'AWaRe_prepared.csv')
df_prepared.to_csv(csv_path, index=False)

### Matching to VTMs

We can attempt to match Antibiotic names in the UKHSA to VTMs in dm+d

In [15]:
sql = f"""
  SELECT  
    aware.Antibiotic,
    aware.atc_route,
    aware.aware_2019,
    aware.aware_2024,
    vtm.nm,
    CASE
      WHEN aware.Antibiotic = vtm.nm THEN 'DIRECT'
      ELSE 'ASSUMED'
    END AS match_type
  FROM `ebmdatalab.chris.aware_list` aware
  LEFT JOIN `ebmdatalab.dmd.vtm` vtm 
    ON vtm.nm = aware.Antibiotic
  WHERE vtm.invalid IS NOT TRUE
  ORDER BY Antibiotic ASC
"""

# Define the CSV path for caching the results.
csv_path = os.path.join('..', 'data', 'vtm_match.csv')

# Use the cached_read function from the bq library to run the query.
vtm_match = bq.cached_read(sql, csv_path=csv_path)

with pd.option_context('display.max_rows', None):
    display(vtm_match)

,Antibiotic,atc_route,aware_2019,aware_2024,nm,match_type
0,Amikacin,NaN,Watch,Watch,Amikacin,DIRECT
1,Amoxicillin,NaN,Access,Access,Amoxicillin,DIRECT
2,Ampicillin,NaN,Access,Access,Ampicillin,DIRECT
3,Azithromycin,NaN,Watch,Watch,Azithromycin,DIRECT
4,Aztreonam,NaN,Reserve,Reserve,Aztreonam,DIRECT
5,Benzathine benzylpenicillin,NaN,Access,Access,Benzathine benzylpenicillin,DIRECT
6,Benzylpenicillin,NaN,Access,Access,Benzylpenicillin,DIRECT
7,Cefaclor,NaN,Watch,Watch,Cefaclor,DIRECT
8,Cefadroxil,NaN,Watch,Access,Cefadroxil,DIRECT
9,Cefalexin,NaN,Watch,Access,Cefalexin,DIRECT
10,Cefalotin,NaN,Watch,Access,NaN,ASSUMED
11,Cefamandole,NaN,Watch,Watch,Cefamandole,DIRECT
12,Cefazolin,NaN,Watch,Access,Cefazolin,DIRECT
13,Cefepime,NaN,Watch,Watch,Cefepime,DIRECT
14,Cefiderocol,NaN,Reserve,Reserve,Cefiderocol,DIRECT
15,Cefixime,NaN,Watch,Watch,Cefixime,DIRECT
16,Cefotaxime,NaN,Watch,Watch,Cefotaxime,DIRECT
17,Cefoxitin,NaN,Watch,Watch,Cefoxitin,DIRECT
18,Cefradine,NaN,Watch,Access,Cefradine,DIRECT
19,Ceftaroline fosamil,NaN,Reserve,Reserve,Ceftaroline fosamil,DIRECT
20,Ceftazidime,NaN,Watch,Watch,Ceftazidime,DIRECT
21,Ceftazidime + Avibactam,NaN,Reserve,Reserve,Ceftazidime + Avibactam,DIRECT
22,Ceftobiprole,NaN,Reserve,Reserve,Ceftobiprole,DIRECT
23,Ceftolozane + Tazobactam,NaN,Reserve,Reserve,Ceftolozane + Tazobactam,DIRECT
24,Ceftriaxone,NaN,Watch,Watch,Ceftriaxone,DIRECT
25,Cefuroxime,NaN,Watch,Watch,Cefuroxime,DIRECT
26,Chloramphenicol,NaN,Watch,Watch,Chloramphenicol,DIRECT
27,Cilastatin + Imipenem + Relebactam,NaN,Reserve,Reserve,Cilastatin + Imipenem + Relebactam,DIRECT
28,Ciprofloxacin,NaN,Watch,Watch,Ciprofloxacin,DIRECT
29,Clarithromycin,NaN,Watch,Watch,Clarithromycin,DIRECT
30,Clindamycin,NaN,Watch,Watch,Clindamycin,DIRECT
31,Co-amoxiclav,NaN,Watch,Watch,Co-amoxiclav,DIRECT
32,Co-trimoxazole,NaN,Access,Access,Co-trimoxazole,DIRECT
33,Colistin,P,Reserve,Reserve,Colistin,DIRECT
34,Colistin,O,Reserve,Reserve,Colistin,DIRECT
35,Dalbavancin,NaN,Reserve,Reserve,Dalbavancin,DIRECT
36,Daptomycin,NaN,Reserve,Reserve,Daptomycin,DIRECT
37,Delafloxacin,NaN,Watch,Watch,Delafloxacin,DIRECT
38,Demeclocycline,NaN,Watch,Other,Demeclocycline,DIRECT
39,Doripenem,NaN,Reserve,Reserve,Doripenem,DIRECT
40,Doxycycline,NaN,Access,Access,Doxycycline,DIRECT
41,Eravacycline,NaN,Reserve,Reserve,Eravacycline,DIRECT
42,Ertapenem,NaN,Reserve,Reserve,Ertapenem,DIRECT
43,Erythromycin,NaN,Watch,Watch,Erythromycin,DIRECT
44,Fidaxomicin,NaN,Watch,Watch,Fidaxomicin,DIRECT
45,Flucloxacillin,NaN,Access,Access,Flucloxacillin,DIRECT
46,Fosfomycin,P,Reserve,Reserve,Fosfomycin,DIRECT
47,Fosfomycin,O,Access,Access,Fosfomycin,DIRECT
48,Fusidic acid,NaN,Access,Watch,Fusidic acid,DIRECT
49,Gentamicin,NaN,Access,Access,Gentamicin,DIRECT
50,Imipenem + Cilastatin,NaN,Reserve,Reserve,Imipenem + Cilastatin,DIRECT
51,Levofloxacin,NaN,Watch,Watch,Levofloxacin,DIRECT
52,Linezolid,NaN,Reserve,Reserve,Linezolid,DIRECT
53,Lymecycline,NaN,Watch,Watch,Lymecycline,DIRECT
54,Meropenem,NaN,Reserve,Reserve,Meropenem,DIRECT
55,Meropenem + Vaborbactam,NaN,Reserve,Reserve,Meropenem + Vaborbactam,DIRECT
56,Methenamine,NaN,Other,Other,Methenamine,DIRECT
57,Metronidazole,NaN,Access,Access,Metronidazole,DIRECT
58,Minocycline,O,Watch,Watch,Minocycline,DIRECT
59,Moxifloxacin,NaN,Watch,Watch,Moxifloxacin,DIRECT
60,Nalidixic Acid,NaN,Other,Other,NaN,ASSUMED
61,Neomycin,NaN,Watch,Watch,Neomycin,DIRECT
62,Nitrofurantoin,NaN,Access,Access,Nitrofurantoin,DIRECT
63,Norfloxacin,NaN,Watch,Watch,Norfloxacin,DIRECT
64,Ofloxacin,NaN,Watch,Watch,Ofloxacin,DIRECT
65,Oritavancin,NaN,Reserve,Reserve,Oritavancin,DIRECT
66,Oxytetracycline,NaN,Watch,Watch,Oxytetracycline,DIRECT
67,Phenoxymethylpenicillin,NaN,Access,Access,Phenoxymethylpenicillin,DIRECT
68,Piperacillin,NaN,Watch,Watch,NaN,ASSUMED
69,Piperacillin + Tazobactam,NaN,Watch,Watch,Piperacillin + Tazobactam,DIRECT
70,Pivmecillinam,NaN,Access,Access,Pivmecillinam,DIRECT
71,Pristinamycin,NaN,Watch,Other,Pristinamycin,DIRECT
72,Procaine benzylpenicillin,NaN,Access,Access,Procaine benzylpenicillin,DIRECT
73,Quinupristin + Dalfopristin,NaN,Reserve,Reserve,Quinupristin + Dalfopristin,DIRECT
74,Spectinomycin,NaN,Other,Other,Spectinomycin,DIRECT
75,Spiramycin,NaN,Other,Other,Spiramycin,DIRECT
76,Streptomycin,P,Other,Other,Streptomycin,DIRECT
77,Sulfadiazine,NaN,Other,Other,Sulfadiazine,DIRECT
78,Sulfamethoxypyridazine,NaN,Other,Other,Sulfamethoxypyridazine,DIRECT
79,Sulfapyridine,NaN,Other,Other,Sulfapyridine,DIRECT
80,Tedizolid,NaN,Reserve,Reserve,Tedizolid,DIRECT
81,Teicoplanin,NaN,Watch,Watch,Teicoplanin,DIRECT
82,Telavancin,NaN,Reserve,Reserve,Telavancin,DIRECT
83,Temocillin,NaN,Watch,Watch,Temocillin,DIRECT
84,Tetracycline,NaN,Access,Access,Tetracycline,DIRECT
85,Tigecycline,NaN,Reserve,Reserve,Tigecycline,DIRECT
86,Tinidazole,NaN,Other,Access,Tinidazole,DIRECT
87,Tobramycin,NaN,Watch,Watch,Tobramycin,DIRECT
88,Trimethoprim,NaN,Access,Access,Trimethoprim,DIRECT
89,Vancomycin,NaN,Watch,Watch,Vancomycin,DIRECT

This works to match VTMs to many of the listing. But doesn't capture where there are multiple VTM matches - for example Amikacin and Amikacin liposomal for Amikacin. 

We can use more fuzzy matching to get greater sensitivity in the matches.

In [16]:
sql = f"""
  SELECT  
    aware.Antibiotic,
    aware.atc_route,
    aware.aware_2019,
    aware.aware_2024,
    vtm.nm,
    CASE
      WHEN aware.Antibiotic = vtm.nm THEN 'DIRECT'
      ELSE 'ASSUMED'
    END AS match_type
  FROM `ebmdatalab.chris.aware_list` aware
  LEFT JOIN `ebmdatalab.dmd.vtm` vtm 
    ON vtm.nm LIKE CONCAT('%', aware.Antibiotic, '%')
  WHERE vtm.invalid IS NOT TRUE
  ORDER BY Antibiotic ASC
"""

# Define the CSV path for caching the results.
csv_path = os.path.join('..', 'data', 'vtm_fuzzy_match.csv')

# Use the cached_read function from the bq library to run the query.
vtm_fuzzy_match = bq.cached_read(sql, csv_path=csv_path)

with pd.option_context('display.max_rows', None):
    display(vtm_fuzzy_match)

,Antibiotic,atc_route,aware_2019,aware_2024,nm,match_type
0,Amikacin,NaN,Watch,Watch,Amikacin liposomal,ASSUMED
1,Amikacin,NaN,Watch,Watch,Amikacin,DIRECT
2,Amoxicillin,NaN,Access,Access,Amoxicillin,DIRECT
3,Ampicillin,NaN,Access,Access,Ampicillin,DIRECT
4,Ampicillin,NaN,Access,Access,Ampicillin + Flucloxacillin,ASSUMED
5,Azithromycin,NaN,Watch,Watch,Azithromycin,DIRECT
6,Aztreonam,NaN,Reserve,Reserve,Aztreonam + Avibactam,ASSUMED
7,Aztreonam,NaN,Reserve,Reserve,Aztreonam,DIRECT
8,Benzathine benzylpenicillin,NaN,Access,Access,Benzathine benzylpenicillin,DIRECT
9,Benzylpenicillin,NaN,Access,Access,Benzylpenicillin,DIRECT
10,Cefaclor,NaN,Watch,Watch,Cefaclor,DIRECT
11,Cefadroxil,NaN,Watch,Access,Cefadroxil,DIRECT
12,Cefalexin,NaN,Watch,Access,Cefalexin,DIRECT
13,Cefalotin,NaN,Watch,Access,NaN,ASSUMED
14,Cefamandole,NaN,Watch,Watch,Cefamandole,DIRECT
15,Cefazolin,NaN,Watch,Access,Cefazolin,DIRECT
16,Cefepime,NaN,Watch,Watch,Cefepime + Enmetazobactam,ASSUMED
17,Cefepime,NaN,Watch,Watch,Cefepime,DIRECT
18,Cefiderocol,NaN,Reserve,Reserve,Cefiderocol,DIRECT
19,Cefixime,NaN,Watch,Watch,Cefixime,DIRECT
20,Cefotaxime,NaN,Watch,Watch,Cefotaxime,DIRECT
21,Cefoxitin,NaN,Watch,Watch,Cefoxitin,DIRECT
22,Cefradine,NaN,Watch,Access,Cefradine,DIRECT
23,Ceftaroline fosamil,NaN,Reserve,Reserve,Ceftaroline fosamil,DIRECT
24,Ceftazidime,NaN,Watch,Watch,Ceftazidime + Avibactam,ASSUMED
25,Ceftazidime,NaN,Watch,Watch,Ceftazidime,DIRECT
26,Ceftazidime + Avibactam,NaN,Reserve,Reserve,Ceftazidime + Avibactam,DIRECT
27,Ceftobiprole,NaN,Reserve,Reserve,Ceftobiprole,DIRECT
28,Ceftolozane + Tazobactam,NaN,Reserve,Reserve,Ceftolozane + Tazobactam,DIRECT
29,Ceftriaxone,NaN,Watch,Watch,Ceftriaxone,DIRECT
30,Cefuroxime,NaN,Watch,Watch,Cefuroxime,DIRECT
31,Chloramphenicol,NaN,Watch,Watch,Chloramphenicol,DIRECT
32,Cilastatin + Imipenem + Relebactam,NaN,Reserve,Reserve,Cilastatin + Imipenem + Relebactam,DIRECT
33,Ciprofloxacin,NaN,Watch,Watch,Ciprofloxacin + Dexamethasone,ASSUMED
34,Ciprofloxacin,NaN,Watch,Watch,Ciprofloxacin,DIRECT
35,Ciprofloxacin,NaN,Watch,Watch,Ciprofloxacin + Fluocinolone acetonide,ASSUMED
36,Clarithromycin,NaN,Watch,Watch,Clarithromycin,DIRECT
37,Clindamycin,NaN,Watch,Watch,Clindamycin + Tretinoin,ASSUMED
38,Clindamycin,NaN,Watch,Watch,Clindamycin + Hydrocortisone,ASSUMED
39,Clindamycin,NaN,Watch,Watch,Clindamycin,DIRECT
40,Clindamycin,NaN,Watch,Watch,Benzoyl peroxide + Clindamycin,ASSUMED
41,Co-amoxiclav,NaN,Watch,Watch,Co-amoxiclav,DIRECT
42,Co-trimoxazole,NaN,Access,Access,Co-trimoxazole,DIRECT
43,Colistin,P,Reserve,Reserve,Colistin,DIRECT
44,Colistin,O,Reserve,Reserve,Colistin,DIRECT
45,Dalbavancin,NaN,Reserve,Reserve,Dalbavancin,DIRECT
46,Daptomycin,NaN,Reserve,Reserve,Daptomycin,DIRECT
47,Delafloxacin,NaN,Watch,Watch,Delafloxacin,DIRECT
48,Demeclocycline,NaN,Watch,Other,Demeclocycline,DIRECT
49,Doripenem,NaN,Reserve,Reserve,Doripenem,DIRECT
50,Doxycycline,NaN,Access,Access,Betamethasone + Doxycycline + Nystatin,ASSUMED
51,Doxycycline,NaN,Access,Access,Doxycycline,DIRECT
52,Eravacycline,NaN,Reserve,Reserve,Eravacycline,DIRECT
53,Ertapenem,NaN,Reserve,Reserve,Ertapenem,DIRECT
54,Erythromycin,NaN,Watch,Watch,Erythromycin + Zinc acetate,ASSUMED
55,Erythromycin,NaN,Watch,Watch,Tretinoin + Erythromycin,ASSUMED
56,Erythromycin,NaN,Watch,Watch,Isotretinoin + Erythromycin,ASSUMED
57,Erythromycin,NaN,Watch,Watch,Erythromycin lactobionate,ASSUMED
58,Erythromycin,NaN,Watch,Watch,Erythromycin,DIRECT
59,Erythromycin,NaN,Watch,Watch,Benzoyl peroxide + Erythromycin,ASSUMED
60,Erythromycin,NaN,Watch,Watch,Erythromycin ethyl succinate,ASSUMED
61,Erythromycin,NaN,Watch,Watch,Erythromycin stearate,ASSUMED
62,Fidaxomicin,NaN,Watch,Watch,Fidaxomicin,DIRECT
63,Flucloxacillin,NaN,Access,Access,Flucloxacillin,DIRECT
64,Flucloxacillin,NaN,Access,Access,Ampicillin + Flucloxacillin,ASSUMED
65,Fosfomycin,P,Reserve,Reserve,Fosfomycin,DIRECT
66,Fosfomycin,O,Access,Access,Fosfomycin,DIRECT
67,Fusidic acid,NaN,Access,Watch,Fusidic acid,DIRECT
68,Fusidic acid,NaN,Access,Watch,Betamethasone + Fusidic acid,ASSUMED
69,Fusidic acid,NaN,Access,Watch,Hydrocortisone + Fusidic acid,ASSUMED
70,Gentamicin,NaN,Access,Access,Gentamicin + Hydrocortisone,ASSUMED
71,Gentamicin,NaN,Access,Access,Gentamicin,DIRECT
72,Imipenem + Cilastatin,NaN,Reserve,Reserve,Imipenem + Cilastatin,DIRECT
73,Levofloxacin,NaN,Watch,Watch,Levofloxacin,DIRECT
74,Levofloxacin,NaN,Watch,Watch,Dexamethasone + Levofloxacin,ASSUMED
75,Linezolid,NaN,Reserve,Reserve,Linezolid,DIRECT
76,Lymecycline,NaN,Watch,Watch,Lymecycline,DIRECT
77,Meropenem,NaN,Reserve,Reserve,Meropenem,DIRECT
78,Meropenem,NaN,Reserve,Reserve,Meropenem + Vaborbactam,ASSUMED
79,Meropenem + Vaborbactam,NaN,Reserve,Reserve,Meropenem + Vaborbactam,DIRECT
80,Methenamine,NaN,Other,Other,Methenamine,DIRECT
81,Metronidazole,NaN,Access,Access,Metronidazole,DIRECT
82,Minocycline,O,Watch,Watch,Minocycline,DIRECT
83,Moxifloxacin,NaN,Watch,Watch,Moxifloxacin,DIRECT
84,Nalidixic Acid,NaN,Other,Other,NaN,ASSUMED
85,Neomycin,NaN,Watch,Watch,Clobetasol + Neomycin + Nystatin,ASSUMED
86,Neomycin,NaN,Watch,Watch,Betamethasone + Neomycin,ASSUMED
87,Neomycin,NaN,Watch,Watch,Neomycin + Gramicidin,ASSUMED
88,Neomycin,NaN,Watch,Watch,Neomycin + Chlorhexidine,ASSUMED
89,Neomycin,NaN,Watch,Watch,Neomycin,DIRECT
90,Neomycin,NaN,Watch,Watch,Hydrocortisone + Neomycin,ASSUMED
91,Neomycin,NaN,Watch,Watch,Fluocinolone acetonide + Neomycin,ASSUMED
92,Neomycin,NaN,Watch,Watch,Neomycin + Triamcinolone,ASSUMED
93,Neomycin,NaN,Watch,Watch,Neomycin + Prednisolone,ASSUMED
94,Nitrofurantoin,NaN,Access,Access,Nitrofurantoin,DIRECT
95,Norfloxacin,NaN,Watch,Watch,Norfloxacin,DIRECT
96,Ofloxacin,NaN,Watch,Watch,Ofloxacin,DIRECT
97,Oritavancin,NaN,Reserve,Reserve,Oritavancin,DIRECT
98,Oxytetracycline,NaN,Watch,Watch,Oxytetracycline + Hydrocortisone,ASSUMED
99,Oxytetracycline,NaN,Watch,Watch,Oxytetracycline,DIRECT
100,Oxytetracycline,NaN,Watch,Watch,Clobetasone + Oxytetracycline + Nystatin,ASSUMED
101,Phenoxymethylpenicillin,NaN,Access,Access,Phenoxymethylpenicillin,DIRECT
102,Piperacillin,NaN,Watch,Watch,Piperacillin + Tazobactam,ASSUMED
103,Piperacillin + Tazobactam,NaN,Watch,Watch,Piperacillin + Tazobactam,DIRECT
104,Pivmecillinam,NaN,Access,Access,Pivmecillinam,DIRECT
105,Pristinamycin,NaN,Watch,Other,Pristinamycin,DIRECT
106,Procaine benzylpenicillin,NaN,Access,Access,Procaine benzylpenicillin,DIRECT
107,Quinupristin + Dalfopristin,NaN,Reserve,Reserve,Quinupristin + Dalfopristin,DIRECT
108,Spectinomycin,NaN,Other,Other,Spectinomycin,DIRECT
109,Spiramycin,NaN,Other,Other,Spiramycin,DIRECT
110,Streptomycin,P,Other,Other,Streptomycin,DIRECT
111,Sulfadiazine,NaN,Other,Other,Cerium nitrate + Sulfadiazine silver,ASSUMED
112,Sulfadiazine,NaN,Other,Other,Sulfadiazine,DIRECT
113,Sulfadiazine,NaN,Other,Other,Sulfadiazine silver,ASSUMED
114,Sulfamethoxypyridazine,NaN,Other,Other,Sulfamethoxypyridazine,DIRECT
115,Sulfapyridine,NaN,Other,Other,Sulfapyridine,DIRECT
116,Tedizolid,NaN,Reserve,Reserve,Tedizolid,DIRECT
117,Teicoplanin,NaN,Watch,Watch,Teicoplanin,DIRECT
118,Telavancin,NaN,Reserve,Reserve,Telavancin,DIRECT
119,Temocillin,NaN,Watch,Watch,Temocillin,DIRECT
120,Tetracycline,NaN,Access,Access,Tetracycline,DIRECT
121,Tigecycline,NaN,Reserve,Reserve,Tigecycline,DIRECT
122,Tinidazole,NaN,Other,Access,Tinidazole,DIRECT
123,Tobramycin,NaN,Watch,Watch,Tobramycin,DIRECT
124,Tobramycin,NaN,Watch,Watch,Dexamethasone + Tobramycin,ASSUMED
125,Trimethoprim,NaN,Access,Access,Trimethoprim,DIRECT
126,Trimethoprim,NaN,Access,Access,Polymyxin B + Trimethoprim,ASSUMED
127,Vancomycin,NaN,Watch,Watch,Vancomycin,DIRECT

This gives a number of duplicate matches - for example Meropenem + Vaborbactam matches to both Meropenem and Meropenem + Vaborbactam

We can look for all the duplicates

In [17]:
sql = f"""
WITH matched_vtms AS (
  SELECT  
    aware.Antibiotic,
    aware.atc_route,
    aware.aware_2019,
    aware.aware_2024,
    vtm.nm,
    CASE
      WHEN aware.Antibiotic = vtm.nm THEN 'DIRECT'
      ELSE 'ASSUMED'
    END AS match_type
  FROM `ebmdatalab.chris.aware_list` aware
  LEFT JOIN `ebmdatalab.dmd.vtm` vtm 
    ON vtm.nm LIKE CONCAT('%', aware.Antibiotic, '%')
  WHERE vtm.invalid IS NOT TRUE
)

SELECT *
FROM matched_vtms
WHERE nm IN (
  SELECT nm
  FROM matched_vtms
  WHERE atc_route IS NULL
  GROUP BY nm
  HAVING COUNT(*) > 1
)
ORDER BY Antibiotic ASC;
"""

# Define the CSV path for caching the results.
csv_path = os.path.join('..', 'data', 'vtm_duplicates.csv')

# Use the cached_read function from the bq library to run the query.
vtm_duplicates = bq.cached_read(sql, csv_path=csv_path)

with pd.option_context('display.max_rows', None):
    display(vtm_duplicates)

,Antibiotic,atc_route,aware_2019,aware_2024,nm,match_type
0,Ampicillin,NaN,Access,Access,Ampicillin + Flucloxacillin,ASSUMED
1,Ceftazidime,NaN,Watch,Watch,Ceftazidime + Avibactam,ASSUMED
2,Ceftazidime + Avibactam,NaN,Reserve,Reserve,Ceftazidime + Avibactam,DIRECT
3,Flucloxacillin,NaN,Access,Access,Ampicillin + Flucloxacillin,ASSUMED
4,Meropenem,NaN,Reserve,Reserve,Meropenem + Vaborbactam,ASSUMED
5,Meropenem + Vaborbactam,NaN,Reserve,Reserve,Meropenem + Vaborbactam,DIRECT
6,Piperacillin,NaN,Watch,Watch,Piperacillin + Tazobactam,ASSUMED
7,Piperacillin + Tazobactam,NaN,Watch,Watch,Piperacillin + Tazobactam,DIRECT

From this we can create a list of the unwanted duplicates to remove from our full list.

In [18]:
sql = f"""
WITH matched_vtms AS (
  SELECT  
    aware.Antibiotic,
    aware.atc_route,
    aware.aware_2019,
    aware.aware_2024,
    vtm.nm,
    CASE
      WHEN aware.Antibiotic = vtm.nm THEN 'DIRECT'
      ELSE 'ASSUMED'
    END AS match_type
  FROM `ebmdatalab.chris.aware_list` aware
  LEFT JOIN `ebmdatalab.dmd.vtm` vtm 
    ON vtm.nm LIKE CONCAT('%', aware.Antibiotic, '%')
  WHERE vtm.invalid IS NOT TRUE
)

SELECT *
FROM matched_vtms
WHERE nm IN (
  SELECT nm
  FROM matched_vtms
  WHERE atc_route IS NULL
  GROUP BY nm
  HAVING COUNT(*) > 1
) AND match_type = 'ASSUMED' 
    AND NOT (Antibiotic='Ampicillin' AND nm='Ampicillin + Flucloxacillin')
ORDER BY Antibiotic ASC;
"""

# Define the CSV path for caching the results.
csv_path = os.path.join('..', 'data', 'vtm_duplicates_direct.csv')

# Use the cached_read function from the bq library to run the query.
vtm_duplicates_direct = bq.cached_read(sql, csv_path=csv_path)

with pd.option_context('display.max_rows', None):
    display(vtm_duplicates_direct)

,Antibiotic,atc_route,aware_2019,aware_2024,nm,match_type
0,Ceftazidime,NaN,Watch,Watch,Ceftazidime + Avibactam,ASSUMED
1,Flucloxacillin,NaN,Access,Access,Ampicillin + Flucloxacillin,ASSUMED
2,Meropenem,NaN,Reserve,Reserve,Meropenem + Vaborbactam,ASSUMED
3,Piperacillin,NaN,Watch,Watch,Piperacillin + Tazobactam,ASSUMED

We can then create a full list of potential VTMs with duplicates removed.

In [19]:
sql = f"""
WITH matched_vtms AS ( -- This query does the fuzzy matching of Antibiotic name to VTM name
  SELECT  
    aware.Antibiotic,
    aware.atc_route,
    aware.aware_2019,
    aware.aware_2024,
    vtm.nm,
    vtm.id,
    CASE
      WHEN aware.Antibiotic = vtm.nm THEN 'DIRECT'
      ELSE 'ASSUMED'
    END AS match_type
  FROM `ebmdatalab.chris.aware_list` aware
  LEFT JOIN `ebmdatalab.dmd.vtm` vtm 
    ON vtm.nm LIKE CONCAT('%', aware.Antibiotic, '%')
  WHERE vtm.invalid IS NOT TRUE
),

manual_exceptions AS ( -- This is a list of manual exceptions used when recluding assumed matches
  SELECT 'Ampicillin' AS Antibiotic, 'Ampicillin + Flucloxacillin' AS nm
  -- Add more rows here as needed
),

duplicate_vtms AS ( -- This produces a list of duplicate rows where a direct match already exists
  SELECT *
  FROM matched_vtms
  WHERE nm IN (
    SELECT nm
    FROM matched_vtms
    WHERE atc_route IS NULL
    GROUP BY nm
    HAVING COUNT(*) > 1
  )
  AND match_type = 'ASSUMED'
  AND NOT EXISTS (
    SELECT 1
    FROM manual_exceptions e
    WHERE e.Antibiotic = matched_vtms.Antibiotic AND e.nm = matched_vtms.nm
  )
)

SELECT
  matched_vtms.Antibiotic,
  matched_vtms.nm,
  matched_vtms.id,
  matched_vtms.atc_route,
  matched_vtms.aware_2019,
  matched_vtms.aware_2024,
FROM matched_vtms
WHERE NOT EXISTS ( -- removes the duplicates identified above
  SELECT 1
  FROM duplicate_vtms
  WHERE matched_vtms.Antibiotic = duplicate_vtms.Antibiotic AND matched_vtms.nm = duplicate_vtms.nm
)
ORDER BY matched_vtms.Antibiotic ASC;
"""

# Define the CSV path for caching the results.
csv_path = os.path.join('..', 'data', 'vtm_match_cleaned.csv')

# Use the cached_read function from the bq library to run the query.
vtm_match_cleaned = bq.cached_read(sql, csv_path=csv_path)

with pd.option_context('display.max_rows', None):
    display(vtm_match_cleaned)

,Antibiotic,nm,id,atc_route,aware_2019,aware_2024
0,Amikacin,Amikacin liposomal,7.824210e+08,NaN,Watch,Watch
1,Amikacin,Amikacin,7.745340e+08,NaN,Watch,Watch
2,Amoxicillin,Amoxicillin,7.745860e+08,NaN,Access,Access
3,Ampicillin,Ampicillin + Flucloxacillin,7.745920e+08,NaN,Access,Access
4,Ampicillin,Ampicillin,7.745900e+08,NaN,Access,Access
5,Azithromycin,Azithromycin,7.747220e+08,NaN,Watch,Watch
6,Aztreonam,Aztreonam + Avibactam,4.379671e+16,NaN,Reserve,Reserve
7,Aztreonam,Aztreonam,7.747250e+08,NaN,Reserve,Reserve
8,Benzathine benzylpenicillin,Benzathine benzylpenicillin,1.234764e+09,NaN,Access,Access
9,Benzylpenicillin,Benzylpenicillin,7.748260e+08,NaN,Access,Access
10,Cefaclor,Cefaclor,7.750860e+08,NaN,Watch,Watch
11,Cefadroxil,Cefadroxil,7.750870e+08,NaN,Watch,Access
12,Cefalexin,Cefalexin,7.750880e+08,NaN,Watch,Access
13,Cefalotin,NaN,NaN,NaN,Watch,Access
14,Cefamandole,Cefamandole,7.750900e+08,NaN,Watch,Watch
15,Cefazolin,Cefazolin,7.750920e+08,NaN,Watch,Access
16,Cefepime,Cefepime,7.750950e+08,NaN,Watch,Watch
17,Cefepime,Cefepime + Enmetazobactam,4.289421e+16,NaN,Watch,Watch
18,Cefiderocol,Cefiderocol,8.302050e+08,NaN,Reserve,Reserve
19,Cefixime,Cefixime,7.750970e+08,NaN,Watch,Watch
20,Cefotaxime,Cefotaxime,7.751030e+08,NaN,Watch,Watch
21,Cefoxitin,Cefoxitin,7.751070e+08,NaN,Watch,Watch
22,Cefradine,Cefradine,7.751120e+08,NaN,Watch,Access
23,Ceftaroline fosamil,Ceftaroline fosamil,2.138731e+16,NaN,Reserve,Reserve
24,Ceftazidime,Ceftazidime,7.751150e+08,NaN,Watch,Watch
25,Ceftazidime + Avibactam,Ceftazidime + Avibactam,7.813000e+08,NaN,Reserve,Reserve
26,Ceftobiprole,Ceftobiprole,1.287090e+09,NaN,Reserve,Reserve
27,Ceftolozane + Tazobactam,Ceftolozane + Tazobactam,7.751190e+08,NaN,Reserve,Reserve
28,Ceftriaxone,Ceftriaxone,7.751200e+08,NaN,Watch,Watch
29,Cefuroxime,Cefuroxime,7.751210e+08,NaN,Watch,Watch
30,Chloramphenicol,Chloramphenicol,7.751600e+08,NaN,Watch,Watch
31,Cilastatin + Imipenem + Relebactam,Cilastatin + Imipenem + Relebactam,7.890740e+08,NaN,Reserve,Reserve
32,Ciprofloxacin,Ciprofloxacin + Fluocinolone acetonide,3.587311e+16,NaN,Watch,Watch
33,Ciprofloxacin,Ciprofloxacin + Dexamethasone,7.752620e+08,NaN,Watch,Watch
34,Ciprofloxacin,Ciprofloxacin,7.752610e+08,NaN,Watch,Watch
35,Clarithromycin,Clarithromycin,7.752770e+08,NaN,Watch,Watch
36,Clindamycin,Benzoyl peroxide + Clindamycin,7.748120e+08,NaN,Watch,Watch
37,Clindamycin,Clindamycin,7.752880e+08,NaN,Watch,Watch
38,Clindamycin,Clindamycin + Hydrocortisone,2.220751e+16,NaN,Watch,Watch
39,Clindamycin,Clindamycin + Tretinoin,7.752890e+08,NaN,Watch,Watch
40,Co-amoxiclav,Co-amoxiclav,7.745870e+08,NaN,Watch,Watch
41,Co-trimoxazole,Co-trimoxazole,1.803751e+16,NaN,Access,Access
42,Colistin,Colistin,7.753730e+08,O,Reserve,Reserve
43,Colistin,Colistin,7.753730e+08,P,Reserve,Reserve
44,Dalbavancin,Dalbavancin,7.754370e+08,NaN,Reserve,Reserve
45,Daptomycin,Daptomycin,7.754510e+08,NaN,Reserve,Reserve
46,Delafloxacin,Delafloxacin,7.754690e+08,NaN,Watch,Watch
47,Demeclocycline,Demeclocycline,7.754760e+08,NaN,Watch,Other
48,Doripenem,Doripenem,7.756890e+08,NaN,Reserve,Reserve
49,Doxycycline,Doxycycline,7.756980e+08,NaN,Access,Access
50,Doxycycline,Betamethasone + Doxycycline + Nystatin,4.058881e+16,NaN,Access,Access
51,Eravacycline,Eravacycline,7.758070e+08,NaN,Reserve,Reserve
52,Ertapenem,Ertapenem,7.758200e+08,NaN,Reserve,Reserve
53,Erythromycin,Isotretinoin + Erythromycin,7.758230e+08,NaN,Watch,Watch
54,Erythromycin,Benzoyl peroxide + Erythromycin,7.748130e+08,NaN,Watch,Watch
55,Erythromycin,Erythromycin ethyl succinate,3.640851e+16,NaN,Watch,Watch
56,Erythromycin,Erythromycin,7.758220e+08,NaN,Watch,Watch
57,Erythromycin,Erythromycin stearate,3.640861e+16,NaN,Watch,Watch
58,Erythromycin,Tretinoin + Erythromycin,7.758250e+08,NaN,Watch,Watch
59,Erythromycin,Erythromycin + Zinc acetate,7.758270e+08,NaN,Watch,Watch
60,Erythromycin,Erythromycin lactobionate,3.640951e+16,NaN,Watch,Watch
61,Fidaxomicin,Fidaxomicin,7.759610e+08,NaN,Watch,Watch
62,Flucloxacillin,Flucloxacillin,7.759790e+08,NaN,Access,Access
63,Fosfomycin,Fosfomycin,7.760410e+08,P,Reserve,Reserve
64,Fosfomycin,Fosfomycin,7.760410e+08,O,Access,Access
65,Fusidic acid,Betamethasone + Fusidic acid,7.748430e+08,NaN,Access,Watch
66,Fusidic acid,Hydrocortisone + Fusidic acid,7.760590e+08,NaN,Access,Watch
67,Fusidic acid,Fusidic acid,7.760580e+08,NaN,Access,Watch
68,Gentamicin,Gentamicin,7.760940e+08,NaN,Access,Access
69,Gentamicin,Gentamicin + Hydrocortisone,7.760950e+08,NaN,Access,Access
70,Imipenem + Cilastatin,Imipenem + Cilastatin,7.752450e+08,NaN,Reserve,Reserve
71,Levofloxacin,Levofloxacin,7.765170e+08,NaN,Watch,Watch
72,Levofloxacin,Dexamethasone + Levofloxacin,1.286887e+09,NaN,Watch,Watch
73,Linezolid,Linezolid,7.765440e+08,NaN,Reserve,Reserve
74,Lymecycline,Lymecycline,7.765930e+08,NaN,Watch,Watch
75,Meropenem,Meropenem,7.766940e+08,NaN,Reserve,Reserve
76,Meropenem + Vaborbactam,Meropenem + Vaborbactam,7.766950e+08,NaN,Reserve,Reserve
77,Methenamine,Methenamine,7.767250e+08,NaN,Other,Other
78,Metronidazole,Metronidazole,7.767740e+08,NaN,Access,Access
79,Minocycline,Minocycline,7.768000e+08,O,Watch,Watch
80,Moxifloxacin,Moxifloxacin,7.768310e+08,NaN,Watch,Watch
81,Nalidixic Acid,NaN,NaN,NaN,Other,Other
82,Neomycin,Clobetasol + Neomycin + Nystatin,7.752960e+08,NaN,Watch,Watch
83,Neomycin,Neomycin + Gramicidin,7.761450e+08,NaN,Watch,Watch
84,Neomycin,Fluocinolone acetonide + Neomycin,2.263691e+16,NaN,Watch,Watch
85,Neomycin,Neomycin + Triamcinolone,7.768900e+08,NaN,Watch,Watch
86,Neomycin,Neomycin + Chlorhexidine,7.751700e+08,NaN,Watch,Watch
87,Neomycin,Betamethasone + Neomycin,7.748440e+08,NaN,Watch,Watch
88,Neomycin,Neomycin + Prednisolone,7.768890e+08,NaN,Watch,Watch
89,Neomycin,Hydrocortisone + Neomycin,7.762540e+08,NaN,Watch,Watch
90,Neomycin,Neomycin,7.768850e+08,NaN,Watch,Watch
91,Nitrofurantoin,Nitrofurantoin,7.769270e+08,NaN,Access,Access
92,Norfloxacin,Norfloxacin,7.769430e+08,NaN,Watch,Watch
93,Ofloxacin,Ofloxacin,7.769730e+08,NaN,Watch,Watch
94,Oritavancin,Oritavancin,7.770010e+08,NaN,Reserve,Reserve
95,Oxytetracycline,Oxytetracycline + Hydrocortisone,7.762570e+08,NaN,Watch,Watch
96,Oxytetracycline,Clobetasone + Oxytetracycline + Nystatin,7.752990e+08,NaN,Watch,Watch
97,Oxytetracycline,Oxytetracycline,7.770350e+08,NaN,Watch,Watch
98,Phenoxymethylpenicillin,Phenoxymethylpenicillin,7.771750e+08,NaN,Access,Access
99,Piperacillin + Tazobactam,Piperacillin + Tazobactam,7.772120e+08,NaN,Watch,Watch
100,Pivmecillinam,Pivmecillinam,7.772270e+08,NaN,Access,Access
101,Pristinamycin,Pristinamycin,1.625101e+16,NaN,Watch,Other
102,Procaine benzylpenicillin,Procaine benzylpenicillin,1.234762e+09,NaN,Access,Access
103,Quinupristin + Dalfopristin,Quinupristin + Dalfopristin,7.754390e+08,NaN,Reserve,Reserve
104,Spectinomycin,Spectinomycin,7.776000e+08,NaN,Other,Other
105,Spiramycin,Spiramycin,7.776020e+08,NaN,Other,Other
106,Streptomycin,Streptomycin,7.776140e+08,P,Other,Other
107,Sulfadiazine,Cerium nitrate + Sulfadiazine silver,4.277911e+16,NaN,Other,Other
108,Sulfadiazine,Sulfadiazine silver,8.640080e+08,NaN,Other,Other
109,Sulfadiazine,Sulfadiazine,7.775320e+08,NaN,Other,Other
110,Sulfamethoxypyridazine,Sulfamethoxypyridazine,7.776430e+08,NaN,Other,Other
111,Sulfapyridine,Sulfapyridine,1.546581e+16,NaN,Other,Other
112,Tedizolid,Tedizolid,7.776860e+08,NaN,Reserve,Reserve
113,Teicoplanin,Teicoplanin,7.776910e+08,NaN,Watch,Watch
114,Telavancin,Telavancin,7.776930e+08,NaN,Reserve,Reserve
115,Temocillin,Temocillin,7.777000e+08,NaN,Watch,Watch
116,Tetracycline,Tetracycline,7.777300e+08,NaN,Access,Access
117,Tigecycline,Tigecycline,7.777690e+08,NaN,Reserve,Reserve
118,Tinidazole,Tinidazole,7.777750e+08,NaN,Other,Access
119,Tobramycin,Tobramycin,7.777910e+08,NaN,Watch,Watch
120,Tobramycin,Dexamethasone + Tobramycin,7.755020e+08,NaN,Watch,Watch
121,Trimethoprim,Trimethoprim,7.778580e+08,NaN,Access,Access
122,Trimethoprim,Polymyxin B + Trimethoprim,7.772470e+08,NaN,Access,Access
123,Vancomycin,Vancomycin,7.779140e+08,NaN,Watch,Watch

### Bringing in VMPs

Now that we have a list of dm+d compatible VTMs, we can bring in matching VMPs.

In [26]:
sql = f"""
WITH matched_vtms AS ( -- This query does the fuzzy matching of Antibiotic name to VTM name
  SELECT  
    aware.Antibiotic,
    aware.atc_route,
    aware.aware_2019,
    aware.aware_2024,
    vtm.nm,
    vtm.id,
    CASE
      WHEN aware.Antibiotic = vtm.nm THEN 'DIRECT'
      ELSE 'ASSUMED'
    END AS match_type
  FROM `ebmdatalab.chris.aware_list` aware
  LEFT JOIN `ebmdatalab.dmd.vtm` vtm 
    ON vtm.nm LIKE CONCAT('%', aware.Antibiotic, '%')
  WHERE vtm.invalid IS NOT TRUE
),

manual_exceptions AS ( -- This is a list of manual exceptions used when recluding assumed matches
  SELECT 'Ampicillin' AS Antibiotic, 'Ampicillin + Flucloxacillin' AS nm
  -- Add more rows here as needed
),

duplicate_vtms AS ( -- This produces a list of duplicate rows where a direct match already exists
  SELECT *
  FROM matched_vtms
  WHERE nm IN (
    SELECT nm
    FROM matched_vtms
    WHERE atc_route IS NULL
    GROUP BY nm
    HAVING COUNT(*) > 1
  )
  AND match_type = 'ASSUMED'
  AND NOT EXISTS (
    SELECT 1
    FROM manual_exceptions e
    WHERE e.Antibiotic = matched_vtms.Antibiotic AND e.nm = matched_vtms.nm
  )
),

vmp_with_route AS (
  SELECT DISTINCT
    vmp.id AS id,
    vmp.vtm AS vtm,
    vmp.nm AS nm,
    COALESCE(sroute.route, routelookup.who_route) AS vmp_atc_route
  FROM `ebmdatalab.dmd.vmp` vmp
  LEFT JOIN dmd.ont ont ON vmp.id = ont.vmp
  LEFT JOIN dmd.ontformroute ofr ON ont.form = ofr.cd
  LEFT JOIN chris.vmp_single_route_identifier sroute ON vmp.id = sroute.vmp_id
  LEFT JOIN `scmd_dmd_views.dmd_to_atc_route` routelookup ON ofr.descr = routelookup.dmd_ofr
)

SELECT DISTINCT
  matched_vtms.Antibiotic,
  matched_vtms.nm as vtm_nm,
  matched_vtms.id as vtm_id,
  vmp.nm as vmp_nm,
  vmp.id as vmp_id,
  vmp.vmp_atc_route,
  matched_vtms.atc_route,
  matched_vtms.aware_2019,
  matched_vtms.aware_2024
FROM matched_vtms
LEFT JOIN vmp_with_route vmp
  ON matched_vtms.id = vmp.vtm
  AND (
    matched_vtms.atc_route IS NULL
    OR matched_vtms.atc_route = vmp.vmp_atc_route
  )
WHERE NOT EXISTS ( -- removes the duplicates identified above
  SELECT 1
  FROM duplicate_vtms
  WHERE matched_vtms.Antibiotic = duplicate_vtms.Antibiotic AND matched_vtms.nm = duplicate_vtms.nm
)
ORDER BY matched_vtms.Antibiotic ASC;
"""

# Define the CSV path for caching the results.
csv_path = os.path.join('..', 'data', 'vmps_matched.csv')

# Use the cached_read function from the bq library to run the query.
vmps_matched = bq.cached_read(sql, csv_path=csv_path)

vmps_matched

Downloading: 100%|█████████████████████████████████████████████████████████████|

,Antibiotic,vtm_nm,vtm_id,vmp_nm,vmp_id,vmp_atc_route,atc_route,aware_2019,aware_2024
0,Amikacin,Amikacin liposomal,782421008,Amikacin liposomal 590mg nebuliser dispersion ...,39601711000001109,Inhal.solution,None,Watch,Watch
1,Amikacin,Amikacin,774534000,Amikacin 500mg/2ml solution for injection ampo...,44422511000001103,P,None,Watch,Watch
2,Amikacin,Amikacin,774534000,Amikacin 25mg/5ml solution for injection ampoules,44007311000001107,None,None,Watch,Watch
3,Amikacin,Amikacin,774534000,Amikacin 500mg/100ml infusion polyethylene bot...,41823511000001108,P,None,Watch,Watch
4,Amikacin,Amikacin,774534000,Amikacin 400micrograms/0.1ml intravitreal inje...,38244211000001108,None,None,Watch,Watch
...,...,...,...,...,...,...,...,...,...
703,Vancomycin,Vancomycin,777914002,Vancomycin 62.5mg/5ml oral solution,13455811000001106,O,None,Watch,Watch
704,Vancomycin,Vancomycin,777914002,Vancomycin 125mg/5ml oral solution,15453011000001107,O,None,Watch,Watch
705,Vancomycin,Vancomycin,777914002,Vancomycin 125mg/5ml oral suspension,15453111000001108,O,None,Watch,Watch
706,Vancomycin,Vancomycin,777914002,Vancomycin 5% eye drops,21407511000001100,None,None,Watch,Watch
707,Vancomycin,Vancomycin,777914002,Vancomycin 1.4% eye drops,22103111000001101,None,None,Watch,Watch

Inspecting this list we can see a number of non-systemic antibiotics which are not considered as part of the AWaRe classification - e.g. eye drops, ointments etc. We can remove these by filtering out when selecting VMPs.

In [21]:
sql = f"""
WITH matched_vtms AS ( -- This query does the fuzzy matching of Antibiotic name to VTM name
  SELECT  
    aware.Antibiotic,
    aware.atc_route,
    aware.aware_2019,
    aware.aware_2024,
    vtm.nm,
    vtm.id,
    CASE
      WHEN aware.Antibiotic = vtm.nm THEN 'DIRECT'
      ELSE 'ASSUMED'
    END AS match_type
  FROM `ebmdatalab.chris.aware_list` aware
  LEFT JOIN `ebmdatalab.dmd.vtm` vtm 
    ON vtm.nm LIKE CONCAT('%', aware.Antibiotic, '%')
  WHERE vtm.invalid IS NOT TRUE
),

manual_exceptions AS ( -- This is a list of manual exceptions used when recluding assumed matches
  SELECT 'Ampicillin' AS Antibiotic, 'Ampicillin + Flucloxacillin' AS nm
  -- Add more rows here as needed
),

duplicate_vtms AS ( -- This produces a list of duplicate rows where a direct match already exists
  SELECT *
  FROM matched_vtms
  WHERE nm IN (
    SELECT nm
    FROM matched_vtms
    WHERE atc_route IS NULL
    GROUP BY nm
    HAVING COUNT(*) > 1
  )
  AND match_type = 'ASSUMED'
  AND NOT EXISTS (
    SELECT 1
    FROM manual_exceptions e
    WHERE e.Antibiotic = matched_vtms.Antibiotic AND e.nm = matched_vtms.nm
  )
),

vmp_with_route AS (
  SELECT DISTINCT
    vmp.id AS id,
    vmp.vtm AS vtm,
    vmp.nm AS nm,
    COALESCE(sroute.route, routelookup.who_route) AS vmp_atc_route
  FROM `ebmdatalab.dmd.vmp` vmp
  LEFT JOIN dmd.ont ont ON vmp.id = ont.vmp
  LEFT JOIN dmd.ontformroute ofr ON ont.form = ofr.cd
  LEFT JOIN chris.vmp_single_route_identifier sroute ON vmp.id = sroute.vmp_id
  LEFT JOIN `scmd_dmd_views.dmd_to_atc_route` routelookup ON ofr.descr = routelookup.dmd_ofr
  WHERE ofr.descr NOT LIKE '%.auricular'
  AND ofr.descr NOT LIKE '%.cutaneous'
  AND ofr.descr NOT LIKE '%.ophthalmic'
  AND ofr.descr NOT LIKE '%.oromucosal'
  AND ofr.descr NOT LIKE '%.intralesional'
  AND ofr.descr NOT LIKE '%.nasal'
)

SELECT DISTINCT
  matched_vtms.Antibiotic,
  matched_vtms.nm as vtm_nm,
  matched_vtms.id as vtm_id,
  vmp.nm as vmp_nm,
  vmp.id as vmp_id,
  vmp.vmp_atc_route,
  matched_vtms.atc_route,
  matched_vtms.aware_2019,
  matched_vtms.aware_2024
FROM matched_vtms
LEFT JOIN vmp_with_route vmp
  ON matched_vtms.id = vmp.vtm
  AND (
    matched_vtms.atc_route IS NULL
    OR matched_vtms.atc_route = vmp.vmp_atc_route
  )
WHERE NOT EXISTS ( -- removes the duplicates identified above
  SELECT 1
  FROM duplicate_vtms
  WHERE matched_vtms.Antibiotic = duplicate_vtms.Antibiotic AND matched_vtms.nm = duplicate_vtms.nm
) AND vmp.id IS NOT NULL
ORDER BY matched_vtms.Antibiotic ASC;
"""

# Define the CSV path for caching the results.
csv_path = os.path.join('..', 'data', 'vmps_matched.csv')

# Use the cached_read function from the bq library to run the query.
vmps_matched = bq.cached_read(sql, csv_path=csv_path)

with pd.option_context('display.max_rows', None):
    display(vmps_matched)

Downloading: 100%|█████████████████████████████████████████████████████████████|

,Antibiotic,vtm_nm,vtm_id,vmp_nm,vmp_id,vmp_atc_route,atc_route,aware_2019,aware_2024
0,Amikacin,Amikacin liposomal,782421008,Amikacin liposomal 590mg nebuliser dispersion ...,39601711000001109,Inhal.solution,None,Watch,Watch
1,Amikacin,Amikacin,774534000,Amikacin 500mg/2ml solution for injection ampo...,44422511000001103,P,None,Watch,Watch
2,Amikacin,Amikacin,774534000,Amikacin 25mg/5ml solution for injection ampoules,44007311000001107,None,None,Watch,Watch
3,Amikacin,Amikacin,774534000,Amikacin 500mg/100ml infusion polyethylene bot...,41823511000001108,P,None,Watch,Watch
4,Amikacin,Amikacin,774534000,Amikacin 400micrograms/0.1ml intravitreal inje...,38244211000001108,None,None,Watch,Watch
5,Amikacin,Amikacin,774534000,Amikacin 25mg/5ml solution for injection vials,35111911000001104,None,None,Watch,Watch
6,Amikacin,Amikacin,774534000,Amikacin 25mg/5ml solution for injection pre-f...,35104511000001105,None,None,Watch,Watch
7,Amikacin,Amikacin,774534000,Amikacin 500mg/2ml solution for injection vials,35899911000001109,P,None,Watch,Watch
8,Amikacin,Amikacin,774534000,Amikacin 100mg/2ml solution for injection vials,35899811000001104,P,None,Watch,Watch
9,Amoxicillin,Amoxicillin,774586009,Amoxicillin 500mg/50ml infusion bags,34226911000001109,P,None,Access,Access
10,Amoxicillin,Amoxicillin,774586009,Amoxicillin 250mg capsules,39732311000001104,O,None,Access,Access
11,Amoxicillin,Amoxicillin,774586009,Amoxicillin 500mg capsules,39732411000001106,O,None,Access,Access
12,Amoxicillin,Amoxicillin,774586009,Amoxicillin 250mg/5ml oral suspension,41941111000001109,O,None,Access,Access
13,Amoxicillin,Amoxicillin,774586009,Amoxicillin 250mg/5ml oral suspension sugar free,39021911000001105,O,None,Access,Access
14,Amoxicillin,Amoxicillin,774586009,Amoxicillin 125mg/5ml oral suspension,41940811000001105,O,None,Access,Access
15,Amoxicillin,Amoxicillin,774586009,Amoxicillin 125mg/5ml oral suspension sugar free,35901911000001104,O,None,Access,Access
16,Amoxicillin,Amoxicillin,774586009,Amoxicillin 125mg/1.25ml oral suspension paedi...,35368511000001109,O,None,Access,Access
17,Amoxicillin,Amoxicillin,774586009,Amoxicillin 500mg powder for solution for inje...,41941211000001103,P,None,Access,Access
18,Amoxicillin,Amoxicillin,774586009,Amoxicillin 250mg powder for solution for inje...,41941011000001108,P,None,Access,Access
19,Amoxicillin,Amoxicillin,774586009,Amoxicillin 1g powder for solution for injecti...,41940911000001100,P,None,Access,Access
20,Amoxicillin,Amoxicillin,774586009,Amoxicillin 3g oral powder sachets sugar free,35902111000001107,O,None,Access,Access
21,Amoxicillin,Amoxicillin,774586009,Amoxicillin 500mg tablets,44456411000001100,O,None,Access,Access
22,Amoxicillin,Amoxicillin,774586009,Amoxicillin 1g dispersible tablets sugar free,38726811000001109,O,None,Access,Access
23,Amoxicillin,Amoxicillin,774586009,Amoxicillin 500mg/5ml oral suspension sugar free,41941311000001106,O,None,Access,Access
24,Ampicillin,Ampicillin,774590006,Ampicillin 250mg capsules,41941511000001100,O,None,Access,Access
25,Ampicillin,Ampicillin,774590006,Ampicillin 500mg capsules,41941711000001105,O,None,Access,Access
26,Ampicillin,Ampicillin,774590006,Ampicillin 125mg/5ml oral suspension,41941411000001104,O,None,Access,Access
27,Ampicillin,Ampicillin,774590006,Ampicillin 250mg/5ml oral suspension,41941611000001101,O,None,Access,Access
28,Ampicillin,Ampicillin,774590006,Ampicillin 500mg powder for solution for injec...,41941811000001102,P,None,Access,Access
29,Ampicillin,Ampicillin,774590006,Ampicillin 500mg powder for solution for injec...,41941811000001102,None,None,Access,Access
30,Azithromycin,Azithromycin,774722005,Azithromycin 500mg powder for solution for inf...,41942111000001104,P,None,Watch,Watch
31,Azithromycin,Azithromycin,774722005,Azithromycin 500mg tablets,39733511000001103,O,None,Watch,Watch
32,Azithromycin,Azithromycin,774722005,Azithromycin 250mg capsules,41942011000001100,O,None,Watch,Watch
33,Azithromycin,Azithromycin,774722005,Azithromycin 200mg/5ml oral suspension,41941911000001107,O,None,Watch,Watch
34,Azithromycin,Azithromycin,774722005,Azithromycin 250mg tablets,11034311000001100,O,None,Watch,Watch
35,Azithromycin,Azithromycin,774722005,Azithromycin 200mg/5ml oral suspension sugar free,29668711000001101,O,None,Watch,Watch
36,Aztreonam,Aztreonam + Avibactam,43796711000001109,Aztreonam 1.5g / Avibactam 500mg powder for so...,43801411000001109,P,None,Reserve,Reserve
37,Aztreonam,Aztreonam,774725007,Aztreonam 75mg powder and solvent for nebulise...,17463011000001100,Inhal.solution,None,Reserve,Reserve
38,Aztreonam,Aztreonam,774725007,Aztreonam 500mg powder for solution for inject...,41759611000001105,P,None,Reserve,Reserve
39,Aztreonam,Aztreonam,774725007,Aztreonam 1g powder for solution for injection...,41759411000001107,P,None,Reserve,Reserve
40,Aztreonam,Aztreonam,774725007,Aztreonam 2g powder for solution for injection...,41759511000001106,P,None,Reserve,Reserve
41,Aztreonam,Aztreonam,774725007,Aztreonam 75mg powder and solvent for nebulise...,17463411000001109,Inhal.solution,None,Reserve,Reserve
42,Benzathine benzylpenicillin,Benzathine benzylpenicillin,1234764000,Benzathine benzylpenicillin 2.4million unit po...,44168511000001109,P,None,Access,Access
43,Benzathine benzylpenicillin,Benzathine benzylpenicillin,1234764000,Benzathine benzylpenicillin 1.2million unit po...,42683111000001104,P,None,Access,Access
44,Benzathine benzylpenicillin,Benzathine benzylpenicillin,1234764000,Benzathine benzylpenicillin 1.2million unit po...,10153111000001102,P,None,Access,Access
45,Benzathine benzylpenicillin,Benzathine benzylpenicillin,1234764000,Benzathine benzylpenicillin 2.4million unit po...,10153211000001108,P,None,Access,Access
46,Benzathine benzylpenicillin,Benzathine benzylpenicillin,1234764000,"Benzathine benzylpenicillin 600,000unit powder...",10150911000001107,P,None,Access,Access
47,Benzylpenicillin,Benzylpenicillin,774826003,Benzylpenicillin sodium 1.2g/50ml infusion bags,22097311000001100,P,None,Access,Access
48,Benzylpenicillin,Benzylpenicillin,774826003,Benzylpenicillin sodium 600mg/50ml infusion bags,22085911000001105,P,None,Access,Access
49,Benzylpenicillin,Benzylpenicillin,774826003,Benzylpenicillin sodium 600mg powder for solut...,41942311000001102,P,None,Access,Access
50,Benzylpenicillin,Benzylpenicillin,774826003,Benzylpenicillin sodium 1.2g powder for soluti...,41942211000001105,P,None,Access,Access
51,Cefaclor,Cefaclor,775086009,Cefaclor 250mg capsules,39735011000001107,O,None,Watch,Watch
52,Cefaclor,Cefaclor,775086009,Cefaclor 500mg capsules,39735111000001108,O,None,Watch,Watch
53,Cefaclor,Cefaclor,775086009,Cefaclor 375mg modified-release tablets,36134211000001100,O,None,Watch,Watch
54,Cefaclor,Cefaclor,775086009,Cefaclor 125mg/5ml oral suspension sugar free,36134011000001105,O,None,Watch,Watch
55,Cefaclor,Cefaclor,775086009,Cefaclor 250mg/5ml oral suspension sugar free,36134111000001106,O,None,Watch,Watch
56,Cefaclor,Cefaclor,775086009,Cefaclor 250mg/5ml oral suspension,41942611000001107,O,None,Watch,Watch
57,Cefaclor,Cefaclor,775086009,Cefaclor 125mg/5ml oral suspension,41942511000001108,O,None,Watch,Watch
58,Cefadroxil,Cefadroxil,775087000,Cefadroxil 500mg capsules,39735211000001102,O,None,Watch,Access
59,Cefadroxil,Cefadroxil,775087000,Cefadroxil 125mg/5ml oral suspension,41942711000001103,O,None,Watch,Access
60,Cefadroxil,Cefadroxil,775087000,Cefadroxil 250mg/5ml oral suspension,41942811000001106,O,None,Watch,Access
61,Cefadroxil,Cefadroxil,775087000,Cefadroxil 500mg/5ml oral suspension,41942911000001101,O,None,Watch,Access
62,Cefalexin,Cefalexin,775088005,Cefalexin 250mg/5ml oral suspension,41943111000001105,O,None,Watch,Access
63,Cefalexin,Cefalexin,775088005,Cefalexin 250mg capsules,39735311000001105,O,None,Watch,Access
64,Cefalexin,Cefalexin,775088005,Cefalexin 125mg/5ml oral suspension,41943011000001109,O,None,Watch,Access
65,Cefalexin,Cefalexin,775088005,Cefalexin 500mg capsules,39694811000001102,O,None,Watch,Access
66,Cefalexin,Cefalexin,775088005,Cefalexin 250mg tablets,39684111000001105,O,None,Watch,Access
67,Cefalexin,Cefalexin,775088005,Cefalexin 500mg tablets,39735911000001106,O,None,Watch,Access
68,Cefalexin,Cefalexin,775088005,Cefalexin 500mg/5ml oral suspension,36134311000001108,O,None,Watch,Access
69,Cefalexin,Cefalexin,775088005,Cefalexin 250mg/5ml oral suspension sugar free,4515811000001108,O,None,Watch,Access
70,Cefalexin,Cefalexin,775088005,Cefalexin 125mg/5ml oral suspension sugar free,4865011000001104,O,None,Watch,Access
71,Cefamandole,Cefamandole,775090006,Cefamandole 1g powder for solution for injecti...,4457111000001107,P,None,Watch,Watch
72,Cefazolin,Cefazolin,775092003,Cefazolin 1g powder for solution for injection...,41872611000001103,P,None,Watch,Access
73,Cefazolin,Cefazolin,775092003,Cefazolin 500mg powder for solution for inject...,41872711000001107,P,None,Watch,Access
74,Cefazolin,Cefazolin,775092003,Cefazolin 2g powder for solution for injection...,33631211000001106,P,None,Watch,Access
75,Cefepime,Cefepime,775095001,Cefepime 1g powder for solution for injection ...,36458411000001105,P,None,Watch,Watch
76,Cefepime,Cefepime,775095001,Cefepime 2g powder for solution for injection ...,36458511000001109,P,None,Watch,Watch
77,Cefepime,Cefepime + Enmetazobactam,42894211000001100,Cefepime 2g / Enmetazobactam 500mg powder for ...,42894511000001102,P,None,Watch,Watch
78,Cefiderocol,Cefiderocol,830205006,Cefiderocol 1g powder for solution for infusio...,39002611000001100,P,None,Reserve,Reserve
79,Cefixime,Cefixime,775097009,Cefixime 200mg tablets,41943211000001104,O,None,Watch,Watch
80,Cefixime,Cefixime,775097009,Cefixime 100mg/5ml oral suspension,36134411000001101,O,None,Watch,Watch
81,Cefixime,Cefixime,775097009,Cefixime 400mg tablets,41943311000001107,O,None,Watch,Watch
82,Cefotaxime,Cefotaxime,775103002,Cefotaxime 1g/50ml infusion bags,44009011000001100,P,None,Watch,Watch
83,Cefotaxime,Cefotaxime,775103002,Cefotaxime 2g/100ml infusion bags,44007911000001108,P,None,Watch,Watch
84,Cefotaxime,Cefotaxime,775103002,Cefotaxime 1g powder for solution for injectio...,41943411000001100,P,None,Watch,Watch
85,Cefotaxime,Cefotaxime,775103002,Cefotaxime 500mg powder for solution for injec...,41943511000001101,P,None,Watch,Watch
86,Cefotaxime,Cefotaxime,775103002,Cefotaxime 2g powder for solution for injectio...,4558311000001100,P,None,Watch,Watch
87,Cefoxitin,Cefoxitin,775107001,Cefoxitin 1g powder for solution for injection...,41943611000001102,P,None,Watch,Watch
88,Cefoxitin,Cefoxitin,775107001,Cefoxitin 2g powder for solution for injection...,41943711000001106,P,None,Watch,Watch
89,Cefradine,Cefradine,775112000,Cefradine 250mg capsules,41944511000001103,O,None,Watch,Access
90,Cefradine,Cefradine,775112000,Cefradine 500mg capsules,41944611000001104,O,None,Watch,Access
91,Cefradine,Cefradine,775112000,Cefradine 1g powder for solution for injection...,41944411000001102,P,None,Watch,Access
92,Cefradine,Cefradine,775112000,Cefradine 500mg powder for solution for inject...,41944711000001108,P,None,Watch,Access
93,Cefradine,Cefradine,775112000,Cefradine 250mg/5ml oral solution,36134511000001102,O,None,Watch,Access
94,Ceftaroline fosamil,Ceftaroline fosamil,21387311000001104,Ceftaroline fosamil 600mg powder for solution ...,21386911000001101,P,None,Reserve,Reserve
95,Ceftazidime,Ceftazidime,775115003,Ceftazidime 2mg/0.1ml solution for injection p...,40558111000001101,None,None,Watch,Watch
96,Ceftazidime,Ceftazidime,775115003,Ceftazidime 1g/50ml solution for infusion pre-...,22455011000001109,P,None,Watch,Watch
97,Ceftazidime,Ceftazidime,775115003,Ceftazidime 1g/50ml infusion bags,22097911000001104,P,None,Watch,Watch
98,Ceftazidime,Ceftazidime,775115003,Ceftazidime 1g/25ml solution for infusion pre-...,22098511000001105,P,None,Watch,Watch
99,Ceftazidime,Ceftazidime,775115003,Ceftazidime 2g intravenous infusion vials,323856006,P,None,Watch,Watch
100,Ceftazidime,Ceftazidime,775115003,Ceftazidime 1g powder for solution for injecti...,41944811000001100,P,None,Watch,Watch
101,Ceftazidime,Ceftazidime,775115003,Ceftazidime 250mg powder for solution for inje...,41944911000001105,P,None,Watch,Watch
102,Ceftazidime,Ceftazidime,775115003,Ceftazidime 500mg powder for solution for inje...,41945211000001100,P,None,Watch,Watch
103,Ceftazidime,Ceftazidime,775115003,Ceftazidime 2g powder for solution for injecti...,41945011000001105,P,None,Watch,Watch
104,Ceftazidime,Ceftazidime,775115003,Ceftazidime 3g powder for solution for injecti...,41945111000001106,P,None,Watch,Watch
105,Ceftazidime + Avibactam,Ceftazidime + Avibactam,781300005,Ceftazidime 2g / Avibactam 500mg powder for so...,34179911000001103,P,None,Reserve,Reserve
106,Ceftobiprole,Ceftobiprole,1287090001,Ceftobiprole 500mg powder for solution for inf...,31008911000001103,P,None,Reserve,Reserve
107,Ceftolozane + Tazobactam,Ceftolozane + Tazobactam,775119009,Ceftolozane 1g / Tazobactam 500mg powder for s...,31007811000001109,P,None,Reserve,Reserve
108,Ceftriaxone,Ceftriaxone,775120003,Ceftriaxone 2g powder for solution for infusio...,23107411000001109,P,None,Watch,Watch
109,Ceftriaxone,Ceftriaxone,775120003,Ceftriaxone 1g/50ml infusion bags,22102411000001102,P,None,Watch,Watch
110,Ceftriaxone,Ceftriaxone,775120003,Ceftriaxone 1g powder for solution for injecti...,41945311000001108,P,None,Watch,Watch
111,Ceftriaxone,Ceftriaxone,775120003,Ceftriaxone 250mg powder for solution for inje...,41945511000001102,P,None,Watch,Watch
112,Ceftriaxone,Ceftriaxone,775120003,Ceftriaxone 2g powder for solution for injecti...,41945611000001103,P,None,Watch,Watch
113,Cefuroxime,Cefuroxime,775121004,Cefuroxime 3mg/0.3ml solution for injection pr...,30791311000001104,None,None,Watch,Watch
114,Cefuroxime,Cefuroxime,775121004,Cefuroxime 1.5g/50ml infusion bags,35893011000001107,P,None,Watch,Watch
115,Cefuroxime,Cefuroxime,775121004,Cefuroxime 750mg/50ml infusion bags,35893111000001108,P,None,Watch,Watch
116,Cefuroxime,Cefuroxime,775121004,Cefuroxime 1.5g/100ml infusion bags,23683311000001109,P,None,Watch,Watch
117,Cefuroxime,Cefuroxime,775121004,Cefuroxime 300micrograms/0.3ml solution for in...,22104011000001100,None,None,Watch,Watch
118,Cefuroxime,Cefuroxime,775121004,Cefuroxime 1mg/0.1ml solution for injection pr...,22041211000001105,None,None,Watch,Watch
119,Cefuroxime,Cefuroxime,775121004,Cefuroxime 50mg powder for solution for inject...,21797311000001102,None,None,Watch,Watch
120,Cefuroxime,Cefuroxime,775121004,Cefuroxime 125mg/5ml oral suspension,41945811000001104,O,None,Watch,Watch
121,Cefuroxime,Cefuroxime,775121004,Cefuroxime 250mg tablets,39694611000001101,O,None,Watch,Watch
122,Cefuroxime,Cefuroxime,775121004,Cefuroxime 125mg tablets,39684511000001101,O,None,Watch,Watch
123,Cefuroxime,Cefuroxime,775121004,Cefuroxime 125mg granules for oral suspension ...,41945711000001107,O,None,Watch,Watch
124,Cefuroxime,Cefuroxime,775121004,Cefuroxime 750mg powder for solution for injec...,36134711000001107,P,None,Watch,Watch
125,Cefuroxime,Cefuroxime,775121004,Cefuroxime 1.5g powder for solution for inject...,4557611000001106,P,None,Watch,Watch
126,Cefuroxime,Cefuroxime,775121004,Cefuroxime 250mg powder for solution for injec...,41945911000001109,P,None,Watch,Watch
127,Chloramphenicol,Chloramphenicol,775160002,Chloramphenicol 250mg capsules,41946111000001100,O,None,Watch,Watch
128,Chloramphenicol,Chloramphenicol,775160002,Chloramphenicol 1g powder for solution for inj...,41946011000001101,P,None,Watch,Watch
129,Cilastatin + Imipenem + Relebactam,Cilastatin + Imipenem + Relebactam,789074009,Generic Recarbrio 500mg/500mg/250mg powder for...,38840011000001101,P,None,Reserve,Reserve
130,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 100mg tablets,39686211000001109,O,None,Watch,Watch
131,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 250mg tablets,39687511000001109,O,None,Watch,Watch
132,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 500mg tablets,39687811000001107,O,None,Watch,Watch
133,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 750mg tablets,39687011000001101,O,None,Watch,Watch
134,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 400mg/200ml infusion bags,36141511000001100,P,None,Watch,Watch
135,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 200mg/100ml infusion bags,36141011000001108,P,None,Watch,Watch
136,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 100mg/50ml solution for infusion...,36140911000001100,P,None,Watch,Watch
137,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 250mg/5ml oral suspension,41760211000001107,O,None,Watch,Watch
138,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 200mg/100ml solution for infusio...,8967411000001108,P,None,Watch,Watch
139,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 400mg/200ml solution for infusio...,8973011000001101,P,None,Watch,Watch
140,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 100mg/50ml solution for infusion...,10892711000001106,P,None,Watch,Watch
141,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 200mg/100ml solution for infusio...,10892811000001103,P,None,Watch,Watch
142,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 400mg/200ml solution for infusio...,10892911000001108,P,None,Watch,Watch
143,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 45mg/5ml oral suspension,12020411000001104,O,None,Watch,Watch
144,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 500mg/5ml oral suspension,12020511000001100,O,None,Watch,Watch
145,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 50mg/5ml oral suspension,12020611000001101,O,None,Watch,Watch
146,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 60mg/5ml oral suspension,12020711000001105,O,None,Watch,Watch
147,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 75mg/5ml oral suspension,12020811000001102,O,None,Watch,Watch
148,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 80mg/5ml oral suspension,12020911000001107,O,None,Watch,Watch
149,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 100mg/5ml oral suspension,12019511000001104,O,None,Watch,Watch
150,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 125mg/5ml oral suspension,12019611000001100,O,None,Watch,Watch
151,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 150mg/5ml oral suspension,12019711000001109,O,None,Watch,Watch
152,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 165mg/5ml oral suspension,12019811000001101,O,None,Watch,Watch
153,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 170mg/5ml oral suspension,12019911000001106,O,None,Watch,Watch
154,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 175mg/5ml oral suspension,12020011000001108,O,None,Watch,Watch
155,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 20mg/5ml oral suspension,12020111000001109,O,None,Watch,Watch
156,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 375mg/5ml oral suspension,12020211000001103,O,None,Watch,Watch
157,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 40mg/5ml oral suspension,12020311000001106,O,None,Watch,Watch
158,Clarithromycin,Clarithromycin,775277005,Clarithromycin 500mg/250ml infusion bags,22390311000001100,P,None,Watch,Watch
159,Clarithromycin,Clarithromycin,775277005,Clarithromycin 500mg tablets,41946511000001109,O,None,Watch,Watch
160,Clarithromycin,Clarithromycin,775277005,Clarithromycin 250mg tablets,41946311000001103,O,None,Watch,Watch
161,Clarithromycin,Clarithromycin,775277005,Clarithromycin 500mg modified-release tablets,36142611000001107,O,None,Watch,Watch
162,Clarithromycin,Clarithromycin,775277005,Clarithromycin 125mg/5ml oral suspension,35368711000001104,O,None,Watch,Watch
163,Clarithromycin,Clarithromycin,775277005,Clarithromycin 250mg/5ml oral suspension,37083211000001101,O,None,Watch,Watch
164,Clarithromycin,Clarithromycin,775277005,Clarithromycin 500mg powder for solution for i...,41946411000001105,P,None,Watch,Watch
165,Clarithromycin,Clarithromycin,775277005,Clarithromycin 250mg granules for oral suspens...,41946211000001106,O,None,Watch,Watch

In [27]:
vmps_matched.to_csv('vmp_matched.csv', index=False)