### UK Access, Watch, Reserve, and Other classification for antibiotics in dmd

The ["UK Access, Watch, Reserve, and Other classification for antibiotics"](https://www.gov.uk/government/publications/uk-aware-antibiotic-classification/uk-access-watch-reserve-and-other-classification-for-antibiotics-uk-aware-antibiotic-classification) categorises antibiotics into groups such as Access, Watch, and Reserve to guide healthcare professionals in optimising their use and mitigating antimicrobial resistance.

The existing list on the UKHSA site is not machine readable. To facilitate research, it is helpful to link this categorisation to the [dm+d standard](https://www.nhsbsa.nhs.uk/pharmacies-gp-practices-and-appliance-contractors/dictionary-medicines-and-devices-dmd).

### Imports
We need to import some libaries to help with the code

In [13]:
import pandas as pd
import requests
from ebmdatalab import bq
import os

### Getting the AWaRe list
The AWaRe list is currently available on the following webpage. We can read the html page directly into Pandas to retrieve the first table.

In [14]:
# Set URL to scrape
url = "https://www.gov.uk/government/publications/uk-aware-antibiotic-classification/uk-access-watch-reserve-and-other-classification-for-antibiotics-uk-aware-antibiotic-classification"

# Read the first HTML table from the page into a DataFrame using the HTML content
df_scrape = pd.read_html(url)[0]

# Display the DataFrame
df_scrape

,Antibiotic,England-adapted 2019 AWaRe category,UK-adapted 2024 AWaRe category
0,Amikacin,Watch,Watch
1,Amoxicillin,Access,Access
2,Amoxicillin/ clavulanic-acid,Watch,Watch
3,Ampicillin,Access,Access
4,Azithromycin,Watch,Watch
...,...,...,...
85,Tigecycline,Reserve,Reserve
86,Tinidazole #,Other,Access
87,Tobramycin,Watch,Watch
88,Trimethoprim,Access,Access
89,Vancomycin,Watch,Watch

The [WHO produce an AWaRe list](https://www.who.int/publications/i/item/WHO-MHP-HPS-EML-2023.04) from which the UK version is adapted. In the WHO version ATC codes are mapped to Antibiotic name.

In [15]:
who_to_atc_path = os.path.join('..', 'data', 'WHO_Antibiotic_to_ATC.csv')
who_antibiotic_to_atc = pd.read_csv(who_to_atc_path)
who_antibiotic_to_atc

,Antibiotic,Class,ATC code
0,Amikacin,Aminoglycosides,J01GB06
1,Amoxicillin,Penicillins,J01CA04
2,Amoxicillin/clavulanic-acid,Beta-lactam/beta-lactamase-inhibitor,J01CR02
3,Ampicillin,Penicillins,J01CA01
4,Ampicillin/sulbactam,Beta-lactam/beta-lactamase-inhibitor,J01CR01
...,...,...,...
252,Trimethoprim,Trimethoprim-derivatives,J01EA01
253,Troleandomycin,Macrolides,J01FA08
254,Trovafloxacin,Fluoroquinolones,J01MA13
255,Vancomycin_IV,Glycopeptides,J01XA01
256,Vancomycin_oral,Glycopeptides,A07AA09

### Cleaning up the UKHSA list
The list contains some characters or identifiers that could break matching, we need to clean these up.

The # symbol is used to denote where category has changed, remove this

In [16]:
df_scrape['Antibiotic'] = df_scrape['Antibiotic'].str.replace(" #", "", regex=False)

We can review remaining rows that contain non-alphabetical characters

In [17]:
df_scrape[df_scrape['Antibiotic'].str.contains(r'[^A-Za-z ]', na=False)]

,Antibiotic,England-adapted 2019 AWaRe category,UK-adapted 2024 AWaRe category
2,Amoxicillin/ clavulanic-acid,Watch,Watch
6,Benzathine-benzylpenicillin,Access,Access
20,Ceftaroline-fosamil,Reserve,Reserve
22,Ceftazidime/ avibactam,Reserve,Reserve
23,Ceftobiprole-medocaril,Reserve,Reserve
24,Ceftolozane/ tazobactam,Reserve,Reserve
31,"Colistin, intravenous",Reserve,Reserve
32,"Colistin, oral",Reserve,Reserve
34,Dalfopristin/ quinupristin,Reserve,Reserve
46,"Fosfomycin, intravenous",Reserve,Reserve
49,Imipenem/cilastatin,Reserve,Reserve
50,Imipenem/cilastatin/relebactam,Reserve,Reserve
55,Meropenem/ vaborbactam,Reserve,Reserve
69,Piperacillin/tazobactam,Watch,Watch
72,Procaine-benzylpenicillin,Access,Access
75,"Streptomycin, intravenous",Other,Other
77,Sulfamethoxazole/ trimethoprim,Access,Access

Some rows specify a route. Sometimes there is a comma between antibiotic and route, sometimes there isn't. We can pull any specified route into a seperate column.

In [18]:
# List of routes to check.
route_list = ["oral", "intravenous"]

# Function to extract the route if the Antibiotic entry ends with a route.
def extract_route(antibiotic):
    for route in route_list:
        if antibiotic.endswith(" " + route):
            return route
    return ""  # Return empty string if no route is found.

# Apply the function to create a new 'Route' column.
df_scrape['Route_specific'] = df_scrape['Antibiotic'].apply(extract_route)

# Remove any route names from the 'Antibiotic' column only if they appear at the end
# and are preceded by either ", " or " ".
for route in route_list:
    df_scrape['Antibiotic'] = df_scrape['Antibiotic'].str.replace(fr'(, | ){route}$', '', regex=True)

# Define mapping
route_map = {'oral': 'O', 'intravenous': 'P'}

# Replace NaN with empty strings just to be safe
df_scrape['Route_specific'] = df_scrape['Route_specific'].fillna('')

# Map values using a dictionary, and fill any unmapped entries with empty string
df_scrape['ATC_Route_specific'] = df_scrape['Route_specific'].map(route_map).fillna('')

df_scrape

,Antibiotic,England-adapted 2019 AWaRe category,UK-adapted 2024 AWaRe category,Route_specific,ATC_Route_specific
0,Amikacin,Watch,Watch,,
1,Amoxicillin,Access,Access,,
2,Amoxicillin/ clavulanic-acid,Watch,Watch,,
3,Ampicillin,Access,Access,,
4,Azithromycin,Watch,Watch,,
...,...,...,...,...,...
85,Tigecycline,Reserve,Reserve,,
86,Tinidazole,Other,Access,,
87,Tobramycin,Watch,Watch,,
88,Trimethoprim,Access,Access,,
89,Vancomycin,Watch,Watch,,

In [19]:
df_scrape[df_scrape['Antibiotic'].str.contains(r'[^A-Za-z ]', na=False)]

,Antibiotic,England-adapted 2019 AWaRe category,UK-adapted 2024 AWaRe category,Route_specific,ATC_Route_specific
2,Amoxicillin/ clavulanic-acid,Watch,Watch,,
6,Benzathine-benzylpenicillin,Access,Access,,
20,Ceftaroline-fosamil,Reserve,Reserve,,
22,Ceftazidime/ avibactam,Reserve,Reserve,,
23,Ceftobiprole-medocaril,Reserve,Reserve,,
24,Ceftolozane/ tazobactam,Reserve,Reserve,,
34,Dalfopristin/ quinupristin,Reserve,Reserve,,
49,Imipenem/cilastatin,Reserve,Reserve,,
50,Imipenem/cilastatin/relebactam,Reserve,Reserve,,
55,Meropenem/ vaborbactam,Reserve,Reserve,,
69,Piperacillin/tazobactam,Watch,Watch,,
72,Procaine-benzylpenicillin,Access,Access,,
77,Sulfamethoxazole/ trimethoprim,Access,Access,,

Some of the formatting in the UKHSA is slightly inconsistent with the WHO format.
In WHO format there is no space after / for combo products. Remove these from UKHSA version.
In WHO format spaces between parts of antibiotic name are always a dash (-) replace spaces for dashes.

In [20]:
df_scrape['Antibiotic'] = df_scrape['Antibiotic'].str.replace('/ ', '/', regex=False)
df_scrape['Antibiotic'] = df_scrape['Antibiotic'].str.replace(' ', '-', regex=False)

In [23]:
with pd.option_context('display.max_rows', None):
    display(df_scrape)

,Antibiotic,England-adapted 2019 AWaRe category,UK-adapted 2024 AWaRe category,Route_specific,ATC_Route_specific
0,Amikacin,Watch,Watch,,
1,Amoxicillin,Access,Access,,
2,Amoxicillin/clavulanic-acid,Watch,Watch,,
3,Ampicillin,Access,Access,,
4,Azithromycin,Watch,Watch,,
5,Aztreonam,Reserve,Reserve,,
6,Benzathine-benzylpenicillin,Access,Access,,
7,Benzylpenicillin,Access,Access,,
8,Cefaclor,Watch,Watch,,
9,Cefadroxil,Watch,Access,,
10,Cefalexin,Watch,Access,,
11,Cefalotin,Watch,Access,,
12,Cefamandole,Watch,Watch,,
13,Cefazolin,Watch,Access,,
14,Cefepime,Watch,Watch,,
15,Cefiderocol,Reserve,Reserve,,
16,Cefixime,Watch,Watch,,
17,Cefotaxime,Watch,Watch,,
18,Cefoxitin,Watch,Watch,,
19,Cefradine,Watch,Access,,
20,Ceftaroline-fosamil,Reserve,Reserve,,
21,Ceftazidime,Watch,Watch,,
22,Ceftazidime/avibactam,Reserve,Reserve,,
23,Ceftobiprole-medocaril,Reserve,Reserve,,
24,Ceftolozane/tazobactam,Reserve,Reserve,,
25,Ceftriaxone,Watch,Watch,,
26,Cefuroxime,Watch,Watch,,
27,Chloramphenicol,Watch,Watch,,
28,Ciprofloxacin,Watch,Watch,,
29,Clarithromycin,Watch,Watch,,
30,Clindamycin,Watch,Watch,,
31,Colistin,Reserve,Reserve,intravenous,P
32,Colistin,Reserve,Reserve,oral,O
33,Dalbavancin,Reserve,Reserve,,
34,Dalfopristin/quinupristin,Reserve,Reserve,,
35,Daptomycin,Reserve,Reserve,,
36,Delafloxacin,Watch,Watch,,
37,Demeclocycline,Watch,Other,,
38,Doripenem,Reserve,Reserve,,
39,Doxycycline,Access,Access,,
40,Eravacycline,Reserve,Reserve,,
41,Ertapenem,Reserve,Reserve,,
42,Erythromycin,Watch,Watch,,
43,Fidaxomicin,Watch,Watch,,
44,Flucloxacillin,Access,Access,,
45,Fosfomycin,Access,Access,oral,O
46,Fosfomycin,Reserve,Reserve,intravenous,P
47,Fusidic-acid,Access,Watch,,
48,Gentamicin,Access,Access,,
49,Imipenem/cilastatin,Reserve,Reserve,,
50,Imipenem/cilastatin/relebactam,Reserve,Reserve,,
51,Levofloxacin,Watch,Watch,,
52,Linezolid,Reserve,Reserve,,
53,Lymecycline,Watch,Watch,,
54,Meropenem,Reserve,Reserve,,
55,Meropenem/vaborbactam,Reserve,Reserve,,
56,Methenamine,Other,Other,,
57,Metronidazole,Access,Access,,
58,Minocycline,Watch,Watch,oral,O
59,Moxifloxacin,Watch,Watch,,
60,Nalidixic-Acid,Other,Other,,
61,Neomycin,Watch,Watch,,
62,Nitrofurantoin,Access,Access,,
63,Norfloxacin,Watch,Watch,,
64,Ofloxacin,Watch,Watch,,
65,Oritavancin,Reserve,Reserve,,
66,Oxytetracycline,Watch,Watch,,
67,Phenoxymethylpenicillin,Access,Access,,
68,Piperacillin,Watch,Watch,,
69,Piperacillin/tazobactam,Watch,Watch,,
70,Pivmecillinam,Access,Access,,
71,Pristinamycin,Watch,Other,,
72,Procaine-benzylpenicillin,Access,Access,,
73,Spectinomycin,Other,Other,,
74,Spiramycin,Other,Other,,
75,Streptomycin,Other,Other,intravenous,P
76,Sulfadiazine,Other,Other,,
77,Sulfamethoxazole/trimethoprim,Access,Access,,
78,Sulfamethoxypyridazine,Other,Other,,
79,Sulfapyridine,Other,Other,,
80,Tedizolid,Reserve,Reserve,,
81,Teicoplanin,Watch,Watch,,
82,Telavancin,Reserve,Reserve,,
83,Temocillin,Watch,Watch,,
84,Tetracycline,Access,Access,,
85,Tigecycline,Reserve,Reserve,,
86,Tinidazole,Other,Access,,
87,Tobramycin,Watch,Watch,,
88,Trimethoprim,Access,Access,,
89,Vancomycin,Watch,Watch,,

## Cleaning up the WHO to ATC list

The WHO list also contains some routes within the names. Seperate this out.

In [21]:
# List of routes to check.
route_list = ["oral", "IV"]

# Function to extract the route if the Antibiotic entry ends with a route.
def extract_route(antibiotic):
    for route in route_list:
        if antibiotic.endswith("_" + route):
            return route
    return ""  # Return empty string if no route is found.

# Apply the function to create a new 'Route' column.
who_antibiotic_to_atc['Route_specific'] = who_antibiotic_to_atc['Antibiotic'].apply(extract_route)

# Remove any route names from the 'Antibiotic' column only if they appear at the end
# and are preceded by either ", " or " ".
for route in route_list:
    who_antibiotic_to_atc['Antibiotic'] = who_antibiotic_to_atc['Antibiotic'].str.replace(fr'(_| ){route}$', '', regex=True)

# Define mapping
route_map = {'oral': 'O', 'IV': 'P'}

# Replace NaN with empty strings just to be safe
who_antibiotic_to_atc['Route_specific'] = who_antibiotic_to_atc['Route_specific'].fillna('')

# Map values using a dictionary, and fill any unmapped entries with empty string
who_antibiotic_to_atc['ATC_Route_specific'] = who_antibiotic_to_atc['Route_specific'].map(route_map).fillna('')

,Antibiotic,Class,ATC code,Route_specific,ATC_Route_specific
0,Amikacin,Aminoglycosides,J01GB06,,
1,Amoxicillin,Penicillins,J01CA04,,
2,Amoxicillin/clavulanic-acid,Beta-lactam/beta-lactamase-inhibitor,J01CR02,,
3,Ampicillin,Penicillins,J01CA01,,
4,Ampicillin/sulbactam,Beta-lactam/beta-lactamase-inhibitor,J01CR01,,
...,...,...,...,...,...
252,Trimethoprim,Trimethoprim-derivatives,J01EA01,,
253,Troleandomycin,Macrolides,J01FA08,,
254,Trovafloxacin,Fluoroquinolones,J01MA13,,
255,Vancomycin,Glycopeptides,J01XA01,IV,P
256,Vancomycin,Glycopeptides,A07AA09,oral,O

In [24]:
with pd.option_context('display.max_rows', None):
    display(who_antibiotic_to_atc)

,Antibiotic,Class,ATC code,Route_specific,ATC_Route_specific
0,Amikacin,Aminoglycosides,J01GB06,,
1,Amoxicillin,Penicillins,J01CA04,,
2,Amoxicillin/clavulanic-acid,Beta-lactam/beta-lactamase-inhibitor,J01CR02,,
3,Ampicillin,Penicillins,J01CA01,,
4,Ampicillin/sulbactam,Beta-lactam/beta-lactamase-inhibitor,J01CR01,,
5,Arbekacin,Aminoglycosides,J01GB12,,
6,Aspoxicillin,Penicillins,J01CA19,,
7,Azidocillin,Penicillins,J01CE04,,
8,Azithromycin,Macrolides,J01FA10,,
9,Azlocillin,Penicillins,J01CA09,,
10,Aztreonam,Monobactams,J01DF01,,
11,Bacampicillin,Penicillins,J01CA06,,
12,Bekanamycin,Aminoglycosides,J01GB13,,
13,Benzathine-benzylpenicillin,Penicillins,J01CE08,,
14,Benzylpenicillin,Penicillins,J01CE01,,
15,Biapenem,Carbapenems,J01DH05,,
16,Brodimoprim,Trimethoprim-derivatives,J01EA02,,
17,Carbenicillin,Penicillins,J01CA03,,
18,Carindacillin,Penicillins,J01CA05,,
19,Carumonam,Monobactams,J01DF02,,
20,Cefacetrile,First-generation-cephalosporins,J01DB10,,
21,Cefaclor,Second-generation-cephalosporins,J01DC04,,
22,Cefadroxil,First-generation-cephalosporins,J01DB05,,
23,Cefalexin,First-generation-cephalosporins,J01DB01,,
24,Cefaloridine,First-generation-cephalosporins,J01DB02,,
25,Cefalotin,First-generation-cephalosporins,J01DB03,,
26,Cefamandole,Second-generation-cephalosporins,J01DC03,,
27,Cefapirin,First-generation-cephalosporins,J01DB08,,
28,Cefatrizine,First-generation-cephalosporins,J01DB07,,
29,Cefazedone,First-generation-cephalosporins,J01DB06,,
30,Cefazolin,First-generation-cephalosporins,J01DB04,,
31,Cefbuperazone,Second-generation-cephalosporins,J01DC13,,
32,Cefcapene-pivoxil,Third-generation-cephalosporins,J01DD17,,
33,Cefdinir,Third-generation-cephalosporins,J01DD15,,
34,Cefditoren-pivoxil,Third-generation-cephalosporins,J01DD16,,
35,Cefepime,Fourth-generation-cephalosporins,J01DE01,,
36,Cefetamet-pivoxil,Third-generation-cephalosporins,J01DD10,,
37,Cefiderocol,Other-cephalosporins,J01DI04,,
38,Cefixime,Third-generation-cephalosporins,J01DD08,,
39,Cefmenoxime,Third-generation-cephalosporins,J01DD05,,
40,Cefmetazole,Second-generation-cephalosporins,J01DC09,,
41,Cefminox,Second-generation-cephalosporins,J01DC12,,
42,Cefodizime,Third-generation-cephalosporins,J01DD09,,
43,Cefonicid,Second-generation-cephalosporins,J01DC06,,
44,Cefoperazone,Third-generation-cephalosporins,J01DD12,,
45,Ceforanide,Second-generation-cephalosporins,J01DC11,,
46,Cefoselis,Fourth-generation-cephalosporins,to be assigned,,
47,Cefotaxime,Third-generation-cephalosporins,J01DD01,,
48,Cefotetan,Second-generation-cephalosporins,J01DC05,,
49,Cefotiam,Second-generation-cephalosporins,J01DC07,,
50,Cefoxitin,Second-generation-cephalosporins,J01DC01,,
51,Cefozopran,Fourth-generation-cephalosporins,J01DE03,,
52,Cefpiramide,Third-generation-cephalosporins,J01DD11,,
53,Cefpirome,Fourth-generation-cephalosporins,J01DE02,,
54,Cefpodoxime-proxetil,Third-generation-cephalosporins,J01DD13,,
55,Cefprozil,Second-generation-cephalosporins,J01DC10,,
56,Cefradine,First-generation-cephalosporins,J01DB09,,
57,Cefroxadine,First-generation-cephalosporins,J01DB11,,
58,Cefsulodin,Third-generation-cephalosporins,J01DD03,,
59,Ceftaroline-fosamil,Fifth-generation cephalosporins,J01DI02,,
60,Ceftazidime,Third-generation-cephalosporins,J01DD02,,
61,Ceftazidime/avibactam,Third-generation-cephalosporins,J01DD52,,
62,Cefteram-pivoxil,Third-generation-cephalosporins,J01DD18,,
63,Ceftezole,First-generation-cephalosporins,J01DB12,,
64,Ceftibuten,Third-generation-cephalosporins,J01DD14,,
65,Ceftizoxime,Third-generation-cephalosporins,J01DD07,,
66,Ceftobiprole-medocaril,Fifth-generation cephalosporins,J01DI01,,
67,Ceftolozane/tazobactam,Fifth-generation cephalosporins,J01DI54,,
68,Ceftriaxone,Third-generation-cephalosporins,J01DD04,,
69,Cefuroxime,Second-generation-cephalosporins,J01DC02,,
70,Chloramphenicol,Amphenicols,J01BA01,,
71,Chlortetracycline,Tetracyclines,J01AA03,,
72,Cinoxacin,Quinolones,J01MB06,,
73,Ciprofloxacin,Fluoroquinolones,J01MA02,,
74,Clarithromycin,Macrolides,J01FA09,,
75,Clindamycin,Lincosamides,J01FF01,,
76,Clofoctol,Phenol derivatives,J01XX03,,
77,Clometocillin,Penicillins,J01CE07,,
78,Clomocycline,Tetracyclines,J01AA11,,
79,Cloxacillin,Penicillins,J01CF02,,
80,Colistin,Polymyxins,J01XB01,IV,P
81,Colistin,Polymyxins,A07AA10,oral,O
82,Dalbavancin,Glycopeptides,J01XA04,,
83,Dalfopristin/quinupristin,Streptogramins,J01FG02,,
84,Daptomycin,Lipopeptides,J01XX09,,
85,Delafloxacin,Fluoroquinolones,J01MA23,,
86,Demeclocycline,Tetracyclines,J01AA01,,
87,Dibekacin,Aminoglycosides,J01GB09,,
88,Dicloxacillin,Penicillins,J01CF01,,
89,Dirithromycin,Macrolides,J01FA13,,
90,Doripenem,Carbapenems,J01DH04,,
91,Doxycycline,Tetracyclines,J01AA02,,
92,Enoxacin,Fluoroquinolones,J01MA04,,
93,Epicillin,Penicillins,J01CA07,,
94,Eravacycline,Tetracyclines,J01AA13,,
95,Ertapenem,Carbapenems,J01DH03,,
96,Erythromycin,Macrolides,J01FA01,,
97,Faropenem,Penems,J01DI03,,
98,Fidaxomicin,Macrolides,A07AA12,,
99,Fleroxacin,Fluoroquinolones,J01MA08,,
100,Flomoxef,Second-generation-cephalosporins,J01DC14,,
101,Flucloxacillin,Penicillins,J01CF05,,
102,Flumequine,Quinolones,J01MB07,,
103,Flurithromycin,Macrolides,J01FA14,,
104,Fosfomycin,Phosphonics,J01XX01,IV,P
105,Fosfomycin,Phosphonics,J01XX01,oral,O
106,Furazidin,Nitrofuran derivatives,J01XE03,,
107,Fusidic-acid,Steroid antibacterials,J01XC01,,
108,Garenoxacin,Fluoroquinolones,J01MA19,,
109,Gatifloxacin,Fluoroquinolones,J01MA16,,
110,Gemifloxacin,Fluoroquinolones,J01MA15,,
111,Gentamicin,Aminoglycosides,J01GB03,,
112,Grepafloxacin,Fluoroquinolones,J01MA11,,
113,Hetacillin,Penicillins,J01CA18,,
114,Iclaprim,Trimethoprim-derivatives,J01EA03,,
115,Imipenem/cilastatin,Carbapenems,J01DH51,,
116,Imipenem/cilastatin/relebactam,Carbapenems,J01DH56,,
117,Isepamicin,Aminoglycosides,J01GB11,,
118,Josamycin,Macrolides,J01FA07,,
119,Kanamycin,Aminoglycosides,J01GB04,IV,P
120,Kanamycin,Aminoglycosides,A07AA08,oral,O
121,Lascufloxacin,Fluoroquinolones,J01MA25,,
122,Latamoxef,Third-generation-cephalosporins,J01DD06,,
123,Lefamulin,Pleuromutilin,J01XX12,,
124,Levofloxacin,Fluoroquinolones,J01MA12,,
125,Levonadifloxacin,Fluoroquinolones,J01MA24,,
126,Lincomycin,Lincosamides,J01FF02,,
127,Linezolid,Oxazolidinones,J01XX08,,
128,Lomefloxacin,Fluoroquinolones,J01MA07,,
129,Loracarbef,Second-generation-cephalosporins,J01DC08,,
130,Lymecycline,Tetracyclines,J01AA04,,
131,Mecillinam,Penicillins,J01CA11,,
132,Meropenem,Carbapenems,J01DH02,,
133,Meropenem/vaborbactam,Carbapenems,J01DH52,,
134,Metacycline,Tetracyclines,J01AA05,,
135,Metampicillin,Penicillins,J01CA14,,
136,Meticillin,Penicillins,J01CF03,,
137,Metronidazole,Imidazoles,J01XD01,IV,P
138,Metronidazole,Imidazoles,P01AB01,oral,O
139,Mezlocillin,Penicillins,J01CA10,,
140,Micronomicin,Aminoglycosides,to be assigned,,
141,Midecamycin,Macrolides,J01FA03,,
142,Minocycline,Tetracyclines,J01AA08,IV,P
143,Minocycline,Tetracyclines,J01AA08,oral,O
144,Miocamycin,Macrolides,J01FA11,,
145,Moxifloxacin,Fluoroquinolones,J01MA14,,
146,Nafcillin,Penicillins,J01CF06,,
147,Nemonoxacin,Quinolones,J01MB08,,
148,Neomycin,Aminoglycosides,J01GB05,IV,P
149,Neomycin,Aminoglycosides,A07AA01,oral,O
150,Netilmicin,Aminoglycosides,J01GB07,,
151,Nifurtoinol,Nitrofuran derivatives,J01XE02,,
152,Nitrofurantoin,Nitrofuran-derivatives,J01XE01,,
153,Norfloxacin,Fluoroquinolones,J01MA06,,
154,Ofloxacin,Fluoroquinolones,J01MA01,,
155,Oleandomycin,Macrolides,J01FA05,,
156,Omadacycline,Tetracyclines,J01AA15,,
157,Oritavancin,Glycopeptides,J01XA05,,
158,Ornidazole,Imidazoles,J01XD03,IV,P
159,Ornidazole,Imidazoles,P01AB03,oral,O
160,Oxacillin,Penicillins,J01CF04,,
161,Oxolinic-acid,Quinolones,J01MB05,,
162,Oxytetracycline,Tetracyclines,J01AA06,,
163,Panipenem,Carbapenems,J01DH55,,
164,Pazufloxacin,Fluoroquinolones,J01MA18,,
165,Pefloxacin,Fluoroquinolones,J01MA03,,
166,Penamecillin,Penicillins,J01CE06,,
167,Penimepicycline,Tetracyclines,J01AA10,,
168,Pheneticillin,Penicillins,J01CE05,,
169,Phenoxymethylpenicillin,Penicillins,J01CE02,,
170,Pipemidic-acid,Quinolones,J01MB04,,
171,Piperacillin,Penicillins,J01CA12,,
172,Piperacillin/tazobactam,Beta-lactam/beta-lactamase-inhibitor_anti-pseu...,J01CR05,,
173,Piromidic-acid,Quinolones,J01MB03,,
174,Pivampicillin,Penicillins,J01CA02,,
175,Pivmecillinam,Penicillins,J01CA08,,
176,Plazomicin,Aminoglycosides,J01GB14,,
177,Polymyxin-B,Polymyxins,J01XB02,IV,P
178,Polymyxin-B,Polymyxins,A07AA05,oral,O
179,Pristinamycin,Streptogramins,J01FG01,,
180,Procaine-benzylpenicillin,Penicillins,J01CE09,,
181,Propicillin,Penicillins,J01CE03,,
182,Prulifloxacin,Fluoroquinolones,J01MA17,,
183,Ribostamycin,Aminoglycosides,J01GB10,,
184,Rifabutin,Rifamycins,J04AB04,,
185,Rifampicin,Rifamycins,J04AB02,,
186,Rifamycin,Rifamycins,J04AB03,IV,P
187,Rifamycin,Rifamycins,A07AA13,oral,O
188,Rifaximin,Rifamycins,A07AA11,,
189,Rokitamycin,Macrolides,J01FA12,,
190,Rolitetracycline,Tetracyclines,J01AA09,,
191,Rosoxacin,Quinolones,J01MB01,,
192,Roxithromycin,Macrolides,J01FA06,,
193,Rufloxacin,Fluoroquinolones,J01MA10,,
194,Sarecycline,Tetracyclines,J01AA14,,
195,Secnidazole,Imidazoles,P01AB07,,
196,Sisomicin,Aminoglycosides,J01GB08,,
197,Sitafloxacin,Fluoroquinolones,J01MA21,,
198,Solithromycin,Macrolides,J01FA16,,
199,Sparfloxacin,Fluoroquinolones,J01MA09,,
200,Spectinomycin,Aminocyclitols,J01XX04,,
201,Spiramycin,Macrolides,J01FA02,,
202,Streptoduocin,Aminoglycosides,J01GA02,,
203,Streptomycin,Aminoglycosides,J01GA01,IV,P
204,Streptomycin,Aminoglycosides,A07AA04,oral,O
205,Sulbactam,Beta-lactamase-inhibitors,J01CG01,,
206,Sulbenicillin,Penicillins,J01CA16,,
207,Sulfadiazine,Sulfonamides,J01EC02,,
208,Sulfadiazine/tetroxoprim,Sulfonamide-trimethoprim-combinations,J01EE06,,
209,Sulfadiazine/trimethoprim,Sulfonamide-trimethoprim-combinations,J01EE02,,
210,Sulfadimethoxine,Sulfonamides,J01ED01,,
211,Sulfadimidine,Sulfonamides,J01EB03,,
212,Sulfadimidine/trimethoprim,Sulfonamide-trimethoprim-combinations,J01EE05,,
213,Sulfafurazole,Sulfonamides,J01EB05,,
214,Sulfaisodimidine,Sulfonamides,J01EB01,,
215,Sulfalene,Sulfonamides,J01ED02,,
216,Sulfamazone,Sulfonamides,J01ED09,,
217,Sulfamerazine,Sulfonamides,J01ED07,,
218,Sulfamerazine/trimethoprim,Sulfonamide-trimethoprim-combinations,J01EE07,,
219,Sulfamethizole,Sulfonamides,J01EB02,,
220,Sulfamethoxazole,Sulfonamides,J01EC01,,
221,Sulfamethoxazole/trimethoprim,Sulfonamide-trimethoprim-combinations,J01EE01,,
222,Sulfamethoxypyridazine,Sulfonamides,J01ED05,,
223,Sulfametomidine,Sulfonamides,J01ED03,,
224,Sulfametoxydiazine,Sulfonamides,J01ED04,,
225,Sulfametrole/trimethoprim,Sulfonamide-trimethoprim-combinations,J01EE03,,
226,Sulfamoxole,Sulfonamides,J01EC03,,
227,Sulfamoxole/trimethoprim,Sulfonamide-trimethoprim-combinations,J01EE04,,
228,Sulfanilamide,Sulfonamides,J01EB06,,
229,Sulfaperin,Sulfonamides,J01ED06,,
230,Sulfaphenazole,Sulfonamides,J01ED08,,
231,Sulfapyridine,Sulfonamides,J01EB04,,
232,Sulfathiazole,Sulfonamides,J01EB07,,
233,Sulfathiourea,Sulfonamides,J01EB08,,
234,Sultamicillin,Beta-lactam/beta-lactamase-inhibitor,J01CR04,,
235,Talampicillin,Penicillins,J01CA15,,
236,Tazobactam,Beta-lactamase-inhibitors,J01CG02,,
237,Tebipenem,Carbapenems,J01DH06,,
238,Tedizolid,Oxazolidinones,J01XX11,,
239,Teicoplanin,Glycopeptides,J01XA02,,
240,Telavancin,Glycopeptides,J01XA03,,
241,Telithromycin,Macrolides,J01FA15,,
242,Temafloxacin,Fluoroquinolones,J01MA05,,
243,Temocillin,Penicillins,J01CA17,,
244,Tetracycline,Tetracyclines,J01AA07,,
245,Thiamphenicol,Amphenicols,J01BA02,,
246,Ticarcillin,Penicillins,J01CA13,,
247,Tigecycline,Glycylcyclines,J01AA12,,
248,Tinidazole,Imidazoles,J01XD02,IV,P
249,Tinidazole,Imidazoles,P01AB02,oral,O
250,Tobramycin,Aminoglycosides,J01GB01,,
251,Tosufloxacin,Fluoroquinolones,J01MA22,,
252,Trimethoprim,Trimethoprim-derivatives,J01EA01,,
253,Troleandomycin,Macrolides,J01FA08,,
254,Trovafloxacin,Fluoroquinolones,J01MA13,,
255,Vancomycin,Glycopeptides,J01XA01,IV,P
256,Vancomycin,Glycopeptides,A07AA09,oral,O

## Adding ATC codes to UKHSA list

We can merge the ATC codes from WHO file with the Antibiotic list published by the UKHSA.

In [25]:
ukhsa_list_with_atc = df_scrape.merge(
    who_antibiotic_to_atc,
    how='left',
    left_on=['Antibiotic', 'ATC_Route_specific'],
    right_on=['Antibiotic', 'ATC_Route_specific']
)

with pd.option_context('display.max_rows', None):
    display(ukhsa_list_with_atc)

,Antibiotic,England-adapted 2019 AWaRe category,UK-adapted 2024 AWaRe category,Route_specific_x,ATC_Route_specific,Class,ATC code,Route_specific_y
0,Amikacin,Watch,Watch,,,Aminoglycosides,J01GB06,
1,Amoxicillin,Access,Access,,,Penicillins,J01CA04,
2,Amoxicillin/clavulanic-acid,Watch,Watch,,,Beta-lactam/beta-lactamase-inhibitor,J01CR02,
3,Ampicillin,Access,Access,,,Penicillins,J01CA01,
4,Azithromycin,Watch,Watch,,,Macrolides,J01FA10,
5,Aztreonam,Reserve,Reserve,,,Monobactams,J01DF01,
6,Benzathine-benzylpenicillin,Access,Access,,,Penicillins,J01CE08,
7,Benzylpenicillin,Access,Access,,,Penicillins,J01CE01,
8,Cefaclor,Watch,Watch,,,Second-generation-cephalosporins,J01DC04,
9,Cefadroxil,Watch,Access,,,First-generation-cephalosporins,J01DB05,
10,Cefalexin,Watch,Access,,,First-generation-cephalosporins,J01DB01,
11,Cefalotin,Watch,Access,,,First-generation-cephalosporins,J01DB03,
12,Cefamandole,Watch,Watch,,,Second-generation-cephalosporins,J01DC03,
13,Cefazolin,Watch,Access,,,First-generation-cephalosporins,J01DB04,
14,Cefepime,Watch,Watch,,,Fourth-generation-cephalosporins,J01DE01,
15,Cefiderocol,Reserve,Reserve,,,Other-cephalosporins,J01DI04,
16,Cefixime,Watch,Watch,,,Third-generation-cephalosporins,J01DD08,
17,Cefotaxime,Watch,Watch,,,Third-generation-cephalosporins,J01DD01,
18,Cefoxitin,Watch,Watch,,,Second-generation-cephalosporins,J01DC01,
19,Cefradine,Watch,Access,,,First-generation-cephalosporins,J01DB09,
20,Ceftaroline-fosamil,Reserve,Reserve,,,Fifth-generation cephalosporins,J01DI02,
21,Ceftazidime,Watch,Watch,,,Third-generation-cephalosporins,J01DD02,
22,Ceftazidime/avibactam,Reserve,Reserve,,,Third-generation-cephalosporins,J01DD52,
23,Ceftobiprole-medocaril,Reserve,Reserve,,,Fifth-generation cephalosporins,J01DI01,
24,Ceftolozane/tazobactam,Reserve,Reserve,,,Fifth-generation cephalosporins,J01DI54,
25,Ceftriaxone,Watch,Watch,,,Third-generation-cephalosporins,J01DD04,
26,Cefuroxime,Watch,Watch,,,Second-generation-cephalosporins,J01DC02,
27,Chloramphenicol,Watch,Watch,,,Amphenicols,J01BA01,
28,Ciprofloxacin,Watch,Watch,,,Fluoroquinolones,J01MA02,
29,Clarithromycin,Watch,Watch,,,Macrolides,J01FA09,
30,Clindamycin,Watch,Watch,,,Lincosamides,J01FF01,
31,Colistin,Reserve,Reserve,intravenous,P,Polymyxins,J01XB01,IV
32,Colistin,Reserve,Reserve,oral,O,Polymyxins,A07AA10,oral
33,Dalbavancin,Reserve,Reserve,,,Glycopeptides,J01XA04,
34,Dalfopristin/quinupristin,Reserve,Reserve,,,Streptogramins,J01FG02,
35,Daptomycin,Reserve,Reserve,,,Lipopeptides,J01XX09,
36,Delafloxacin,Watch,Watch,,,Fluoroquinolones,J01MA23,
37,Demeclocycline,Watch,Other,,,Tetracyclines,J01AA01,
38,Doripenem,Reserve,Reserve,,,Carbapenems,J01DH04,
39,Doxycycline,Access,Access,,,Tetracyclines,J01AA02,
40,Eravacycline,Reserve,Reserve,,,Tetracyclines,J01AA13,
41,Ertapenem,Reserve,Reserve,,,Carbapenems,J01DH03,
42,Erythromycin,Watch,Watch,,,Macrolides,J01FA01,
43,Fidaxomicin,Watch,Watch,,,Macrolides,A07AA12,
44,Flucloxacillin,Access,Access,,,Penicillins,J01CF05,
45,Fosfomycin,Access,Access,oral,O,Phosphonics,J01XX01,oral
46,Fosfomycin,Reserve,Reserve,intravenous,P,Phosphonics,J01XX01,IV
47,Fusidic-acid,Access,Watch,,,Steroid antibacterials,J01XC01,
48,Gentamicin,Access,Access,,,Aminoglycosides,J01GB03,
49,Imipenem/cilastatin,Reserve,Reserve,,,Carbapenems,J01DH51,
50,Imipenem/cilastatin/relebactam,Reserve,Reserve,,,Carbapenems,J01DH56,
51,Levofloxacin,Watch,Watch,,,Fluoroquinolones,J01MA12,
52,Linezolid,Reserve,Reserve,,,Oxazolidinones,J01XX08,
53,Lymecycline,Watch,Watch,,,Tetracyclines,J01AA04,
54,Meropenem,Reserve,Reserve,,,Carbapenems,J01DH02,
55,Meropenem/vaborbactam,Reserve,Reserve,,,Carbapenems,J01DH52,
56,Methenamine,Other,Other,,,NaN,NaN,NaN
57,Metronidazole,Access,Access,,,NaN,NaN,NaN
58,Minocycline,Watch,Watch,oral,O,Tetracyclines,J01AA08,oral
59,Moxifloxacin,Watch,Watch,,,Fluoroquinolones,J01MA14,
60,Nalidixic-Acid,Other,Other,,,NaN,NaN,NaN
61,Neomycin,Watch,Watch,,,NaN,NaN,NaN
62,Nitrofurantoin,Access,Access,,,Nitrofuran-derivatives,J01XE01,
63,Norfloxacin,Watch,Watch,,,Fluoroquinolones,J01MA06,
64,Ofloxacin,Watch,Watch,,,Fluoroquinolones,J01MA01,
65,Oritavancin,Reserve,Reserve,,,Glycopeptides,J01XA05,
66,Oxytetracycline,Watch,Watch,,,Tetracyclines,J01AA06,
67,Phenoxymethylpenicillin,Access,Access,,,Penicillins,J01CE02,
68,Piperacillin,Watch,Watch,,,Penicillins,J01CA12,
69,Piperacillin/tazobactam,Watch,Watch,,,Beta-lactam/beta-lactamase-inhibitor_anti-pseu...,J01CR05,
70,Pivmecillinam,Access,Access,,,Penicillins,J01CA08,
71,Pristinamycin,Watch,Other,,,Streptogramins,J01FG01,
72,Procaine-benzylpenicillin,Access,Access,,,Penicillins,J01CE09,
73,Spectinomycin,Other,Other,,,Aminocyclitols,J01XX04,
74,Spiramycin,Other,Other,,,Macrolides,J01FA02,
75,Streptomycin,Other,Other,intravenous,P,Aminoglycosides,J01GA01,IV
76,Sulfadiazine,Other,Other,,,NaN,NaN,NaN
77,Sulfamethoxazole/trimethoprim,Access,Access,,,Sulfonamide-trimethoprim-combinations,J01EE01,
78,Sulfamethoxypyridazine,Other,Other,,,Sulfonamides,J01ED05,
79,Sulfapyridine,Other,Other,,,Sulfonamides,J01EB04,
80,Tedizolid,Reserve,Reserve,,,Oxazolidinones,J01XX11,
81,Teicoplanin,Watch,Watch,,,Glycopeptides,J01XA02,
82,Telavancin,Reserve,Reserve,,,Glycopeptides,J01XA03,
83,Temocillin,Watch,Watch,,,Penicillins,J01CA17,
84,Tetracycline,Access,Access,,,Tetracyclines,J01AA07,
85,Tigecycline,Reserve,Reserve,,,Glycylcyclines,J01AA12,
86,Tinidazole,Other,Access,,,NaN,NaN,NaN
87,Tobramycin,Watch,Watch,,,Aminoglycosides,J01GB01,
88,Trimethoprim,Access,Access,,,Trimethoprim-derivatives,J01EA01,
89,Vancomycin,Watch,Watch,,,NaN,NaN,NaN

Some are missing matches - where there is a single obvious ATC code match we can add in the appropriate code.

In [27]:
ukhsa_list_with_atc.loc[ukhsa_list_with_atc['Antibiotic'] == 'Methenamine', ['Class', 'ATC code']] = ['Triazinanes', 'J01XX05']
ukhsa_list_with_atc.loc[ukhsa_list_with_atc['Antibiotic'] == 'Nalidixic-Acid', ['Class', 'ATC code']] = ['Quinolone', 'J01MB02']
ukhsa_list_with_atc.loc[ukhsa_list_with_atc['Antibiotic'] == 'Sulfadiazine', ['Class', 'ATC code']] = ['Sulfonamides', 'J01EC02']

Some match to multiple ATC codes (different for oral and IV) - we can add in new rows for this and remove the unmatched rows.

In [29]:
manual_entries = [
    {
        "Antibiotic": "Metronidazole",
        "England-adapted 2019 AWaRe category": "Access",
        "UK-adapted 2024 AWaRe category": "Access",
        "Route_specific_x": "oral",
        "ATC_Route_specific": "O",
        "Class": "Imidazoles",
        "ATC code": "P01AB01",
        "Route_specific_y": "oral"
    },
    {
        "Antibiotic": "Metronidazole",
        "England-adapted 2019 AWaRe category": "Access",
        "UK-adapted 2024 AWaRe category": "Access",
        "Route_specific_x": "intravenous",
        "ATC_Route_specific": "P",
        "Class": "Imidazoles",
        "ATC code": "J01XD01",
        "Route_specific_y": "IV"
    },
    {
        "Antibiotic": "Tinidazole",
        "England-adapted 2019 AWaRe category": "Other",
        "UK-adapted 2024 AWaRe category": "Access",
        "Route_specific_x": "oral",
        "ATC_Route_specific": "O",
        "Class": "Imidazoles",
        "ATC code": "P01AB02",
        "Route_specific_y": "oral"
    },
    {
        "Antibiotic": "Tinidazole",
        "England-adapted 2019 AWaRe category": "Other",
        "UK-adapted 2024 AWaRe category": "Access",
        "Route_specific_x": "intravenous",
        "ATC_Route_specific": "P",
        "Class": "Imidazoles",
        "ATC code": "J01XD02",
        "Route_specific_y": "IV"
    },
    {
        "Antibiotic": "Vancomycin",
        "England-adapted 2019 AWaRe category": "Watch",
        "UK-adapted 2024 AWaRe category": "Watch",
        "Route_specific_x": "oral",
        "ATC_Route_specific": "O",
        "Class": "Imidazoles",
        "ATC code": "A07AA09",
        "Route_specific_y": "oral"
    },
    {
        "Antibiotic": "Vancomycin",
        "England-adapted 2019 AWaRe category": "Watch",
        "UK-adapted 2024 AWaRe category": "Watch",
        "Route_specific_x": "intravenous",
        "ATC_Route_specific": "P",
        "Class": "Imidazoles",
        "ATC code": "J01XA01",
        "Route_specific_y": "IV"
    },
    {
        "Antibiotic": "Neomycin",
        "England-adapted 2019 AWaRe category": "Watch",
        "UK-adapted 2024 AWaRe category": "Watch",
        "Route_specific_x": "oral",
        "ATC_Route_specific": "O",
        "Class": "Imidazoles",
        "ATC code": "A07AA01",
        "Route_specific_y": "oral"
    },
    {
        "Antibiotic": "Neomycin",
        "England-adapted 2019 AWaRe category": "Watch",
        "UK-adapted 2024 AWaRe category": "Watch",
        "Route_specific_x": "intravenous",
        "ATC_Route_specific": "P",
        "Class": "Imidazoles",
        "ATC code": "J01GB05",
        "Route_specific_y": "IV"
    },
]

In [30]:
manual_df = pd.DataFrame(manual_entries)

# Remove existing rows where Antibiotic is one of those in the manual entries
ukhsa_cleaned = ukhsa_list_with_atc[~ukhsa_list_with_atc['Antibiotic'].isin(manual_df['Antibiotic'])]

# Append the cleaned manual rows
ukhsa_final = pd.concat([ukhsa_cleaned, manual_df], ignore_index=True)

Reorder the columns and rename to simplify

In [34]:
ukhsa_final = ukhsa_final[['Antibiotic', 'Route_specific_x', 'Class', 'ATC code', 'England-adapted 2019 AWaRe category', 'UK-adapted 2024 AWaRe category']]

ukhsa_final.rename(columns={'England-adapted 2019 AWaRe category': 'aware_2019'}, inplace=True)
ukhsa_final.rename(columns={'UK-adapted 2024 AWaRe category': 'aware_2024'}, inplace=True)
ukhsa_final.rename(columns={'Route_specific_x': 'route'}, inplace=True)
ukhsa_final.rename(columns={'ATC code': 'ATC code'}, inplace=True)

with pd.option_context('display.max_rows', None):
    display(ukhsa_final)

,Antibiotic,route,Class,ATC code,aware_2019,aware_2024
0,Amikacin,,Aminoglycosides,J01GB06,Watch,Watch
1,Amoxicillin,,Penicillins,J01CA04,Access,Access
2,Amoxicillin/clavulanic-acid,,Beta-lactam/beta-lactamase-inhibitor,J01CR02,Watch,Watch
3,Ampicillin,,Penicillins,J01CA01,Access,Access
4,Azithromycin,,Macrolides,J01FA10,Watch,Watch
5,Aztreonam,,Monobactams,J01DF01,Reserve,Reserve
6,Benzathine-benzylpenicillin,,Penicillins,J01CE08,Access,Access
7,Benzylpenicillin,,Penicillins,J01CE01,Access,Access
8,Cefaclor,,Second-generation-cephalosporins,J01DC04,Watch,Watch
9,Cefadroxil,,First-generation-cephalosporins,J01DB05,Watch,Access
10,Cefalexin,,First-generation-cephalosporins,J01DB01,Watch,Access
11,Cefalotin,,First-generation-cephalosporins,J01DB03,Watch,Access
12,Cefamandole,,Second-generation-cephalosporins,J01DC03,Watch,Watch
13,Cefazolin,,First-generation-cephalosporins,J01DB04,Watch,Access
14,Cefepime,,Fourth-generation-cephalosporins,J01DE01,Watch,Watch
15,Cefiderocol,,Other-cephalosporins,J01DI04,Reserve,Reserve
16,Cefixime,,Third-generation-cephalosporins,J01DD08,Watch,Watch
17,Cefotaxime,,Third-generation-cephalosporins,J01DD01,Watch,Watch
18,Cefoxitin,,Second-generation-cephalosporins,J01DC01,Watch,Watch
19,Cefradine,,First-generation-cephalosporins,J01DB09,Watch,Access
20,Ceftaroline-fosamil,,Fifth-generation cephalosporins,J01DI02,Reserve,Reserve
21,Ceftazidime,,Third-generation-cephalosporins,J01DD02,Watch,Watch
22,Ceftazidime/avibactam,,Third-generation-cephalosporins,J01DD52,Reserve,Reserve
23,Ceftobiprole-medocaril,,Fifth-generation cephalosporins,J01DI01,Reserve,Reserve
24,Ceftolozane/tazobactam,,Fifth-generation cephalosporins,J01DI54,Reserve,Reserve
25,Ceftriaxone,,Third-generation-cephalosporins,J01DD04,Watch,Watch
26,Cefuroxime,,Second-generation-cephalosporins,J01DC02,Watch,Watch
27,Chloramphenicol,,Amphenicols,J01BA01,Watch,Watch
28,Ciprofloxacin,,Fluoroquinolones,J01MA02,Watch,Watch
29,Clarithromycin,,Macrolides,J01FA09,Watch,Watch
30,Clindamycin,,Lincosamides,J01FF01,Watch,Watch
31,Colistin,intravenous,Polymyxins,J01XB01,Reserve,Reserve
32,Colistin,oral,Polymyxins,A07AA10,Reserve,Reserve
33,Dalbavancin,,Glycopeptides,J01XA04,Reserve,Reserve
34,Dalfopristin/quinupristin,,Streptogramins,J01FG02,Reserve,Reserve
35,Daptomycin,,Lipopeptides,J01XX09,Reserve,Reserve
36,Delafloxacin,,Fluoroquinolones,J01MA23,Watch,Watch
37,Demeclocycline,,Tetracyclines,J01AA01,Watch,Other
38,Doripenem,,Carbapenems,J01DH04,Reserve,Reserve
39,Doxycycline,,Tetracyclines,J01AA02,Access,Access
40,Eravacycline,,Tetracyclines,J01AA13,Reserve,Reserve
41,Ertapenem,,Carbapenems,J01DH03,Reserve,Reserve
42,Erythromycin,,Macrolides,J01FA01,Watch,Watch
43,Fidaxomicin,,Macrolides,A07AA12,Watch,Watch
44,Flucloxacillin,,Penicillins,J01CF05,Access,Access
45,Fosfomycin,oral,Phosphonics,J01XX01,Access,Access
46,Fosfomycin,intravenous,Phosphonics,J01XX01,Reserve,Reserve
47,Fusidic-acid,,Steroid antibacterials,J01XC01,Access,Watch
48,Gentamicin,,Aminoglycosides,J01GB03,Access,Access
49,Imipenem/cilastatin,,Carbapenems,J01DH51,Reserve,Reserve
50,Imipenem/cilastatin/relebactam,,Carbapenems,J01DH56,Reserve,Reserve
51,Levofloxacin,,Fluoroquinolones,J01MA12,Watch,Watch
52,Linezolid,,Oxazolidinones,J01XX08,Reserve,Reserve
53,Lymecycline,,Tetracyclines,J01AA04,Watch,Watch
54,Meropenem,,Carbapenems,J01DH02,Reserve,Reserve
55,Meropenem/vaborbactam,,Carbapenems,J01DH52,Reserve,Reserve
56,Methenamine,,Triazinanes,J01XX05,Other,Other
57,Minocycline,oral,Tetracyclines,J01AA08,Watch,Watch
58,Moxifloxacin,,Fluoroquinolones,J01MA14,Watch,Watch
59,Nalidixic-Acid,,Quinolone,J01MB02,Other,Other
60,Nitrofurantoin,,Nitrofuran-derivatives,J01XE01,Access,Access
61,Norfloxacin,,Fluoroquinolones,J01MA06,Watch,Watch
62,Ofloxacin,,Fluoroquinolones,J01MA01,Watch,Watch
63,Oritavancin,,Glycopeptides,J01XA05,Reserve,Reserve
64,Oxytetracycline,,Tetracyclines,J01AA06,Watch,Watch
65,Phenoxymethylpenicillin,,Penicillins,J01CE02,Access,Access
66,Piperacillin,,Penicillins,J01CA12,Watch,Watch
67,Piperacillin/tazobactam,,Beta-lactam/beta-lactamase-inhibitor_anti-pseu...,J01CR05,Watch,Watch
68,Pivmecillinam,,Penicillins,J01CA08,Access,Access
69,Pristinamycin,,Streptogramins,J01FG01,Watch,Other
70,Procaine-benzylpenicillin,,Penicillins,J01CE09,Access,Access
71,Spectinomycin,,Aminocyclitols,J01XX04,Other,Other
72,Spiramycin,,Macrolides,J01FA02,Other,Other
73,Streptomycin,intravenous,Aminoglycosides,J01GA01,Other,Other
74,Sulfadiazine,,Sulfonamides,J01EC02,Other,Other
75,Sulfamethoxazole/trimethoprim,,Sulfonamide-trimethoprim-combinations,J01EE01,Access,Access
76,Sulfamethoxypyridazine,,Sulfonamides,J01ED05,Other,Other
77,Sulfapyridine,,Sulfonamides,J01EB04,Other,Other
78,Tedizolid,,Oxazolidinones,J01XX11,Reserve,Reserve
79,Teicoplanin,,Glycopeptides,J01XA02,Watch,Watch
80,Telavancin,,Glycopeptides,J01XA03,Reserve,Reserve
81,Temocillin,,Penicillins,J01CA17,Watch,Watch
82,Tetracycline,,Tetracyclines,J01AA07,Access,Access
83,Tigecycline,,Glycylcyclines,J01AA12,Reserve,Reserve
84,Tobramycin,,Aminoglycosides,J01GB01,Watch,Watch
85,Trimethoprim,,Trimethoprim-derivatives,J01EA01,Access,Access
86,Metronidazole,oral,Imidazoles,P01AB01,Access,Access
87,Metronidazole,intravenous,Imidazoles,J01XD01,Access,Access
88,Tinidazole,oral,Imidazoles,P01AB02,Other,Access
89,Tinidazole,intravenous,Imidazoles,J01XD02,Other,Access
90,Vancomycin,oral,Imidazoles,A07AA09,Watch,Watch
91,Vancomycin,intravenous,Imidazoles,J01XA01,Watch,Watch
92,Neomycin,oral,Imidazoles,A07AA01,Watch,Watch
93,Neomycin,intravenous,Imidazoles,J01GB05,Watch,Watch

In [35]:
ukhsa_final.to_csv("ukhsa_atc.csv", index=False)

## Matching VMPs

We can attempt to match Antibiotic names in the UKHSA to VTMs in dm+d