# AWaRe Data Integration and Mapping
AWaRe is a classification published by the WHO to categorise antibiotics into Access, Watch, Reserve and Other groups.

The ["UK Access, Watch, Reserve, and Other classification for antibiotics"](https://www.gov.uk/government/publications/uk-aware-antibiotic-classification/uk-access-watch-reserve-and-other-classification-for-antibiotics-uk-aware-antibiotic-classification) is a UK adapted version of this.

The existing list on the UKHSA site is not machine readable. To facilitate research, it is helpful to link this categorisation to the [dm+d standard](https://www.nhsbsa.nhs.uk/pharmacies-gp-practices-and-appliance-contractors/dictionary-medicines-and-devices-dmd).

This notebook details a process to:
- Generate a dm+d-compatible AWaRe list using SQL-based logic.
- Compare this against a supplied UKHSA Excel version.
- Analyse differences, identify discrepancies, and reconcile them.

The work is divided into two main sections:
1. [**Mapping AWaRe using dm+d and SQL**](#s1)
2. [**Analysing UKHSA Excel-supplied data**](#s2)
3. [**Comparing UKHSA Excel-supplied data**](#s3)
4. [**Refining AWaRe dm+d list/SQL**](#s4)
5. [**Summary**](#s5)

### Imports
We need to import some libaries to help with the code

In [1]:
import pandas as pd
import requests
from ebmdatalab import bq
import os

<a id='s1'></a>
## Section 1: Mapping AWaRe to dm+d
This section uses SQL logic with dm+d data to extract a list of relevant VTMs and associated VMPs and map them to their AWaRe classification.

### Getting the AWaRe list
The AWaRe list is currently available on the following webpage. We can read the html page directly into Pandas to retrieve the first table.

In [2]:
# Set URL to scrape
url = "https://www.gov.uk/government/publications/uk-aware-antibiotic-classification/uk-access-watch-reserve-and-other-classification-for-antibiotics-uk-aware-antibiotic-classification"

# Read the first HTML table from the page into a DataFrame using the HTML content
df_scrape = pd.read_html(url)[0]

# Display the DataFrame
df_scrape

,Antibiotic,England-adapted 2019 AWaRe category,UK-adapted 2024 AWaRe category
0,Amikacin,Watch,Watch
1,Amoxicillin,Access,Access
2,Amoxicillin/ clavulanic-acid,Watch,Watch
3,Ampicillin,Access,Access
4,Azithromycin,Watch,Watch
...,...,...,...
85,Tigecycline,Reserve,Reserve
86,Tinidazole #,Other,Access
87,Tobramycin,Watch,Watch
88,Trimethoprim,Access,Access
89,Vancomycin,Watch,Watch

### Cleaning up the list
The list contains some characters or identifiers that could break matching, we need to clean these up.

The # symbol is used to denote where category has changed, remove this

In [3]:
df_scrape['Antibiotic'] = df_scrape['Antibiotic'].str.replace(" #", "", regex=False)

We can review remaining rows that contain non-alphabetical characters

In [4]:
df_scrape[df_scrape['Antibiotic'].str.contains(r'[^A-Za-z ]', na=False)]

,Antibiotic,England-adapted 2019 AWaRe category,UK-adapted 2024 AWaRe category
2,Amoxicillin/ clavulanic-acid,Watch,Watch
6,Benzathine-benzylpenicillin,Access,Access
20,Ceftaroline-fosamil,Reserve,Reserve
22,Ceftazidime/ avibactam,Reserve,Reserve
23,Ceftobiprole-medocaril,Reserve,Reserve
24,Ceftolozane/ tazobactam,Reserve,Reserve
31,"Colistin, intravenous",Reserve,Reserve
32,"Colistin, oral",Reserve,Reserve
34,Dalfopristin/ quinupristin,Reserve,Reserve
46,"Fosfomycin, intravenous",Reserve,Reserve
49,Imipenem/cilastatin,Reserve,Reserve
50,Imipenem/cilastatin/relebactam,Reserve,Reserve
55,Meropenem/ vaborbactam,Reserve,Reserve
69,Piperacillin/tazobactam,Watch,Watch
72,Procaine-benzylpenicillin,Access,Access
75,"Streptomycin, intravenous",Other,Other
77,Sulfamethoxazole/ trimethoprim,Access,Access

Some rows specify a route. Sometimes there is a comma between antibiotic and route, sometimes there isn't. We can pull any specified route into a seperate column.

In [5]:
# List of routes to check.
route_list = ["oral", "intravenous"]

# Function to extract the route if the Antibiotic entry ends with a route.
def extract_route(antibiotic):
    for route in route_list:
        if antibiotic.endswith(" " + route):
            return route
    return ""  # Return empty string if no route is found.

# Apply the function to create a new 'Route' column.
df_scrape['Route_specific'] = df_scrape['Antibiotic'].apply(extract_route)

# Remove any route names from the 'Antibiotic' column only if they appear at the end
# and are preceded by either ", " or " ".
for route in route_list:
    df_scrape['Antibiotic'] = df_scrape['Antibiotic'].str.replace(fr'(, | ){route}$', '', regex=True)

In [6]:
df_scrape[df_scrape['Antibiotic'].str.contains(r'[^A-Za-z ]', na=False)]

,Antibiotic,England-adapted 2019 AWaRe category,UK-adapted 2024 AWaRe category,Route_specific
2,Amoxicillin/ clavulanic-acid,Watch,Watch,
6,Benzathine-benzylpenicillin,Access,Access,
20,Ceftaroline-fosamil,Reserve,Reserve,
22,Ceftazidime/ avibactam,Reserve,Reserve,
23,Ceftobiprole-medocaril,Reserve,Reserve,
24,Ceftolozane/ tazobactam,Reserve,Reserve,
34,Dalfopristin/ quinupristin,Reserve,Reserve,
49,Imipenem/cilastatin,Reserve,Reserve,
50,Imipenem/cilastatin/relebactam,Reserve,Reserve,
55,Meropenem/ vaborbactam,Reserve,Reserve,
69,Piperacillin/tazobactam,Watch,Watch,
72,Procaine-benzylpenicillin,Access,Access,
77,Sulfamethoxazole/ trimethoprim,Access,Access,

Some items contain a dash between words where as in dm+d there is a space. Replace the dash with a space to follow the common format.

In [7]:
df_scrape['Antibiotic'] = df_scrape['Antibiotic'].str.replace("-", " ", regex=False)

Some items contain a forward slash between words to indicate a combination where as in dm+d there is a + symbol. Replace the dash with a + ensuring appropriately spaced to follow the common dm+d format.

In [8]:
# Replace / with a + ensuring it is appropriately spaced and 2nd drug name is capitalised
df_scrape['Antibiotic'] = (
    df_scrape['Antibiotic']
    .str.replace(r'\s*/\s*', ' + ', regex=True)
    .str.replace(r'(\+\s+)(\w)', lambda m: m.group(1) + m.group(2).upper(), regex=True)
)
# Create a new column 'Combo' that is True if 'Antibiotic' contains a plus between two words.
df_scrape['Combo'] = df_scrape['Antibiotic'].str.contains(r'\b\w+\s*\+\s*\w+\b', regex=True)

In [9]:
df_scrape[df_scrape['Antibiotic'].str.contains(r'[^A-Za-z ]', na=False)]

,Antibiotic,England-adapted 2019 AWaRe category,UK-adapted 2024 AWaRe category,Route_specific,Combo
2,Amoxicillin + Clavulanic acid,Watch,Watch,,True
22,Ceftazidime + Avibactam,Reserve,Reserve,,True
24,Ceftolozane + Tazobactam,Reserve,Reserve,,True
34,Dalfopristin + Quinupristin,Reserve,Reserve,,True
49,Imipenem + Cilastatin,Reserve,Reserve,,True
50,Imipenem + Cilastatin + Relebactam,Reserve,Reserve,,True
55,Meropenem + Vaborbactam,Reserve,Reserve,,True
69,Piperacillin + Tazobactam,Watch,Watch,,True
77,Sulfamethoxazole + Trimethoprim,Access,Access,,True

Some antibiotic combinations are referred to as different names or in a different order in dm+d. These can be identified via dm+d manual search. We need to convert the strings to match those used in dm+d.

In [10]:
df_scrape['Antibiotic'] = df_scrape['Antibiotic'].str.replace("Amoxicillin + Clavulanic acid", "Co-amoxiclav", regex=False)
df_scrape['Antibiotic'] = df_scrape['Antibiotic'].str.replace("Sulfamethoxazole + Trimethoprim", "Co-trimoxazole", regex=False)
df_scrape['Antibiotic'] = df_scrape['Antibiotic'].str.replace("Dalfopristin + Quinupristin", "Quinupristin + Dalfopristin", regex=False)
df_scrape['Antibiotic'] = df_scrape['Antibiotic'].str.replace("Imipenem + Cilastatin + Relebactam", "Cilastatin + Imipenem + Relebactam", regex=False)
df_scrape['Antibiotic'] = df_scrape['Antibiotic'].str.replace("Ceftobiprole medocaril", "Ceftobiprole", regex=False)

Add a column 'ATC_Route_specific' mapping 'Route_specific' to ATC route.  
Ensure 'Route_specific' is a string by replacing NaN with an empty string.

In [11]:
# Define mapping
route_map = {'oral': 'O', 'intravenous': 'P'}

# Replace NaN with empty strings just to be safe
df_scrape['Route_specific'] = df_scrape['Route_specific'].fillna('')

# Map values using a dictionary, and fill any unmapped entries with empty string
df_scrape['ATC_Route_specific'] = df_scrape['Route_specific'].map(route_map).fillna('')

Reorder the columns and rename to simplify

In [12]:
df_scrape = df_scrape[['Antibiotic', 'Route_specific', 'ATC_Route_specific', 'Combo'] + [col for col in df_scrape.columns if col not in ['Antibiotic', 'Route_specific', 'ATC_Route_specific', 'Combo']]]

df_scrape.rename(columns={'England-adapted 2019 AWaRe category': 'aware_2019'}, inplace=True)
df_scrape.rename(columns={'UK-adapted 2024 AWaRe category': 'aware_2024'}, inplace=True)
df_scrape.rename(columns={'Route_specific': 'route'}, inplace=True)
df_scrape.rename(columns={'ATC_Route_specific': 'atc_route'}, inplace=True)

# Drop un-needed column
df_scrape.drop(columns='Combo', inplace=True)

In [13]:
df_prepared = df_scrape

with pd.option_context('display.max_rows', None):
    display(df_prepared)

,Antibiotic,route,atc_route,aware_2019,aware_2024
0,Amikacin,,,Watch,Watch
1,Amoxicillin,,,Access,Access
2,Co-amoxiclav,,,Watch,Watch
3,Ampicillin,,,Access,Access
4,Azithromycin,,,Watch,Watch
5,Aztreonam,,,Reserve,Reserve
6,Benzathine benzylpenicillin,,,Access,Access
7,Benzylpenicillin,,,Access,Access
8,Cefaclor,,,Watch,Watch
9,Cefadroxil,,,Watch,Access
10,Cefalexin,,,Watch,Access
11,Cefalotin,,,Watch,Access
12,Cefamandole,,,Watch,Watch
13,Cefazolin,,,Watch,Access
14,Cefepime,,,Watch,Watch
15,Cefiderocol,,,Reserve,Reserve
16,Cefixime,,,Watch,Watch
17,Cefotaxime,,,Watch,Watch
18,Cefoxitin,,,Watch,Watch
19,Cefradine,,,Watch,Access
20,Ceftaroline fosamil,,,Reserve,Reserve
21,Ceftazidime,,,Watch,Watch
22,Ceftazidime + Avibactam,,,Reserve,Reserve
23,Ceftobiprole,,,Reserve,Reserve
24,Ceftolozane + Tazobactam,,,Reserve,Reserve
25,Ceftriaxone,,,Watch,Watch
26,Cefuroxime,,,Watch,Watch
27,Chloramphenicol,,,Watch,Watch
28,Ciprofloxacin,,,Watch,Watch
29,Clarithromycin,,,Watch,Watch
30,Clindamycin,,,Watch,Watch
31,Colistin,intravenous,P,Reserve,Reserve
32,Colistin,oral,O,Reserve,Reserve
33,Dalbavancin,,,Reserve,Reserve
34,Quinupristin + Dalfopristin,,,Reserve,Reserve
35,Daptomycin,,,Reserve,Reserve
36,Delafloxacin,,,Watch,Watch
37,Demeclocycline,,,Watch,Other
38,Doripenem,,,Reserve,Reserve
39,Doxycycline,,,Access,Access
40,Eravacycline,,,Reserve,Reserve
41,Ertapenem,,,Reserve,Reserve
42,Erythromycin,,,Watch,Watch
43,Fidaxomicin,,,Watch,Watch
44,Flucloxacillin,,,Access,Access
45,Fosfomycin,oral,O,Access,Access
46,Fosfomycin,intravenous,P,Reserve,Reserve
47,Fusidic acid,,,Access,Watch
48,Gentamicin,,,Access,Access
49,Imipenem + Cilastatin,,,Reserve,Reserve
50,Cilastatin + Imipenem + Relebactam,,,Reserve,Reserve
51,Levofloxacin,,,Watch,Watch
52,Linezolid,,,Reserve,Reserve
53,Lymecycline,,,Watch,Watch
54,Meropenem,,,Reserve,Reserve
55,Meropenem + Vaborbactam,,,Reserve,Reserve
56,Methenamine,,,Other,Other
57,Metronidazole,,,Access,Access
58,Minocycline,oral,O,Watch,Watch
59,Moxifloxacin,,,Watch,Watch
60,Nalidixic Acid,,,Other,Other
61,Neomycin,,,Watch,Watch
62,Nitrofurantoin,,,Access,Access
63,Norfloxacin,,,Watch,Watch
64,Ofloxacin,,,Watch,Watch
65,Oritavancin,,,Reserve,Reserve
66,Oxytetracycline,,,Watch,Watch
67,Phenoxymethylpenicillin,,,Access,Access
68,Piperacillin,,,Watch,Watch
69,Piperacillin + Tazobactam,,,Watch,Watch
70,Pivmecillinam,,,Access,Access
71,Pristinamycin,,,Watch,Other
72,Procaine benzylpenicillin,,,Access,Access
73,Spectinomycin,,,Other,Other
74,Spiramycin,,,Other,Other
75,Streptomycin,intravenous,P,Other,Other
76,Sulfadiazine,,,Other,Other
77,Co-trimoxazole,,,Access,Access
78,Sulfamethoxypyridazine,,,Other,Other
79,Sulfapyridine,,,Other,Other
80,Tedizolid,,,Reserve,Reserve
81,Teicoplanin,,,Watch,Watch
82,Telavancin,,,Reserve,Reserve
83,Temocillin,,,Watch,Watch
84,Tetracycline,,,Access,Access
85,Tigecycline,,,Reserve,Reserve
86,Tinidazole,,,Other,Access
87,Tobramycin,,,Watch,Watch
88,Trimethoprim,,,Access,Access
89,Vancomycin,,,Watch,Watch

We can save this as a CSV and upload as a table in BigQuery for further processing. `ebmdatalab.chris.aware_prepared`

In [14]:
csv_path = os.path.join('data', 'AWaRe_prepared.csv')
df_prepared.to_csv(csv_path, index=False)

### Matching to VTMs

We can attempt to match Antibiotic names in the UKHSA to VTMs in dm+d.  

Firstly we will try directly matching.

In [15]:
sql = f"""
  SELECT  
    aware.Antibiotic,
    aware.atc_route,
    aware.aware_2019,
    aware.aware_2024,
    vtm.nm,
  FROM `ebmdatalab.chris.aware_list` aware
  LEFT JOIN `ebmdatalab.dmd.vtm` vtm 
    ON vtm.nm = aware.Antibiotic
  WHERE vtm.invalid IS NOT TRUE
  ORDER BY Antibiotic ASC
"""

# Define the CSV path for caching the results.
csv_path = os.path.join('..', 'data', 'vtm_match.csv')

# Use the cached_read function from the bq library to run the query.
vtm_match = bq.cached_read(sql, csv_path=csv_path)

with pd.option_context('display.max_rows', None):
    display(vtm_match)

,Antibiotic,atc_route,aware_2019,aware_2024,nm
0,Amikacin,NaN,Watch,Watch,Amikacin
1,Amoxicillin,NaN,Access,Access,Amoxicillin
2,Ampicillin,NaN,Access,Access,Ampicillin
3,Azithromycin,NaN,Watch,Watch,Azithromycin
4,Aztreonam,NaN,Reserve,Reserve,Aztreonam
5,Benzathine benzylpenicillin,NaN,Access,Access,Benzathine benzylpenicillin
6,Benzylpenicillin,NaN,Access,Access,Benzylpenicillin
7,Cefaclor,NaN,Watch,Watch,Cefaclor
8,Cefadroxil,NaN,Watch,Access,Cefadroxil
9,Cefalexin,NaN,Watch,Access,Cefalexin
10,Cefalotin,NaN,Watch,Access,NaN
11,Cefamandole,NaN,Watch,Watch,Cefamandole
12,Cefazolin,NaN,Watch,Access,Cefazolin
13,Cefepime,NaN,Watch,Watch,Cefepime
14,Cefiderocol,NaN,Reserve,Reserve,Cefiderocol
15,Cefixime,NaN,Watch,Watch,Cefixime
16,Cefotaxime,NaN,Watch,Watch,Cefotaxime
17,Cefoxitin,NaN,Watch,Watch,Cefoxitin
18,Cefradine,NaN,Watch,Access,Cefradine
19,Ceftaroline fosamil,NaN,Reserve,Reserve,Ceftaroline fosamil
20,Ceftazidime,NaN,Watch,Watch,Ceftazidime
21,Ceftazidime + Avibactam,NaN,Reserve,Reserve,Ceftazidime + Avibactam
22,Ceftobiprole,NaN,Reserve,Reserve,Ceftobiprole
23,Ceftolozane + Tazobactam,NaN,Reserve,Reserve,Ceftolozane + Tazobactam
24,Ceftriaxone,NaN,Watch,Watch,Ceftriaxone
25,Cefuroxime,NaN,Watch,Watch,Cefuroxime
26,Chloramphenicol,NaN,Watch,Watch,Chloramphenicol
27,Cilastatin + Imipenem + Relebactam,NaN,Reserve,Reserve,Cilastatin + Imipenem + Relebactam
28,Ciprofloxacin,NaN,Watch,Watch,Ciprofloxacin
29,Clarithromycin,NaN,Watch,Watch,Clarithromycin
30,Clindamycin,NaN,Watch,Watch,Clindamycin
31,Co-amoxiclav,NaN,Watch,Watch,Co-amoxiclav
32,Co-trimoxazole,NaN,Access,Access,Co-trimoxazole
33,Colistin,P,Reserve,Reserve,Colistin
34,Colistin,O,Reserve,Reserve,Colistin
35,Dalbavancin,NaN,Reserve,Reserve,Dalbavancin
36,Daptomycin,NaN,Reserve,Reserve,Daptomycin
37,Delafloxacin,NaN,Watch,Watch,Delafloxacin
38,Demeclocycline,NaN,Watch,Other,Demeclocycline
39,Doripenem,NaN,Reserve,Reserve,Doripenem
40,Doxycycline,NaN,Access,Access,Doxycycline
41,Eravacycline,NaN,Reserve,Reserve,Eravacycline
42,Ertapenem,NaN,Reserve,Reserve,Ertapenem
43,Erythromycin,NaN,Watch,Watch,Erythromycin
44,Fidaxomicin,NaN,Watch,Watch,Fidaxomicin
45,Flucloxacillin,NaN,Access,Access,Flucloxacillin
46,Fosfomycin,P,Reserve,Reserve,Fosfomycin
47,Fosfomycin,O,Access,Access,Fosfomycin
48,Fusidic acid,NaN,Access,Watch,Fusidic acid
49,Gentamicin,NaN,Access,Access,Gentamicin
50,Imipenem + Cilastatin,NaN,Reserve,Reserve,Imipenem + Cilastatin
51,Levofloxacin,NaN,Watch,Watch,Levofloxacin
52,Linezolid,NaN,Reserve,Reserve,Linezolid
53,Lymecycline,NaN,Watch,Watch,Lymecycline
54,Meropenem,NaN,Reserve,Reserve,Meropenem
55,Meropenem + Vaborbactam,NaN,Reserve,Reserve,Meropenem + Vaborbactam
56,Methenamine,NaN,Other,Other,Methenamine
57,Metronidazole,NaN,Access,Access,Metronidazole
58,Minocycline,O,Watch,Watch,Minocycline
59,Moxifloxacin,NaN,Watch,Watch,Moxifloxacin
60,Nalidixic Acid,NaN,Other,Other,NaN
61,Neomycin,NaN,Watch,Watch,Neomycin
62,Nitrofurantoin,NaN,Access,Access,Nitrofurantoin
63,Norfloxacin,NaN,Watch,Watch,Norfloxacin
64,Ofloxacin,NaN,Watch,Watch,Ofloxacin
65,Oritavancin,NaN,Reserve,Reserve,Oritavancin
66,Oxytetracycline,NaN,Watch,Watch,Oxytetracycline
67,Phenoxymethylpenicillin,NaN,Access,Access,Phenoxymethylpenicillin
68,Piperacillin,NaN,Watch,Watch,NaN
69,Piperacillin + Tazobactam,NaN,Watch,Watch,Piperacillin + Tazobactam
70,Pivmecillinam,NaN,Access,Access,Pivmecillinam
71,Pristinamycin,NaN,Watch,Other,Pristinamycin
72,Procaine benzylpenicillin,NaN,Access,Access,Procaine benzylpenicillin
73,Quinupristin + Dalfopristin,NaN,Reserve,Reserve,Quinupristin + Dalfopristin
74,Spectinomycin,NaN,Other,Other,Spectinomycin
75,Spiramycin,NaN,Other,Other,Spiramycin
76,Streptomycin,P,Other,Other,Streptomycin
77,Sulfadiazine,NaN,Other,Other,Sulfadiazine
78,Sulfamethoxypyridazine,NaN,Other,Other,Sulfamethoxypyridazine
79,Sulfapyridine,NaN,Other,Other,Sulfapyridine
80,Tedizolid,NaN,Reserve,Reserve,Tedizolid
81,Teicoplanin,NaN,Watch,Watch,Teicoplanin
82,Telavancin,NaN,Reserve,Reserve,Telavancin
83,Temocillin,NaN,Watch,Watch,Temocillin
84,Tetracycline,NaN,Access,Access,Tetracycline
85,Tigecycline,NaN,Reserve,Reserve,Tigecycline
86,Tinidazole,NaN,Other,Access,Tinidazole
87,Tobramycin,NaN,Watch,Watch,Tobramycin
88,Trimethoprim,NaN,Access,Access,Trimethoprim
89,Vancomycin,NaN,Watch,Watch,Vancomycin

This works to match VTMs to many of the listing. But doesn't capture where there are multiple VTM matches - for example Amikacin and Amikacin liposomal for Amikacin. 

We can use more fuzzy matching to get greater sensitivity in the matches.

In [16]:
sql = f"""
  SELECT  
    aware.Antibiotic,
    aware.atc_route,
    aware.aware_2019,
    aware.aware_2024,
    vtm.nm,
    CASE
      WHEN aware.Antibiotic = vtm.nm THEN 'DIRECT'
      ELSE 'ASSUMED'
    END AS match_type
  FROM `ebmdatalab.chris.aware_list` aware
  LEFT JOIN `ebmdatalab.dmd.vtm` vtm 
    ON vtm.nm LIKE CONCAT('%', aware.Antibiotic, '%')
  WHERE vtm.invalid IS NOT TRUE
  ORDER BY Antibiotic ASC
"""

# Define the CSV path for caching the results.
csv_path = os.path.join('..', 'data', 'vtm_fuzzy_match.csv')

# Use the cached_read function from the bq library to run the query.
vtm_fuzzy_match = bq.cached_read(sql, csv_path=csv_path)

with pd.option_context('display.max_rows', None):
    display(vtm_fuzzy_match)

,Antibiotic,atc_route,aware_2019,aware_2024,nm,match_type
0,Amikacin,NaN,Watch,Watch,Amikacin liposomal,ASSUMED
1,Amikacin,NaN,Watch,Watch,Amikacin,DIRECT
2,Amoxicillin,NaN,Access,Access,Amoxicillin,DIRECT
3,Ampicillin,NaN,Access,Access,Ampicillin,DIRECT
4,Ampicillin,NaN,Access,Access,Ampicillin + Flucloxacillin,ASSUMED
5,Azithromycin,NaN,Watch,Watch,Azithromycin,DIRECT
6,Aztreonam,NaN,Reserve,Reserve,Aztreonam + Avibactam,ASSUMED
7,Aztreonam,NaN,Reserve,Reserve,Aztreonam,DIRECT
8,Benzathine benzylpenicillin,NaN,Access,Access,Benzathine benzylpenicillin,DIRECT
9,Benzylpenicillin,NaN,Access,Access,Benzylpenicillin,DIRECT
10,Cefaclor,NaN,Watch,Watch,Cefaclor,DIRECT
11,Cefadroxil,NaN,Watch,Access,Cefadroxil,DIRECT
12,Cefalexin,NaN,Watch,Access,Cefalexin,DIRECT
13,Cefalotin,NaN,Watch,Access,NaN,ASSUMED
14,Cefamandole,NaN,Watch,Watch,Cefamandole,DIRECT
15,Cefazolin,NaN,Watch,Access,Cefazolin,DIRECT
16,Cefepime,NaN,Watch,Watch,Cefepime + Enmetazobactam,ASSUMED
17,Cefepime,NaN,Watch,Watch,Cefepime,DIRECT
18,Cefiderocol,NaN,Reserve,Reserve,Cefiderocol,DIRECT
19,Cefixime,NaN,Watch,Watch,Cefixime,DIRECT
20,Cefotaxime,NaN,Watch,Watch,Cefotaxime,DIRECT
21,Cefoxitin,NaN,Watch,Watch,Cefoxitin,DIRECT
22,Cefradine,NaN,Watch,Access,Cefradine,DIRECT
23,Ceftaroline fosamil,NaN,Reserve,Reserve,Ceftaroline fosamil,DIRECT
24,Ceftazidime,NaN,Watch,Watch,Ceftazidime + Avibactam,ASSUMED
25,Ceftazidime,NaN,Watch,Watch,Ceftazidime,DIRECT
26,Ceftazidime + Avibactam,NaN,Reserve,Reserve,Ceftazidime + Avibactam,DIRECT
27,Ceftobiprole,NaN,Reserve,Reserve,Ceftobiprole,DIRECT
28,Ceftolozane + Tazobactam,NaN,Reserve,Reserve,Ceftolozane + Tazobactam,DIRECT
29,Ceftriaxone,NaN,Watch,Watch,Ceftriaxone,DIRECT
30,Cefuroxime,NaN,Watch,Watch,Cefuroxime,DIRECT
31,Chloramphenicol,NaN,Watch,Watch,Chloramphenicol,DIRECT
32,Cilastatin + Imipenem + Relebactam,NaN,Reserve,Reserve,Cilastatin + Imipenem + Relebactam,DIRECT
33,Ciprofloxacin,NaN,Watch,Watch,Ciprofloxacin + Dexamethasone,ASSUMED
34,Ciprofloxacin,NaN,Watch,Watch,Ciprofloxacin,DIRECT
35,Ciprofloxacin,NaN,Watch,Watch,Ciprofloxacin + Fluocinolone acetonide,ASSUMED
36,Clarithromycin,NaN,Watch,Watch,Clarithromycin,DIRECT
37,Clindamycin,NaN,Watch,Watch,Clindamycin + Tretinoin,ASSUMED
38,Clindamycin,NaN,Watch,Watch,Clindamycin + Hydrocortisone,ASSUMED
39,Clindamycin,NaN,Watch,Watch,Clindamycin,DIRECT
40,Clindamycin,NaN,Watch,Watch,Benzoyl peroxide + Clindamycin,ASSUMED
41,Co-amoxiclav,NaN,Watch,Watch,Co-amoxiclav,DIRECT
42,Co-trimoxazole,NaN,Access,Access,Co-trimoxazole,DIRECT
43,Colistin,P,Reserve,Reserve,Colistin,DIRECT
44,Colistin,O,Reserve,Reserve,Colistin,DIRECT
45,Dalbavancin,NaN,Reserve,Reserve,Dalbavancin,DIRECT
46,Daptomycin,NaN,Reserve,Reserve,Daptomycin,DIRECT
47,Delafloxacin,NaN,Watch,Watch,Delafloxacin,DIRECT
48,Demeclocycline,NaN,Watch,Other,Demeclocycline,DIRECT
49,Doripenem,NaN,Reserve,Reserve,Doripenem,DIRECT
50,Doxycycline,NaN,Access,Access,Betamethasone + Doxycycline + Nystatin,ASSUMED
51,Doxycycline,NaN,Access,Access,Doxycycline,DIRECT
52,Eravacycline,NaN,Reserve,Reserve,Eravacycline,DIRECT
53,Ertapenem,NaN,Reserve,Reserve,Ertapenem,DIRECT
54,Erythromycin,NaN,Watch,Watch,Erythromycin + Zinc acetate,ASSUMED
55,Erythromycin,NaN,Watch,Watch,Tretinoin + Erythromycin,ASSUMED
56,Erythromycin,NaN,Watch,Watch,Isotretinoin + Erythromycin,ASSUMED
57,Erythromycin,NaN,Watch,Watch,Erythromycin lactobionate,ASSUMED
58,Erythromycin,NaN,Watch,Watch,Erythromycin,DIRECT
59,Erythromycin,NaN,Watch,Watch,Benzoyl peroxide + Erythromycin,ASSUMED
60,Erythromycin,NaN,Watch,Watch,Erythromycin ethyl succinate,ASSUMED
61,Erythromycin,NaN,Watch,Watch,Erythromycin stearate,ASSUMED
62,Fidaxomicin,NaN,Watch,Watch,Fidaxomicin,DIRECT
63,Flucloxacillin,NaN,Access,Access,Flucloxacillin,DIRECT
64,Flucloxacillin,NaN,Access,Access,Ampicillin + Flucloxacillin,ASSUMED
65,Fosfomycin,P,Reserve,Reserve,Fosfomycin,DIRECT
66,Fosfomycin,O,Access,Access,Fosfomycin,DIRECT
67,Fusidic acid,NaN,Access,Watch,Fusidic acid,DIRECT
68,Fusidic acid,NaN,Access,Watch,Betamethasone + Fusidic acid,ASSUMED
69,Fusidic acid,NaN,Access,Watch,Hydrocortisone + Fusidic acid,ASSUMED
70,Gentamicin,NaN,Access,Access,Gentamicin + Hydrocortisone,ASSUMED
71,Gentamicin,NaN,Access,Access,Gentamicin,DIRECT
72,Imipenem + Cilastatin,NaN,Reserve,Reserve,Imipenem + Cilastatin,DIRECT
73,Levofloxacin,NaN,Watch,Watch,Levofloxacin,DIRECT
74,Levofloxacin,NaN,Watch,Watch,Dexamethasone + Levofloxacin,ASSUMED
75,Linezolid,NaN,Reserve,Reserve,Linezolid,DIRECT
76,Lymecycline,NaN,Watch,Watch,Lymecycline,DIRECT
77,Meropenem,NaN,Reserve,Reserve,Meropenem,DIRECT
78,Meropenem,NaN,Reserve,Reserve,Meropenem + Vaborbactam,ASSUMED
79,Meropenem + Vaborbactam,NaN,Reserve,Reserve,Meropenem + Vaborbactam,DIRECT
80,Methenamine,NaN,Other,Other,Methenamine,DIRECT
81,Metronidazole,NaN,Access,Access,Metronidazole,DIRECT
82,Minocycline,O,Watch,Watch,Minocycline,DIRECT
83,Moxifloxacin,NaN,Watch,Watch,Moxifloxacin,DIRECT
84,Nalidixic Acid,NaN,Other,Other,NaN,ASSUMED
85,Neomycin,NaN,Watch,Watch,Clobetasol + Neomycin + Nystatin,ASSUMED
86,Neomycin,NaN,Watch,Watch,Betamethasone + Neomycin,ASSUMED
87,Neomycin,NaN,Watch,Watch,Neomycin + Gramicidin,ASSUMED
88,Neomycin,NaN,Watch,Watch,Neomycin + Chlorhexidine,ASSUMED
89,Neomycin,NaN,Watch,Watch,Neomycin,DIRECT
90,Neomycin,NaN,Watch,Watch,Hydrocortisone + Neomycin,ASSUMED
91,Neomycin,NaN,Watch,Watch,Fluocinolone acetonide + Neomycin,ASSUMED
92,Neomycin,NaN,Watch,Watch,Neomycin + Triamcinolone,ASSUMED
93,Neomycin,NaN,Watch,Watch,Neomycin + Prednisolone,ASSUMED
94,Nitrofurantoin,NaN,Access,Access,Nitrofurantoin,DIRECT
95,Norfloxacin,NaN,Watch,Watch,Norfloxacin,DIRECT
96,Ofloxacin,NaN,Watch,Watch,Ofloxacin,DIRECT
97,Oritavancin,NaN,Reserve,Reserve,Oritavancin,DIRECT
98,Oxytetracycline,NaN,Watch,Watch,Oxytetracycline + Hydrocortisone,ASSUMED
99,Oxytetracycline,NaN,Watch,Watch,Oxytetracycline,DIRECT
100,Oxytetracycline,NaN,Watch,Watch,Clobetasone + Oxytetracycline + Nystatin,ASSUMED
101,Phenoxymethylpenicillin,NaN,Access,Access,Phenoxymethylpenicillin,DIRECT
102,Piperacillin,NaN,Watch,Watch,Piperacillin + Tazobactam,ASSUMED
103,Piperacillin + Tazobactam,NaN,Watch,Watch,Piperacillin + Tazobactam,DIRECT
104,Pivmecillinam,NaN,Access,Access,Pivmecillinam,DIRECT
105,Pristinamycin,NaN,Watch,Other,Pristinamycin,DIRECT
106,Procaine benzylpenicillin,NaN,Access,Access,Procaine benzylpenicillin,DIRECT
107,Quinupristin + Dalfopristin,NaN,Reserve,Reserve,Quinupristin + Dalfopristin,DIRECT
108,Spectinomycin,NaN,Other,Other,Spectinomycin,DIRECT
109,Spiramycin,NaN,Other,Other,Spiramycin,DIRECT
110,Streptomycin,P,Other,Other,Streptomycin,DIRECT
111,Sulfadiazine,NaN,Other,Other,Cerium nitrate + Sulfadiazine silver,ASSUMED
112,Sulfadiazine,NaN,Other,Other,Sulfadiazine,DIRECT
113,Sulfadiazine,NaN,Other,Other,Sulfadiazine silver,ASSUMED
114,Sulfamethoxypyridazine,NaN,Other,Other,Sulfamethoxypyridazine,DIRECT
115,Sulfapyridine,NaN,Other,Other,Sulfapyridine,DIRECT
116,Tedizolid,NaN,Reserve,Reserve,Tedizolid,DIRECT
117,Teicoplanin,NaN,Watch,Watch,Teicoplanin,DIRECT
118,Telavancin,NaN,Reserve,Reserve,Telavancin,DIRECT
119,Temocillin,NaN,Watch,Watch,Temocillin,DIRECT
120,Tetracycline,NaN,Access,Access,Tetracycline,DIRECT
121,Tigecycline,NaN,Reserve,Reserve,Tigecycline,DIRECT
122,Tinidazole,NaN,Other,Access,Tinidazole,DIRECT
123,Tobramycin,NaN,Watch,Watch,Tobramycin,DIRECT
124,Tobramycin,NaN,Watch,Watch,Dexamethasone + Tobramycin,ASSUMED
125,Trimethoprim,NaN,Access,Access,Trimethoprim,DIRECT
126,Trimethoprim,NaN,Access,Access,Polymyxin B + Trimethoprim,ASSUMED
127,Vancomycin,NaN,Watch,Watch,Vancomycin,DIRECT

This gives a number of duplicate matches - for example Meropenem + Vaborbactam matches to both Meropenem and Meropenem + Vaborbactam

We can look for all the duplicates

In [17]:
sql = f"""
WITH matched_vtms AS (
  SELECT  
    aware.Antibiotic,
    aware.atc_route,
    aware.aware_2019,
    aware.aware_2024,
    vtm.nm,
    CASE
      WHEN aware.Antibiotic = vtm.nm THEN 'DIRECT'
      ELSE 'ASSUMED'
    END AS match_type
  FROM `ebmdatalab.chris.aware_list` aware
  LEFT JOIN `ebmdatalab.dmd.vtm` vtm 
    ON vtm.nm LIKE CONCAT('%', aware.Antibiotic, '%')
  WHERE vtm.invalid IS NOT TRUE
)

SELECT *
FROM matched_vtms
WHERE nm IN (
  SELECT nm
  FROM matched_vtms
  WHERE atc_route IS NULL
  GROUP BY nm
  HAVING COUNT(*) > 1
)
ORDER BY Antibiotic ASC;
"""

# Define the CSV path for caching the results.
csv_path = os.path.join('..', 'data', 'vtm_duplicates.csv')

# Use the cached_read function from the bq library to run the query.
vtm_duplicates = bq.cached_read(sql, csv_path=csv_path)

with pd.option_context('display.max_rows', None):
    display(vtm_duplicates)

,Antibiotic,atc_route,aware_2019,aware_2024,nm,match_type
0,Ampicillin,NaN,Access,Access,Ampicillin + Flucloxacillin,ASSUMED
1,Ceftazidime,NaN,Watch,Watch,Ceftazidime + Avibactam,ASSUMED
2,Ceftazidime + Avibactam,NaN,Reserve,Reserve,Ceftazidime + Avibactam,DIRECT
3,Flucloxacillin,NaN,Access,Access,Ampicillin + Flucloxacillin,ASSUMED
4,Meropenem,NaN,Reserve,Reserve,Meropenem + Vaborbactam,ASSUMED
5,Meropenem + Vaborbactam,NaN,Reserve,Reserve,Meropenem + Vaborbactam,DIRECT
6,Piperacillin,NaN,Watch,Watch,Piperacillin + Tazobactam,ASSUMED
7,Piperacillin + Tazobactam,NaN,Watch,Watch,Piperacillin + Tazobactam,DIRECT

From this we can create a list of the unwanted duplicates to remove from our full list.

In [18]:
sql = f"""
WITH matched_vtms AS (
  SELECT  
    aware.Antibiotic,
    aware.atc_route,
    aware.aware_2019,
    aware.aware_2024,
    vtm.nm,
    CASE
      WHEN aware.Antibiotic = vtm.nm THEN 'DIRECT'
      ELSE 'ASSUMED'
    END AS match_type
  FROM `ebmdatalab.chris.aware_list` aware
  LEFT JOIN `ebmdatalab.dmd.vtm` vtm 
    ON vtm.nm LIKE CONCAT('%', aware.Antibiotic, '%')
  WHERE vtm.invalid IS NOT TRUE
)

SELECT *
FROM matched_vtms
WHERE nm IN (
  SELECT nm
  FROM matched_vtms
  WHERE atc_route IS NULL
  GROUP BY nm
  HAVING COUNT(*) > 1
) AND match_type = 'ASSUMED' 
    AND NOT (Antibiotic='Ampicillin' AND nm='Ampicillin + Flucloxacillin')
ORDER BY Antibiotic ASC;
"""

# Define the CSV path for caching the results.
csv_path = os.path.join('..', 'data', 'vtm_duplicates_direct.csv')

# Use the cached_read function from the bq library to run the query.
vtm_duplicates_direct = bq.cached_read(sql, csv_path=csv_path)

with pd.option_context('display.max_rows', None):
    display(vtm_duplicates_direct)

,Antibiotic,atc_route,aware_2019,aware_2024,nm,match_type
0,Ceftazidime,NaN,Watch,Watch,Ceftazidime + Avibactam,ASSUMED
1,Flucloxacillin,NaN,Access,Access,Ampicillin + Flucloxacillin,ASSUMED
2,Meropenem,NaN,Reserve,Reserve,Meropenem + Vaborbactam,ASSUMED
3,Piperacillin,NaN,Watch,Watch,Piperacillin + Tazobactam,ASSUMED

We can then create a full list of potential VTMs with duplicates removed.

In [19]:
sql = f"""
WITH matched_vtms AS ( -- This query does the fuzzy matching of Antibiotic name to VTM name
  SELECT  
    aware.Antibiotic,
    aware.atc_route,
    aware.aware_2019,
    aware.aware_2024,
    vtm.nm,
    vtm.id,
    CASE
      WHEN aware.Antibiotic = vtm.nm THEN 'DIRECT'
      ELSE 'ASSUMED'
    END AS match_type
  FROM `ebmdatalab.chris.aware_list` aware
  LEFT JOIN `ebmdatalab.dmd.vtm` vtm 
    ON vtm.nm LIKE CONCAT('%', aware.Antibiotic, '%')
  WHERE vtm.invalid IS NOT TRUE
),

manual_exceptions AS ( -- This is a list of manual exceptions used when recluding assumed matches
  SELECT 'Ampicillin' AS Antibiotic, 'Ampicillin + Flucloxacillin' AS nm
  -- Add more rows here as needed
),

duplicate_vtms AS ( -- This produces a list of duplicate rows where a direct match already exists
  SELECT *
  FROM matched_vtms
  WHERE nm IN (
    SELECT nm
    FROM matched_vtms
    WHERE atc_route IS NULL
    GROUP BY nm
    HAVING COUNT(*) > 1
  )
  AND match_type = 'ASSUMED'
  AND NOT EXISTS (
    SELECT 1
    FROM manual_exceptions e
    WHERE e.Antibiotic = matched_vtms.Antibiotic AND e.nm = matched_vtms.nm
  )
)

SELECT
  matched_vtms.Antibiotic,
  matched_vtms.nm,
  matched_vtms.id,
  matched_vtms.atc_route,
  matched_vtms.aware_2019,
  matched_vtms.aware_2024,
FROM matched_vtms
WHERE NOT EXISTS ( -- removes the duplicates identified above
  SELECT 1
  FROM duplicate_vtms
  WHERE matched_vtms.Antibiotic = duplicate_vtms.Antibiotic AND matched_vtms.nm = duplicate_vtms.nm
)
ORDER BY matched_vtms.Antibiotic ASC ;
"""

# Define the CSV path for caching the results.
csv_path = os.path.join('..', 'data', 'vtm_match_cleaned.csv')

# Use the cached_read function from the bq library to run the query.
vtm_match_cleaned = bq.cached_read(sql, csv_path=csv_path)

with pd.option_context('display.max_rows', None):
    display(vtm_match_cleaned)

,Antibiotic,nm,id,atc_route,aware_2019,aware_2024
0,Amikacin,Amikacin liposomal,7.824210e+08,NaN,Watch,Watch
1,Amikacin,Amikacin,7.745340e+08,NaN,Watch,Watch
2,Amoxicillin,Amoxicillin,7.745860e+08,NaN,Access,Access
3,Ampicillin,Ampicillin + Flucloxacillin,7.745920e+08,NaN,Access,Access
4,Ampicillin,Ampicillin,7.745900e+08,NaN,Access,Access
5,Azithromycin,Azithromycin,7.747220e+08,NaN,Watch,Watch
6,Aztreonam,Aztreonam + Avibactam,4.379671e+16,NaN,Reserve,Reserve
7,Aztreonam,Aztreonam,7.747250e+08,NaN,Reserve,Reserve
8,Benzathine benzylpenicillin,Benzathine benzylpenicillin,1.234764e+09,NaN,Access,Access
9,Benzylpenicillin,Benzylpenicillin,7.748260e+08,NaN,Access,Access
10,Cefaclor,Cefaclor,7.750860e+08,NaN,Watch,Watch
11,Cefadroxil,Cefadroxil,7.750870e+08,NaN,Watch,Access
12,Cefalexin,Cefalexin,7.750880e+08,NaN,Watch,Access
13,Cefalotin,NaN,NaN,NaN,Watch,Access
14,Cefamandole,Cefamandole,7.750900e+08,NaN,Watch,Watch
15,Cefazolin,Cefazolin,7.750920e+08,NaN,Watch,Access
16,Cefepime,Cefepime,7.750950e+08,NaN,Watch,Watch
17,Cefepime,Cefepime + Enmetazobactam,4.289421e+16,NaN,Watch,Watch
18,Cefiderocol,Cefiderocol,8.302050e+08,NaN,Reserve,Reserve
19,Cefixime,Cefixime,7.750970e+08,NaN,Watch,Watch
20,Cefotaxime,Cefotaxime,7.751030e+08,NaN,Watch,Watch
21,Cefoxitin,Cefoxitin,7.751070e+08,NaN,Watch,Watch
22,Cefradine,Cefradine,7.751120e+08,NaN,Watch,Access
23,Ceftaroline fosamil,Ceftaroline fosamil,2.138731e+16,NaN,Reserve,Reserve
24,Ceftazidime,Ceftazidime,7.751150e+08,NaN,Watch,Watch
25,Ceftazidime + Avibactam,Ceftazidime + Avibactam,7.813000e+08,NaN,Reserve,Reserve
26,Ceftobiprole,Ceftobiprole,1.287090e+09,NaN,Reserve,Reserve
27,Ceftolozane + Tazobactam,Ceftolozane + Tazobactam,7.751190e+08,NaN,Reserve,Reserve
28,Ceftriaxone,Ceftriaxone,7.751200e+08,NaN,Watch,Watch
29,Cefuroxime,Cefuroxime,7.751210e+08,NaN,Watch,Watch
30,Chloramphenicol,Chloramphenicol,7.751600e+08,NaN,Watch,Watch
31,Cilastatin + Imipenem + Relebactam,Cilastatin + Imipenem + Relebactam,7.890740e+08,NaN,Reserve,Reserve
32,Ciprofloxacin,Ciprofloxacin + Fluocinolone acetonide,3.587311e+16,NaN,Watch,Watch
33,Ciprofloxacin,Ciprofloxacin + Dexamethasone,7.752620e+08,NaN,Watch,Watch
34,Ciprofloxacin,Ciprofloxacin,7.752610e+08,NaN,Watch,Watch
35,Clarithromycin,Clarithromycin,7.752770e+08,NaN,Watch,Watch
36,Clindamycin,Benzoyl peroxide + Clindamycin,7.748120e+08,NaN,Watch,Watch
37,Clindamycin,Clindamycin,7.752880e+08,NaN,Watch,Watch
38,Clindamycin,Clindamycin + Hydrocortisone,2.220751e+16,NaN,Watch,Watch
39,Clindamycin,Clindamycin + Tretinoin,7.752890e+08,NaN,Watch,Watch
40,Co-amoxiclav,Co-amoxiclav,7.745870e+08,NaN,Watch,Watch
41,Co-trimoxazole,Co-trimoxazole,1.803751e+16,NaN,Access,Access
42,Colistin,Colistin,7.753730e+08,O,Reserve,Reserve
43,Colistin,Colistin,7.753730e+08,P,Reserve,Reserve
44,Dalbavancin,Dalbavancin,7.754370e+08,NaN,Reserve,Reserve
45,Daptomycin,Daptomycin,7.754510e+08,NaN,Reserve,Reserve
46,Delafloxacin,Delafloxacin,7.754690e+08,NaN,Watch,Watch
47,Demeclocycline,Demeclocycline,7.754760e+08,NaN,Watch,Other
48,Doripenem,Doripenem,7.756890e+08,NaN,Reserve,Reserve
49,Doxycycline,Doxycycline,7.756980e+08,NaN,Access,Access
50,Doxycycline,Betamethasone + Doxycycline + Nystatin,4.058881e+16,NaN,Access,Access
51,Eravacycline,Eravacycline,7.758070e+08,NaN,Reserve,Reserve
52,Ertapenem,Ertapenem,7.758200e+08,NaN,Reserve,Reserve
53,Erythromycin,Isotretinoin + Erythromycin,7.758230e+08,NaN,Watch,Watch
54,Erythromycin,Benzoyl peroxide + Erythromycin,7.748130e+08,NaN,Watch,Watch
55,Erythromycin,Erythromycin ethyl succinate,3.640851e+16,NaN,Watch,Watch
56,Erythromycin,Erythromycin,7.758220e+08,NaN,Watch,Watch
57,Erythromycin,Erythromycin stearate,3.640861e+16,NaN,Watch,Watch
58,Erythromycin,Tretinoin + Erythromycin,7.758250e+08,NaN,Watch,Watch
59,Erythromycin,Erythromycin + Zinc acetate,7.758270e+08,NaN,Watch,Watch
60,Erythromycin,Erythromycin lactobionate,3.640951e+16,NaN,Watch,Watch
61,Fidaxomicin,Fidaxomicin,7.759610e+08,NaN,Watch,Watch
62,Flucloxacillin,Flucloxacillin,7.759790e+08,NaN,Access,Access
63,Fosfomycin,Fosfomycin,7.760410e+08,P,Reserve,Reserve
64,Fosfomycin,Fosfomycin,7.760410e+08,O,Access,Access
65,Fusidic acid,Betamethasone + Fusidic acid,7.748430e+08,NaN,Access,Watch
66,Fusidic acid,Hydrocortisone + Fusidic acid,7.760590e+08,NaN,Access,Watch
67,Fusidic acid,Fusidic acid,7.760580e+08,NaN,Access,Watch
68,Gentamicin,Gentamicin,7.760940e+08,NaN,Access,Access
69,Gentamicin,Gentamicin + Hydrocortisone,7.760950e+08,NaN,Access,Access
70,Imipenem + Cilastatin,Imipenem + Cilastatin,7.752450e+08,NaN,Reserve,Reserve
71,Levofloxacin,Levofloxacin,7.765170e+08,NaN,Watch,Watch
72,Levofloxacin,Dexamethasone + Levofloxacin,1.286887e+09,NaN,Watch,Watch
73,Linezolid,Linezolid,7.765440e+08,NaN,Reserve,Reserve
74,Lymecycline,Lymecycline,7.765930e+08,NaN,Watch,Watch
75,Meropenem,Meropenem,7.766940e+08,NaN,Reserve,Reserve
76,Meropenem + Vaborbactam,Meropenem + Vaborbactam,7.766950e+08,NaN,Reserve,Reserve
77,Methenamine,Methenamine,7.767250e+08,NaN,Other,Other
78,Metronidazole,Metronidazole,7.767740e+08,NaN,Access,Access
79,Minocycline,Minocycline,7.768000e+08,O,Watch,Watch
80,Moxifloxacin,Moxifloxacin,7.768310e+08,NaN,Watch,Watch
81,Nalidixic Acid,NaN,NaN,NaN,Other,Other
82,Neomycin,Clobetasol + Neomycin + Nystatin,7.752960e+08,NaN,Watch,Watch
83,Neomycin,Neomycin + Gramicidin,7.761450e+08,NaN,Watch,Watch
84,Neomycin,Fluocinolone acetonide + Neomycin,2.263691e+16,NaN,Watch,Watch
85,Neomycin,Neomycin + Triamcinolone,7.768900e+08,NaN,Watch,Watch
86,Neomycin,Neomycin + Chlorhexidine,7.751700e+08,NaN,Watch,Watch
87,Neomycin,Betamethasone + Neomycin,7.748440e+08,NaN,Watch,Watch
88,Neomycin,Neomycin + Prednisolone,7.768890e+08,NaN,Watch,Watch
89,Neomycin,Hydrocortisone + Neomycin,7.762540e+08,NaN,Watch,Watch
90,Neomycin,Neomycin,7.768850e+08,NaN,Watch,Watch
91,Nitrofurantoin,Nitrofurantoin,7.769270e+08,NaN,Access,Access
92,Norfloxacin,Norfloxacin,7.769430e+08,NaN,Watch,Watch
93,Ofloxacin,Ofloxacin,7.769730e+08,NaN,Watch,Watch
94,Oritavancin,Oritavancin,7.770010e+08,NaN,Reserve,Reserve
95,Oxytetracycline,Oxytetracycline + Hydrocortisone,7.762570e+08,NaN,Watch,Watch
96,Oxytetracycline,Clobetasone + Oxytetracycline + Nystatin,7.752990e+08,NaN,Watch,Watch
97,Oxytetracycline,Oxytetracycline,7.770350e+08,NaN,Watch,Watch
98,Phenoxymethylpenicillin,Phenoxymethylpenicillin,7.771750e+08,NaN,Access,Access
99,Piperacillin + Tazobactam,Piperacillin + Tazobactam,7.772120e+08,NaN,Watch,Watch
100,Pivmecillinam,Pivmecillinam,7.772270e+08,NaN,Access,Access
101,Pristinamycin,Pristinamycin,1.625101e+16,NaN,Watch,Other
102,Procaine benzylpenicillin,Procaine benzylpenicillin,1.234762e+09,NaN,Access,Access
103,Quinupristin + Dalfopristin,Quinupristin + Dalfopristin,7.754390e+08,NaN,Reserve,Reserve
104,Spectinomycin,Spectinomycin,7.776000e+08,NaN,Other,Other
105,Spiramycin,Spiramycin,7.776020e+08,NaN,Other,Other
106,Streptomycin,Streptomycin,7.776140e+08,P,Other,Other
107,Sulfadiazine,Cerium nitrate + Sulfadiazine silver,4.277911e+16,NaN,Other,Other
108,Sulfadiazine,Sulfadiazine silver,8.640080e+08,NaN,Other,Other
109,Sulfadiazine,Sulfadiazine,7.775320e+08,NaN,Other,Other
110,Sulfamethoxypyridazine,Sulfamethoxypyridazine,7.776430e+08,NaN,Other,Other
111,Sulfapyridine,Sulfapyridine,1.546581e+16,NaN,Other,Other
112,Tedizolid,Tedizolid,7.776860e+08,NaN,Reserve,Reserve
113,Teicoplanin,Teicoplanin,7.776910e+08,NaN,Watch,Watch
114,Telavancin,Telavancin,7.776930e+08,NaN,Reserve,Reserve
115,Temocillin,Temocillin,7.777000e+08,NaN,Watch,Watch
116,Tetracycline,Tetracycline,7.777300e+08,NaN,Access,Access
117,Tigecycline,Tigecycline,7.777690e+08,NaN,Reserve,Reserve
118,Tinidazole,Tinidazole,7.777750e+08,NaN,Other,Access
119,Tobramycin,Tobramycin,7.777910e+08,NaN,Watch,Watch
120,Tobramycin,Dexamethasone + Tobramycin,7.755020e+08,NaN,Watch,Watch
121,Trimethoprim,Trimethoprim,7.778580e+08,NaN,Access,Access
122,Trimethoprim,Polymyxin B + Trimethoprim,7.772470e+08,NaN,Access,Access
123,Vancomycin,Vancomycin,7.779140e+08,NaN,Watch,Watch

In [20]:
vtm_match_cleaned.to_csv("data/vtm_match_clean.csv", index=False)

### Bringing in VMPs

Now that we have a list of dm+d compatible VTMs, we can bring in matching VMPs.

In [21]:
sql = f"""
WITH matched_vtms AS ( -- This query does the fuzzy matching of Antibiotic name to VTM name
  SELECT  
    aware.Antibiotic,
    aware.atc_route,
    aware.aware_2019,
    aware.aware_2024,
    vtm.nm,
    vtm.id,
    CASE
      WHEN aware.Antibiotic = vtm.nm THEN 'DIRECT'
      ELSE 'ASSUMED'
    END AS match_type
  FROM `ebmdatalab.chris.aware_list` aware
  LEFT JOIN `ebmdatalab.dmd.vtm` vtm 
    ON vtm.nm LIKE CONCAT('%', aware.Antibiotic, '%')
  WHERE vtm.invalid IS NOT TRUE
),

manual_exceptions AS ( -- This is a list of manual exceptions used when recluding assumed matches
  SELECT 'Ampicillin' AS Antibiotic, 'Ampicillin + Flucloxacillin' AS nm
  -- Add more rows here as needed
),

duplicate_vtms AS ( -- This produces a list of duplicate rows where a direct match already exists
  SELECT *
  FROM matched_vtms
  WHERE nm IN (
    SELECT nm
    FROM matched_vtms
    WHERE atc_route IS NULL
    GROUP BY nm
    HAVING COUNT(*) > 1
  )
  AND match_type = 'ASSUMED'
  AND NOT EXISTS (
    SELECT 1
    FROM manual_exceptions e
    WHERE e.Antibiotic = matched_vtms.Antibiotic AND e.nm = matched_vtms.nm
  )
),

vmp_with_route AS (
  SELECT DISTINCT
    vmp.id AS id,
    vmp.vtm AS vtm,
    vmp.nm AS nm,
    COALESCE(sroute.route, routelookup.who_route) AS vmp_atc_route
  FROM `ebmdatalab.dmd.vmp` vmp
  LEFT JOIN dmd.ont ont ON vmp.id = ont.vmp
  LEFT JOIN dmd.ontformroute ofr ON ont.form = ofr.cd
  LEFT JOIN chris.vmp_single_route_identifier sroute ON vmp.id = sroute.vmp_id
  LEFT JOIN `scmd_dmd_views.dmd_to_atc_route` routelookup ON ofr.descr = routelookup.dmd_ofr
)

SELECT DISTINCT
  matched_vtms.Antibiotic,
  matched_vtms.nm as vtm_nm,
  matched_vtms.id as vtm_id,
  vmp.nm as vmp_nm,
  vmp.id as vmp_id,
  vmp.vmp_atc_route,
  matched_vtms.atc_route,
  matched_vtms.aware_2019,
  matched_vtms.aware_2024
FROM matched_vtms
LEFT JOIN vmp_with_route vmp
  ON matched_vtms.id = vmp.vtm
  AND (
    matched_vtms.atc_route IS NULL
    OR matched_vtms.atc_route = vmp.vmp_atc_route
  )
WHERE NOT EXISTS ( -- removes the duplicates identified above
  SELECT 1
  FROM duplicate_vtms
  WHERE matched_vtms.Antibiotic = duplicate_vtms.Antibiotic AND matched_vtms.nm = duplicate_vtms.nm
)
ORDER BY matched_vtms.Antibiotic ASC;
"""

# Define the CSV path for caching the results.
csv_path = os.path.join('..', 'data', 'vmps_matched.csv')

# Use the cached_read function from the bq library to run the query.
vmps_matched = bq.cached_read(sql, csv_path=csv_path)

vmps_matched

Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|

,Antibiotic,vtm_nm,vtm_id,vmp_nm,vmp_id,vmp_atc_route,atc_route,aware_2019,aware_2024
0,Amikacin,Amikacin,774534000,Amikacin 500mg/2ml solution for injection ampo...,44422511000001103,P,None,Watch,Watch
1,Amikacin,Amikacin,774534000,Amikacin 25mg/5ml solution for injection ampoules,44007311000001107,None,None,Watch,Watch
2,Amikacin,Amikacin,774534000,Amikacin 500mg/100ml infusion polyethylene bot...,41823511000001108,P,None,Watch,Watch
3,Amikacin,Amikacin,774534000,Amikacin 400micrograms/0.1ml intravitreal inje...,38244211000001108,None,None,Watch,Watch
4,Amikacin,Amikacin,774534000,Amikacin 25mg/5ml solution for injection vials,35111911000001104,None,None,Watch,Watch
...,...,...,...,...,...,...,...,...,...
703,Vancomycin,Vancomycin,777914002,Vancomycin 62.5mg/5ml oral solution,13455811000001106,O,None,Watch,Watch
704,Vancomycin,Vancomycin,777914002,Vancomycin 125mg/5ml oral solution,15453011000001107,O,None,Watch,Watch
705,Vancomycin,Vancomycin,777914002,Vancomycin 125mg/5ml oral suspension,15453111000001108,O,None,Watch,Watch
706,Vancomycin,Vancomycin,777914002,Vancomycin 5% eye drops,21407511000001100,None,None,Watch,Watch
707,Vancomycin,Vancomycin,777914002,Vancomycin 1.4% eye drops,22103111000001101,None,None,Watch,Watch

Inspecting this list we can see a number of non-systemic antibiotics which are not considered as part of the AWaRe classification - e.g. eye drops, ointments etc. We can remove these by filtering out when selecting VMPs.

In [22]:
sql = f"""
WITH matched_vtms AS ( -- This query does the fuzzy matching of Antibiotic name to VTM name
  SELECT  
    aware.Antibiotic,
    aware.atc_route,
    aware.aware_2019,
    aware.aware_2024,
    vtm.nm,
    vtm.id,
    CASE
      WHEN aware.Antibiotic = vtm.nm THEN 'DIRECT'
      ELSE 'ASSUMED'
    END AS match_type
  FROM `ebmdatalab.chris.aware_list` aware
  LEFT JOIN `ebmdatalab.dmd.vtm` vtm 
    ON vtm.nm LIKE CONCAT('%', aware.Antibiotic, '%')
  WHERE vtm.invalid IS NOT TRUE
),

manual_exceptions AS ( -- This is a list of manual exceptions used when recluding assumed matches
  SELECT 'Ampicillin' AS Antibiotic, 'Ampicillin + Flucloxacillin' AS nm
  -- Add more rows here as needed
),

duplicate_vtms AS ( -- This produces a list of duplicate rows where a direct match already exists
  SELECT *
  FROM matched_vtms
  WHERE nm IN (
    SELECT nm
    FROM matched_vtms
    WHERE atc_route IS NULL
    GROUP BY nm
    HAVING COUNT(*) > 1
  )
  AND match_type = 'ASSUMED'
  AND NOT EXISTS (
    SELECT 1
    FROM manual_exceptions e
    WHERE e.Antibiotic = matched_vtms.Antibiotic AND e.nm = matched_vtms.nm
  )
),

vmp_with_route AS (
  SELECT DISTINCT
    vmp.id AS id,
    vmp.vtm AS vtm,
    vmp.nm AS nm,
    COALESCE(sroute.route, routelookup.who_route) AS vmp_atc_route
  FROM `ebmdatalab.dmd.vmp` vmp
  LEFT JOIN dmd.ont ont ON vmp.id = ont.vmp
  LEFT JOIN dmd.ontformroute ofr ON ont.form = ofr.cd
  LEFT JOIN chris.vmp_single_route_identifier sroute ON vmp.id = sroute.vmp_id
  LEFT JOIN `scmd_dmd_views.dmd_to_atc_route` routelookup ON ofr.descr = routelookup.dmd_ofr
  WHERE ofr.descr NOT LIKE '%.auricular'
  AND ofr.descr NOT LIKE '%.cutaneous'
  AND ofr.descr NOT LIKE '%.ophthalmic'
  AND ofr.descr NOT LIKE '%.oromucosal'
  AND ofr.descr NOT LIKE '%.intralesional'
  AND ofr.descr NOT LIKE '%.nasal'
)

SELECT DISTINCT
  matched_vtms.Antibiotic,
  matched_vtms.nm as vtm_nm,
  matched_vtms.id as vtm_id,
  vmp.nm as vmp_nm,
  vmp.id as vmp_id,
  vmp.vmp_atc_route,
  matched_vtms.atc_route,
  matched_vtms.aware_2019,
  matched_vtms.aware_2024
FROM matched_vtms
LEFT JOIN vmp_with_route vmp
  ON matched_vtms.id = vmp.vtm
  AND (
    matched_vtms.atc_route IS NULL
    OR matched_vtms.atc_route = vmp.vmp_atc_route
  )
WHERE NOT EXISTS ( -- removes the duplicates identified above
  SELECT 1
  FROM duplicate_vtms
  WHERE matched_vtms.Antibiotic = duplicate_vtms.Antibiotic AND matched_vtms.nm = duplicate_vtms.nm
) AND vmp.id IS NOT NULL
ORDER BY matched_vtms.Antibiotic ASC;
"""

# Define the CSV path for caching the results.
csv_path = os.path.join('..', 'data', 'vmps_matched.csv')

# Use the cached_read function from the bq library to run the query.
vmps_matched = bq.cached_read(sql, csv_path=csv_path)

with pd.option_context('display.max_rows', None):
    display(vmps_matched)

Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|

,Antibiotic,vtm_nm,vtm_id,vmp_nm,vmp_id,vmp_atc_route,atc_route,aware_2019,aware_2024
0,Amikacin,Amikacin,774534000,Amikacin 500mg/2ml solution for injection ampo...,44422511000001103,P,None,Watch,Watch
1,Amikacin,Amikacin,774534000,Amikacin 25mg/5ml solution for injection ampoules,44007311000001107,None,None,Watch,Watch
2,Amikacin,Amikacin,774534000,Amikacin 500mg/100ml infusion polyethylene bot...,41823511000001108,P,None,Watch,Watch
3,Amikacin,Amikacin,774534000,Amikacin 400micrograms/0.1ml intravitreal inje...,38244211000001108,None,None,Watch,Watch
4,Amikacin,Amikacin,774534000,Amikacin 25mg/5ml solution for injection vials,35111911000001104,None,None,Watch,Watch
5,Amikacin,Amikacin,774534000,Amikacin 25mg/5ml solution for injection pre-f...,35104511000001105,None,None,Watch,Watch
6,Amikacin,Amikacin,774534000,Amikacin 500mg/2ml solution for injection vials,35899911000001109,P,None,Watch,Watch
7,Amikacin,Amikacin,774534000,Amikacin 100mg/2ml solution for injection vials,35899811000001104,P,None,Watch,Watch
8,Amikacin,Amikacin liposomal,782421008,Amikacin liposomal 590mg nebuliser dispersion ...,39601711000001109,Inhal.solution,None,Watch,Watch
9,Amoxicillin,Amoxicillin,774586009,Amoxicillin 500mg/50ml infusion bags,34226911000001109,P,None,Access,Access
10,Amoxicillin,Amoxicillin,774586009,Amoxicillin 250mg capsules,39732311000001104,O,None,Access,Access
11,Amoxicillin,Amoxicillin,774586009,Amoxicillin 500mg capsules,39732411000001106,O,None,Access,Access
12,Amoxicillin,Amoxicillin,774586009,Amoxicillin 250mg/5ml oral suspension,41941111000001109,O,None,Access,Access
13,Amoxicillin,Amoxicillin,774586009,Amoxicillin 250mg/5ml oral suspension sugar free,39021911000001105,O,None,Access,Access
14,Amoxicillin,Amoxicillin,774586009,Amoxicillin 125mg/5ml oral suspension,41940811000001105,O,None,Access,Access
15,Amoxicillin,Amoxicillin,774586009,Amoxicillin 125mg/5ml oral suspension sugar free,35901911000001104,O,None,Access,Access
16,Amoxicillin,Amoxicillin,774586009,Amoxicillin 125mg/1.25ml oral suspension paedi...,35368511000001109,O,None,Access,Access
17,Amoxicillin,Amoxicillin,774586009,Amoxicillin 500mg powder for solution for inje...,41941211000001103,P,None,Access,Access
18,Amoxicillin,Amoxicillin,774586009,Amoxicillin 250mg powder for solution for inje...,41941011000001108,P,None,Access,Access
19,Amoxicillin,Amoxicillin,774586009,Amoxicillin 1g powder for solution for injecti...,41940911000001100,P,None,Access,Access
20,Amoxicillin,Amoxicillin,774586009,Amoxicillin 3g oral powder sachets sugar free,35902111000001107,O,None,Access,Access
21,Amoxicillin,Amoxicillin,774586009,Amoxicillin 500mg tablets,44456411000001100,O,None,Access,Access
22,Amoxicillin,Amoxicillin,774586009,Amoxicillin 1g dispersible tablets sugar free,38726811000001109,O,None,Access,Access
23,Amoxicillin,Amoxicillin,774586009,Amoxicillin 500mg/5ml oral suspension sugar free,41941311000001106,O,None,Access,Access
24,Ampicillin,Ampicillin,774590006,Ampicillin 250mg capsules,41941511000001100,O,None,Access,Access
25,Ampicillin,Ampicillin,774590006,Ampicillin 500mg capsules,41941711000001105,O,None,Access,Access
26,Ampicillin,Ampicillin,774590006,Ampicillin 125mg/5ml oral suspension,41941411000001104,O,None,Access,Access
27,Ampicillin,Ampicillin,774590006,Ampicillin 250mg/5ml oral suspension,41941611000001101,O,None,Access,Access
28,Ampicillin,Ampicillin,774590006,Ampicillin 500mg powder for solution for injec...,41941811000001102,P,None,Access,Access
29,Ampicillin,Ampicillin,774590006,Ampicillin 500mg powder for solution for injec...,41941811000001102,None,None,Access,Access
30,Azithromycin,Azithromycin,774722005,Azithromycin 500mg powder for solution for inf...,41942111000001104,P,None,Watch,Watch
31,Azithromycin,Azithromycin,774722005,Azithromycin 500mg tablets,39733511000001103,O,None,Watch,Watch
32,Azithromycin,Azithromycin,774722005,Azithromycin 250mg capsules,41942011000001100,O,None,Watch,Watch
33,Azithromycin,Azithromycin,774722005,Azithromycin 200mg/5ml oral suspension,41941911000001107,O,None,Watch,Watch
34,Azithromycin,Azithromycin,774722005,Azithromycin 250mg tablets,11034311000001100,O,None,Watch,Watch
35,Azithromycin,Azithromycin,774722005,Azithromycin 200mg/5ml oral suspension sugar free,29668711000001101,O,None,Watch,Watch
36,Aztreonam,Aztreonam + Avibactam,43796711000001109,Aztreonam 1.5g / Avibactam 500mg powder for so...,43801411000001109,P,None,Reserve,Reserve
37,Aztreonam,Aztreonam,774725007,Aztreonam 75mg powder and solvent for nebulise...,17463011000001100,Inhal.solution,None,Reserve,Reserve
38,Aztreonam,Aztreonam,774725007,Aztreonam 500mg powder for solution for inject...,41759611000001105,P,None,Reserve,Reserve
39,Aztreonam,Aztreonam,774725007,Aztreonam 1g powder for solution for injection...,41759411000001107,P,None,Reserve,Reserve
40,Aztreonam,Aztreonam,774725007,Aztreonam 2g powder for solution for injection...,41759511000001106,P,None,Reserve,Reserve
41,Aztreonam,Aztreonam,774725007,Aztreonam 75mg powder and solvent for nebulise...,17463411000001109,Inhal.solution,None,Reserve,Reserve
42,Benzathine benzylpenicillin,Benzathine benzylpenicillin,1234764000,Benzathine benzylpenicillin 2.4million unit po...,44168511000001109,P,None,Access,Access
43,Benzathine benzylpenicillin,Benzathine benzylpenicillin,1234764000,Benzathine benzylpenicillin 1.2million unit po...,42683111000001104,P,None,Access,Access
44,Benzathine benzylpenicillin,Benzathine benzylpenicillin,1234764000,Benzathine benzylpenicillin 1.2million unit po...,10153111000001102,P,None,Access,Access
45,Benzathine benzylpenicillin,Benzathine benzylpenicillin,1234764000,Benzathine benzylpenicillin 2.4million unit po...,10153211000001108,P,None,Access,Access
46,Benzathine benzylpenicillin,Benzathine benzylpenicillin,1234764000,"Benzathine benzylpenicillin 600,000unit powder...",10150911000001107,P,None,Access,Access
47,Benzylpenicillin,Benzylpenicillin,774826003,Benzylpenicillin sodium 1.2g/50ml infusion bags,22097311000001100,P,None,Access,Access
48,Benzylpenicillin,Benzylpenicillin,774826003,Benzylpenicillin sodium 600mg/50ml infusion bags,22085911000001105,P,None,Access,Access
49,Benzylpenicillin,Benzylpenicillin,774826003,Benzylpenicillin sodium 600mg powder for solut...,41942311000001102,P,None,Access,Access
50,Benzylpenicillin,Benzylpenicillin,774826003,Benzylpenicillin sodium 1.2g powder for soluti...,41942211000001105,P,None,Access,Access
51,Cefaclor,Cefaclor,775086009,Cefaclor 250mg capsules,39735011000001107,O,None,Watch,Watch
52,Cefaclor,Cefaclor,775086009,Cefaclor 500mg capsules,39735111000001108,O,None,Watch,Watch
53,Cefaclor,Cefaclor,775086009,Cefaclor 375mg modified-release tablets,36134211000001100,O,None,Watch,Watch
54,Cefaclor,Cefaclor,775086009,Cefaclor 125mg/5ml oral suspension sugar free,36134011000001105,O,None,Watch,Watch
55,Cefaclor,Cefaclor,775086009,Cefaclor 250mg/5ml oral suspension sugar free,36134111000001106,O,None,Watch,Watch
56,Cefaclor,Cefaclor,775086009,Cefaclor 250mg/5ml oral suspension,41942611000001107,O,None,Watch,Watch
57,Cefaclor,Cefaclor,775086009,Cefaclor 125mg/5ml oral suspension,41942511000001108,O,None,Watch,Watch
58,Cefadroxil,Cefadroxil,775087000,Cefadroxil 500mg capsules,39735211000001102,O,None,Watch,Access
59,Cefadroxil,Cefadroxil,775087000,Cefadroxil 125mg/5ml oral suspension,41942711000001103,O,None,Watch,Access
60,Cefadroxil,Cefadroxil,775087000,Cefadroxil 250mg/5ml oral suspension,41942811000001106,O,None,Watch,Access
61,Cefadroxil,Cefadroxil,775087000,Cefadroxil 500mg/5ml oral suspension,41942911000001101,O,None,Watch,Access
62,Cefalexin,Cefalexin,775088005,Cefalexin 250mg/5ml oral suspension,41943111000001105,O,None,Watch,Access
63,Cefalexin,Cefalexin,775088005,Cefalexin 250mg capsules,39735311000001105,O,None,Watch,Access
64,Cefalexin,Cefalexin,775088005,Cefalexin 125mg/5ml oral suspension,41943011000001109,O,None,Watch,Access
65,Cefalexin,Cefalexin,775088005,Cefalexin 500mg capsules,39694811000001102,O,None,Watch,Access
66,Cefalexin,Cefalexin,775088005,Cefalexin 250mg tablets,39684111000001105,O,None,Watch,Access
67,Cefalexin,Cefalexin,775088005,Cefalexin 500mg tablets,39735911000001106,O,None,Watch,Access
68,Cefalexin,Cefalexin,775088005,Cefalexin 500mg/5ml oral suspension,36134311000001108,O,None,Watch,Access
69,Cefalexin,Cefalexin,775088005,Cefalexin 250mg/5ml oral suspension sugar free,4515811000001108,O,None,Watch,Access
70,Cefalexin,Cefalexin,775088005,Cefalexin 125mg/5ml oral suspension sugar free,4865011000001104,O,None,Watch,Access
71,Cefamandole,Cefamandole,775090006,Cefamandole 1g powder for solution for injecti...,4457111000001107,P,None,Watch,Watch
72,Cefazolin,Cefazolin,775092003,Cefazolin 1g powder for solution for injection...,41872611000001103,P,None,Watch,Access
73,Cefazolin,Cefazolin,775092003,Cefazolin 500mg powder for solution for inject...,41872711000001107,P,None,Watch,Access
74,Cefazolin,Cefazolin,775092003,Cefazolin 2g powder for solution for injection...,33631211000001106,P,None,Watch,Access
75,Cefepime,Cefepime + Enmetazobactam,42894211000001100,Cefepime 2g / Enmetazobactam 500mg powder for ...,42894511000001102,P,None,Watch,Watch
76,Cefepime,Cefepime,775095001,Cefepime 1g powder for solution for injection ...,36458411000001105,P,None,Watch,Watch
77,Cefepime,Cefepime,775095001,Cefepime 2g powder for solution for injection ...,36458511000001109,P,None,Watch,Watch
78,Cefiderocol,Cefiderocol,830205006,Cefiderocol 1g powder for solution for infusio...,39002611000001100,P,None,Reserve,Reserve
79,Cefixime,Cefixime,775097009,Cefixime 200mg tablets,41943211000001104,O,None,Watch,Watch
80,Cefixime,Cefixime,775097009,Cefixime 100mg/5ml oral suspension,36134411000001101,O,None,Watch,Watch
81,Cefixime,Cefixime,775097009,Cefixime 400mg tablets,41943311000001107,O,None,Watch,Watch
82,Cefotaxime,Cefotaxime,775103002,Cefotaxime 1g/50ml infusion bags,44009011000001100,P,None,Watch,Watch
83,Cefotaxime,Cefotaxime,775103002,Cefotaxime 2g/100ml infusion bags,44007911000001108,P,None,Watch,Watch
84,Cefotaxime,Cefotaxime,775103002,Cefotaxime 1g powder for solution for injectio...,41943411000001100,P,None,Watch,Watch
85,Cefotaxime,Cefotaxime,775103002,Cefotaxime 500mg powder for solution for injec...,41943511000001101,P,None,Watch,Watch
86,Cefotaxime,Cefotaxime,775103002,Cefotaxime 2g powder for solution for injectio...,4558311000001100,P,None,Watch,Watch
87,Cefoxitin,Cefoxitin,775107001,Cefoxitin 1g powder for solution for injection...,41943611000001102,P,None,Watch,Watch
88,Cefoxitin,Cefoxitin,775107001,Cefoxitin 2g powder for solution for injection...,41943711000001106,P,None,Watch,Watch
89,Cefradine,Cefradine,775112000,Cefradine 250mg capsules,41944511000001103,O,None,Watch,Access
90,Cefradine,Cefradine,775112000,Cefradine 500mg capsules,41944611000001104,O,None,Watch,Access
91,Cefradine,Cefradine,775112000,Cefradine 1g powder for solution for injection...,41944411000001102,P,None,Watch,Access
92,Cefradine,Cefradine,775112000,Cefradine 500mg powder for solution for inject...,41944711000001108,P,None,Watch,Access
93,Cefradine,Cefradine,775112000,Cefradine 250mg/5ml oral solution,36134511000001102,O,None,Watch,Access
94,Ceftaroline fosamil,Ceftaroline fosamil,21387311000001104,Ceftaroline fosamil 600mg powder for solution ...,21386911000001101,P,None,Reserve,Reserve
95,Ceftazidime,Ceftazidime,775115003,Ceftazidime 2mg/0.1ml solution for injection p...,40558111000001101,None,None,Watch,Watch
96,Ceftazidime,Ceftazidime,775115003,Ceftazidime 1g/50ml solution for infusion pre-...,22455011000001109,P,None,Watch,Watch
97,Ceftazidime,Ceftazidime,775115003,Ceftazidime 1g/50ml infusion bags,22097911000001104,P,None,Watch,Watch
98,Ceftazidime,Ceftazidime,775115003,Ceftazidime 1g/25ml solution for infusion pre-...,22098511000001105,P,None,Watch,Watch
99,Ceftazidime,Ceftazidime,775115003,Ceftazidime 2g intravenous infusion vials,323856006,P,None,Watch,Watch
100,Ceftazidime,Ceftazidime,775115003,Ceftazidime 1g powder for solution for injecti...,41944811000001100,P,None,Watch,Watch
101,Ceftazidime,Ceftazidime,775115003,Ceftazidime 250mg powder for solution for inje...,41944911000001105,P,None,Watch,Watch
102,Ceftazidime,Ceftazidime,775115003,Ceftazidime 500mg powder for solution for inje...,41945211000001100,P,None,Watch,Watch
103,Ceftazidime,Ceftazidime,775115003,Ceftazidime 2g powder for solution for injecti...,41945011000001105,P,None,Watch,Watch
104,Ceftazidime,Ceftazidime,775115003,Ceftazidime 3g powder for solution for injecti...,41945111000001106,P,None,Watch,Watch
105,Ceftazidime + Avibactam,Ceftazidime + Avibactam,781300005,Ceftazidime 2g / Avibactam 500mg powder for so...,34179911000001103,P,None,Reserve,Reserve
106,Ceftobiprole,Ceftobiprole,1287090001,Ceftobiprole 500mg powder for solution for inf...,31008911000001103,P,None,Reserve,Reserve
107,Ceftolozane + Tazobactam,Ceftolozane + Tazobactam,775119009,Ceftolozane 1g / Tazobactam 500mg powder for s...,31007811000001109,P,None,Reserve,Reserve
108,Ceftriaxone,Ceftriaxone,775120003,Ceftriaxone 2g powder for solution for infusio...,23107411000001109,P,None,Watch,Watch
109,Ceftriaxone,Ceftriaxone,775120003,Ceftriaxone 1g/50ml infusion bags,22102411000001102,P,None,Watch,Watch
110,Ceftriaxone,Ceftriaxone,775120003,Ceftriaxone 1g powder for solution for injecti...,41945311000001108,P,None,Watch,Watch
111,Ceftriaxone,Ceftriaxone,775120003,Ceftriaxone 250mg powder for solution for inje...,41945511000001102,P,None,Watch,Watch
112,Ceftriaxone,Ceftriaxone,775120003,Ceftriaxone 2g powder for solution for injecti...,41945611000001103,P,None,Watch,Watch
113,Cefuroxime,Cefuroxime,775121004,Cefuroxime 3mg/0.3ml solution for injection pr...,30791311000001104,None,None,Watch,Watch
114,Cefuroxime,Cefuroxime,775121004,Cefuroxime 1.5g/50ml infusion bags,35893011000001107,P,None,Watch,Watch
115,Cefuroxime,Cefuroxime,775121004,Cefuroxime 750mg/50ml infusion bags,35893111000001108,P,None,Watch,Watch
116,Cefuroxime,Cefuroxime,775121004,Cefuroxime 1.5g/100ml infusion bags,23683311000001109,P,None,Watch,Watch
117,Cefuroxime,Cefuroxime,775121004,Cefuroxime 300micrograms/0.3ml solution for in...,22104011000001100,None,None,Watch,Watch
118,Cefuroxime,Cefuroxime,775121004,Cefuroxime 1mg/0.1ml solution for injection pr...,22041211000001105,None,None,Watch,Watch
119,Cefuroxime,Cefuroxime,775121004,Cefuroxime 50mg powder for solution for inject...,21797311000001102,None,None,Watch,Watch
120,Cefuroxime,Cefuroxime,775121004,Cefuroxime 125mg/5ml oral suspension,41945811000001104,O,None,Watch,Watch
121,Cefuroxime,Cefuroxime,775121004,Cefuroxime 250mg tablets,39694611000001101,O,None,Watch,Watch
122,Cefuroxime,Cefuroxime,775121004,Cefuroxime 125mg tablets,39684511000001101,O,None,Watch,Watch
123,Cefuroxime,Cefuroxime,775121004,Cefuroxime 125mg granules for oral suspension ...,41945711000001107,O,None,Watch,Watch
124,Cefuroxime,Cefuroxime,775121004,Cefuroxime 750mg powder for solution for injec...,36134711000001107,P,None,Watch,Watch
125,Cefuroxime,Cefuroxime,775121004,Cefuroxime 1.5g powder for solution for inject...,4557611000001106,P,None,Watch,Watch
126,Cefuroxime,Cefuroxime,775121004,Cefuroxime 250mg powder for solution for injec...,41945911000001109,P,None,Watch,Watch
127,Chloramphenicol,Chloramphenicol,775160002,Chloramphenicol 250mg capsules,41946111000001100,O,None,Watch,Watch
128,Chloramphenicol,Chloramphenicol,775160002,Chloramphenicol 1g powder for solution for inj...,41946011000001101,P,None,Watch,Watch
129,Cilastatin + Imipenem + Relebactam,Cilastatin + Imipenem + Relebactam,789074009,Generic Recarbrio 500mg/500mg/250mg powder for...,38840011000001101,P,None,Reserve,Reserve
130,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 100mg tablets,39686211000001109,O,None,Watch,Watch
131,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 250mg tablets,39687511000001109,O,None,Watch,Watch
132,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 500mg tablets,39687811000001107,O,None,Watch,Watch
133,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 750mg tablets,39687011000001101,O,None,Watch,Watch
134,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 400mg/200ml infusion bags,36141511000001100,P,None,Watch,Watch
135,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 200mg/100ml infusion bags,36141011000001108,P,None,Watch,Watch
136,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 100mg/50ml solution for infusion...,36140911000001100,P,None,Watch,Watch
137,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 250mg/5ml oral suspension,41760211000001107,O,None,Watch,Watch
138,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 200mg/100ml solution for infusio...,8967411000001108,P,None,Watch,Watch
139,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 400mg/200ml solution for infusio...,8973011000001101,P,None,Watch,Watch
140,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 100mg/50ml solution for infusion...,10892711000001106,P,None,Watch,Watch
141,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 200mg/100ml solution for infusio...,10892811000001103,P,None,Watch,Watch
142,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 400mg/200ml solution for infusio...,10892911000001108,P,None,Watch,Watch
143,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 45mg/5ml oral suspension,12020411000001104,O,None,Watch,Watch
144,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 500mg/5ml oral suspension,12020511000001100,O,None,Watch,Watch
145,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 50mg/5ml oral suspension,12020611000001101,O,None,Watch,Watch
146,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 60mg/5ml oral suspension,12020711000001105,O,None,Watch,Watch
147,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 75mg/5ml oral suspension,12020811000001102,O,None,Watch,Watch
148,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 80mg/5ml oral suspension,12020911000001107,O,None,Watch,Watch
149,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 100mg/5ml oral suspension,12019511000001104,O,None,Watch,Watch
150,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 125mg/5ml oral suspension,12019611000001100,O,None,Watch,Watch
151,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 150mg/5ml oral suspension,12019711000001109,O,None,Watch,Watch
152,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 165mg/5ml oral suspension,12019811000001101,O,None,Watch,Watch
153,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 170mg/5ml oral suspension,12019911000001106,O,None,Watch,Watch
154,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 175mg/5ml oral suspension,12020011000001108,O,None,Watch,Watch
155,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 20mg/5ml oral suspension,12020111000001109,O,None,Watch,Watch
156,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 375mg/5ml oral suspension,12020211000001103,O,None,Watch,Watch
157,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 40mg/5ml oral suspension,12020311000001106,O,None,Watch,Watch
158,Clarithromycin,Clarithromycin,775277005,Clarithromycin 500mg/250ml infusion bags,22390311000001100,P,None,Watch,Watch
159,Clarithromycin,Clarithromycin,775277005,Clarithromycin 500mg tablets,41946511000001109,O,None,Watch,Watch
160,Clarithromycin,Clarithromycin,775277005,Clarithromycin 250mg tablets,41946311000001103,O,None,Watch,Watch
161,Clarithromycin,Clarithromycin,775277005,Clarithromycin 500mg modified-release tablets,36142611000001107,O,None,Watch,Watch
162,Clarithromycin,Clarithromycin,775277005,Clarithromycin 125mg/5ml oral suspension,35368711000001104,O,None,Watch,Watch
163,Clarithromycin,Clarithromycin,775277005,Clarithromycin 250mg/5ml oral suspension,37083211000001101,O,None,Watch,Watch
164,Clarithromycin,Clarithromycin,775277005,Clarithromycin 500mg powder for solution for i...,41946411000001105,P,None,Watch,Watch
165,Clarithromycin,Clarithromycin,775277005,Clarithromycin 250mg granules for oral suspens...,41946211000001106,O,None,Watch,Watch

In [23]:
vmps_matched.to_csv('data/vtm_method.csv', index=False)

<a id='s2'></a>
## Section 2: Processing and Comparing AWaRe Excel Data
This section loads and analyses the AWaRe Excel data provided by UKHSA. It compares the content with the previously generated VTM-based method and highlights any discrepancies.

### Getting the AWaRe list
The AWaRe list has been provided by the UKHSA team as an Excel spreadsheet. We can save the Excel spreadsheet as a CSV file then read into Pandas.

In [24]:
excel_path = os.path.join('..', 'data', 'AWaRe_UK_2024_translation_table_FINAL_UPDATED_20250429.xlsx')
df_ukhsa = pd.read_excel(excel_path)
df_ukhsa

,dmd,Antibiotic,Class,atccode,route,VmpUnit,WHO_AWaRe_2023,UK_AWaRe_2024,Include,Notes
0,Amikacin 100mg/2ml solution for injection vials,Amikacin,Aminoglycosides,J01GB06,P,ml,a,w,1,NaN
1,Amikacin 1165mg/100ml solution for injection v...,Amikacin,Aminoglycosides,J01GB06,P,ml,a,w,1,NaN
2,Amikacin 1200mg solution for injection vials,Amikacin,Aminoglycosides,J01GB06,P,ml,a,w,1,NaN
3,Amikacin 1300mg/50ml solution for injection vials,Amikacin,Aminoglycosides,J01GB06,P,ml,a,w,1,NaN
4,Amikacin 250mg/2ml injection,Amikacin,Aminoglycosides,J01GB06,P,ml,a,w,1,NaN
...,...,...,...,...,...,...,...,...,...,...
926,Vancomycin 50mg/5ml oral solution,Vancomycin_oral,Glycopeptides,A07AA09,O,ml,w,w,1,NaN
927,Vancomycin 5mg/0.5ml solution for injection pr...,Vancomycin_IV,Glycopeptides,J01XA01,P,ml,w,w,1,NaN
928,Vancomycin 62.5mg/5ml oral solution,Vancomycin_oral,Glycopeptides,A07AA09,O,ml,w,w,1,NaN
929,Vancomycin 750mg/250ml infusion bags,Vancomycin_IV,Glycopeptides,J01XA01,P,ml,w,w,1,NaN
930,Vancomycin 850mg powder for solution for infus...,Vancomycin_IV,Glycopeptides,J01XA01,P,vial,w,w,1,NaN

Extract data for VMPs from dm+d tables held in BigQuery

In [25]:
# Construct the query using the formatted list.
sql = f"""
SELECT DISTINCT
  vmp.id AS vmp_id,
  vmp.nm AS vmp_nm,
  vmp.invalid AS invalid_vmp,
  vtm.id AS vtm_id,
  vtm.nm AS vtm_nm,
  COALESCE(sroute.route, routelookup.who_route) AS atc_route,
  atclookup.ATC AS atc
FROM `ebmdatalab.dmd.vmp` vmp
LEFT JOIN dmd.ont ont ON vmp.id = ont.vmp
LEFT JOIN dmd.vtm vtm ON vmp.vtm = vtm.id
LEFT JOIN dmd.ontformroute ofr ON ont.form = ofr.cd
LEFT JOIN `dmd.vpi_to_atc_and_ddd` atclookup ON vmp.id = atclookup.VPID
LEFT JOIN chris.vmp_single_route_identifier sroute ON vmp.id = sroute.vmp_id -- this table maps VMP to a specific route where more than one is given
LEFT JOIN `scmd_dmd_views.dmd_to_atc_route` routelookup ON ofr.descr = routelookup.dmd_ofr  -- this table maps dmd route to ATC route
"""

# Define the CSV path for caching the results.
csv_path = os.path.join('..', 'data', 'vmp_vtms.csv')

# Use the cached_read function from the bq library to run the query.
vmp_vtms = bq.cached_read(sql, csv_path=csv_path)

# Force vmp_id and vtm_id to proper string type
vmp_vtms['vmp_id'] = vmp_vtms['vmp_id'].astype('string')
vmp_vtms['vtm_id'] = vmp_vtms['vtm_id'].astype('string')

In [26]:
vmp_vtms

,vmp_id,vmp_nm,invalid_vmp,vtm_id,vtm_nm,atc_route,atc
0,45010811000001105,Lazertinib 80mg tablets,False,4.49914110000011e+16,Lazertinib,O,NaN
1,44117211000001108,Generic DryMax Super dressing 5cm x 5cm square,False,<NA>,NaN,NaN,NaN
2,42801911000001108,Catheter safety valves,False,<NA>,NaN,NaN,NaN
3,41960011000001106,Copper coated barrier dressing sterile with ad...,False,<NA>,NaN,NaN,NaN
4,41535211000001108,Odevixibat 600microgram capsules,False,1179275005.0,Odevixibat,O,A05AX05
...,...,...,...,...,...,...,...
24698,43907811000001106,Somapacitan 10mg/1.5ml solution for injection ...,False,898161005.0,Somapacitan,P,NaN
24699,43907911000001101,Somapacitan 15mg/1.5ml solution for injection ...,False,898161005.0,Somapacitan,P,NaN
24700,44098211000001102,Budesonide 1mg/2ml nebuliser suspension unit d...,False,774924004.0,Budesonide,Inhal.solution,NaN
24701,43813811000001108,Generic PDE reach5 oral powder 18g sachets,False,<NA>,NaN,O,NaN
24702,43907711000001103,Generic Spikevax JN.1 COVID-19 mRNA Vaccine 50...,False,3.93307110000011e+16,COVID-19 vaccine,P,NaN

Attempt to match VMPs to UKHSA table

In [27]:
# Ensure IDs are strings before merging
vmp_vtms['vmp_id'] = vmp_vtms['vmp_id'].astype('string')
vmp_vtms['vtm_id'] = vmp_vtms['vtm_id'].astype('string')

# Add lower-case name columns for matching
df_ukhsa['dmd_lower'] = df_ukhsa['dmd'].str.lower()
vmp_vtms['vmp_nm_lower'] = vmp_vtms['vmp_nm'].str.lower()

# Merge on lower-case names
ukhsa_original_matched = (
    df_ukhsa.merge(
        vmp_vtms,
        left_on='dmd_lower',
        right_on='vmp_nm_lower',
        how='left'
    )
    .drop(columns=['dmd_lower', 'vmp_nm_lower'])
)

ukhsa_original_matched

,dmd,Antibiotic,Class,atccode,route,VmpUnit,WHO_AWaRe_2023,UK_AWaRe_2024,Include,Notes,vmp_id,vmp_nm,invalid_vmp,vtm_id,vtm_nm,atc_route,atc
0,Amikacin 100mg/2ml solution for injection vials,Amikacin,Aminoglycosides,J01GB06,P,ml,a,w,1,NaN,35899811000001104,Amikacin 100mg/2ml solution for injection vials,False,774534000.0,Amikacin,P,J01GB06
1,Amikacin 1165mg/100ml solution for injection v...,Amikacin,Aminoglycosides,J01GB06,P,ml,a,w,1,NaN,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN
2,Amikacin 1200mg solution for injection vials,Amikacin,Aminoglycosides,J01GB06,P,ml,a,w,1,NaN,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN
3,Amikacin 1300mg/50ml solution for injection vials,Amikacin,Aminoglycosides,J01GB06,P,ml,a,w,1,NaN,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN
4,Amikacin 250mg/2ml injection,Amikacin,Aminoglycosides,J01GB06,P,ml,a,w,1,NaN,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
943,Vancomycin 50mg/5ml oral solution,Vancomycin_oral,Glycopeptides,A07AA09,O,ml,w,w,1,NaN,12940811000001109,Vancomycin 50mg/5ml oral solution,False,777914002.0,Vancomycin,O,A07AA09
944,Vancomycin 5mg/0.5ml solution for injection pr...,Vancomycin_IV,Glycopeptides,J01XA01,P,ml,w,w,1,NaN,21278311000001101,Vancomycin 5mg/0.5ml solution for injection pr...,False,777914002.0,Vancomycin,NaN,J01XA01
945,Vancomycin 62.5mg/5ml oral solution,Vancomycin_oral,Glycopeptides,A07AA09,O,ml,w,w,1,NaN,13455811000001106,Vancomycin 62.5mg/5ml oral solution,False,777914002.0,Vancomycin,O,A07AA09
946,Vancomycin 750mg/250ml infusion bags,Vancomycin_IV,Glycopeptides,J01XA01,P,ml,w,w,1,NaN,35051211000001109,Vancomycin 750mg/250ml infusion bags,False,777914002.0,Vancomycin,P,J01XA01
947,Vancomycin 850mg powder for solution for infus...,Vancomycin_IV,Glycopeptides,J01XA01,P,vial,w,w,1,NaN,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN

In [28]:
ukhsa_original_matched.to_csv("ukhsa_original_matched.csv")

In [29]:
ukhsa_original_matched_analysis=ukhsa_original_matched

In [30]:
no_vmp_id_count = ukhsa_original_matched_analysis[ukhsa_original_matched_analysis['vmp_id'].isna() | (ukhsa_original_matched_analysis['vmp_id'] == 0)].shape[0]
print(f"Rows without a matched vmp_id: {no_vmp_id_count}")

Rows without a matched vmp_id: 186

In [31]:
# Filter rows where vmp_id is NA or 0
rows_without_vmpid = ukhsa_original_matched_analysis[
    ukhsa_original_matched_analysis['vmp_id'].isna() | 
    (ukhsa_original_matched_analysis['vmp_id'] == 0)
]

with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
    display(rows_without_vmpid[['dmd', 'Antibiotic', 'Include']])

,dmd,Antibiotic,Include
1,Amikacin 1165mg/100ml solution for injection vials,Amikacin,1
2,Amikacin 1200mg solution for injection vials,Amikacin,1
3,Amikacin 1300mg/50ml solution for injection vials,Amikacin,1
4,Amikacin 250mg/2ml injection,Amikacin,1
39,Aztreonam 3g powder for solution for injection vials,Aztreonam,1
48,Benzathine benzylpenicillin 600000unit powder and solvent for suspension for injection vials,Benzathine-benzylpenicillin,1
49,Benzathine benzylpenicllin 900mg injection,Benzathine-benzylpenicillin,1
50,Benzylpenicillin 1.2g powder for solution for injection vials,Benzylpenicillin,1
51,Benzylpenicillin 1.2g/50ml infusion bags,Benzylpenicillin,1
52,Benzylpenicillin 2.4g/100ml infusion bags,Benzylpenicillin,1
53,Benzylpenicillin 600mg powder for solution for injection vials,Benzylpenicillin,1
54,Benzylpenicillin 600mg/50ml infusion bags,Benzylpenicillin,1
80,Cefalotin,Cefalotin,1
109,Ceftazidime 1.09g/50ml solution for infusion pre-filled injection devices,Ceftazidime,1
110,Ceftazidime 1.2g powder for solution for injection vials,Ceftazidime,1
111,Ceftazidime 1.46g powder for solution for injection vials,Ceftazidime,1
112,Ceftazidime 1.5g powder for solution for injection vials,Ceftazidime,1
113,Ceftazidime 1.65g/50ml solution for infusion pre-filled injection devices,Ceftazidime,1
114,Ceftazidime 1.77g powder for solution for injection vials,Ceftazidime,1
115,Ceftazidime 1.7g powder for solution for injection vials,Ceftazidime,1
116,Ceftazidime 1.875g powder for solution for injection vials,Ceftazidime,1
117,Ceftazidime 1.8g powder for solution for injection vials,Ceftazidime,1
118,Ceftazidime 1.8g/30ml solution for infusion pre-filled injection devices,Ceftazidime,1
119,Ceftazidime 1.9g powder for solution for injection vials,Ceftazidime,1
124,Ceftazidime 2.2g/50ml solution for infusion pre-filled injection devices,Ceftazidime,1
125,Ceftazidime 2.5g powder for solution for injection vials,Ceftazidime,1
126,Ceftazidime 2.9g intravenous infusion vials,Ceftazidime,1
132,Ceftazidime 2g/50ml solution for infusion pre-filled injection devices,Ceftazidime,1
133,Ceftazidime 3.1g intravenous infusion vials,Ceftazidime,1
134,Ceftazidime 3.22g intravenous infusion vials,Ceftazidime,1
135,Ceftazidime 3.36g intravenous infusion vials,Ceftazidime,1
136,Ceftazidime 3.3g intravenous infusion vials,Ceftazidime,1
137,Ceftazidime 3.5g powder for solution for injection vials,Ceftazidime,1
138,Ceftazidime 3.6g powder for solution for injection vials,Ceftazidime,1
139,Ceftazidime 3.75g intravenous infusion vials,Ceftazidime,1
140,Ceftazidime 3.7g intravenous infusion vials,Ceftazidime,1
141,Ceftazidime 3.9g powder for solution for injection vials,Ceftazidime,1
142,Ceftazidime 3000mg/250ml for infusion pre-filled injection devices,Ceftazidime,1
144,Ceftazidime 3g/250ml solution for infusion pre-filled injection devices,Ceftazidime,1
145,Ceftazidime 3g/50ml solution for infusion pre-filled injection devices,Ceftazidime,1
146,Ceftazidime 4000mg/250ml for infusion pre-filled injection devices,Ceftazidime,1
147,Ceftazidime 4g powder for solution for injection vials,Ceftazidime,1
148,Ceftazidime 4mg/0.2ml solution for infusion pre-filled syringes,Ceftazidime,1
150,Ceftazidime 6000mg/250ml for infusion pre-filled injection devices,Ceftazidime,1
151,Ceftazidime 620mg/50ml solution for infusion pre-filled injection devices,Ceftazidime,1
152,Ceftazidime 6g powder for solution for injection vials,Ceftazidime,1
158,Ceftriaxone 2.8g powder for solution for infusion vials,Ceftriaxone,1
162,Ceftriaxone 2g/100ml infusion bags,Ceftriaxone,1
163,Ceftriaxone 3g powder for solution for infusion vials,Ceftriaxone,1
164,Cefuroxime 1.5g powder for injection vials,Cefuroxime,1
168,Cefuroxime 125mg granules sachets,Cefuroxime,1
172,Cefuroxime 200micrograms/0.2ml solution for injection pre-filled syringes,Cefuroxime,1
173,Cefuroxime 250mg powder for injection vials,Cefuroxime,1
176,Cefuroxime 2mg/0.2ml solution for injection pre-filled syringes,Cefuroxime,1
178,Cefuroxime 3mg in 0.3ml solution for injection pre-filled syringes,Cefuroxime,1
181,Cefuroxime 750mg powder for injection vials,Cefuroxime,1
202,Ciprofloxacin 390mg/50ml solution for injection vials,Ciprofloxacin,1
206,Ciprofloxacin 400mg/50ml solution for injection vials,Ciprofloxacin,1
214,Clarithromycin 125mg granules sachets,Clarithromycin,1
215,Clarithromycin 125mg granules straws,Clarithromycin,1
217,Clarithromycin 187.5mg granules straws,Clarithromycin,1
219,Clarithromycin 250mg granules sachets,Clarithromycin,1
220,Clarithromycin 250mg granules straws,Clarithromycin,1
228,Clindamycin 100mg/5ml suspension,Clindamycin,1
241,Clindamycin 50mg in 5ml sugar-free suspension,Clindamycin,1
269,Colistimethate (colomycin) (nebulisation only) vial 1million units inj,Colistin_INH,1
271,Colistimethate 1.2million unit powder for solution for injection vials,Colistin_IV,1
272,Colistimethate 1.5million unit powder for solution for injection vials,Colistin_IV,1
273,Colistimethate 125mg capsules for inhalation,Colistin_INH,1
274,Colistimethate 1662500 units inhalation powder capsules,Colistin_INH,1
286,Colistin 2million unit powder vials,Colistin_IV,1
290,Co-trimoxazole 40mg/200mg/5ml oral suspension,Sulfamethoxazole/trimethoprim,1
306,Demeclocycline 300mg capsule,Demeclocycline,0
310,Demeclocycline 50mg/5ml suspension,Demeclocycline,0
315,Doxycycline 100mg dispersible tablets,Doxycycline,1
317,Doxycycline 100mg injection,Doxycycline,1
329,Erythromycin 0.02 solution,Erythromycin,1
340,Erythromycin lactobionate 1g injection,Erythromycin,1
351,Ethambutol 240mg/5ml oral solution,Ethambutol,0
372,Flucloxacillin 125mg/5ml oral elixir,Flucloxacillin,1
373,Flucloxacillin 125mg/5ml oral elixir/suspension,Flucloxacillin,1
385,Flucloxacillin 250mg/5ml oral elixir/suspension,Flucloxacillin,1
389,Flucloxacillin 2g in 100ml,Flucloxacillin,1
390,Flucloxacillin 2g in sodium chloride 0.9% infusion 100ml,Flucloxacillin,1
393,Flucloxacillin 4g in nacl + buffer (17.4mg/ml) infusion,Flucloxacillin,1
399,Flucloxacillin 8000mg/250ml Infusion bags,Flucloxacillin,1
400,Flucloxacillin 8000mg/250ml infusion bags,Flucloxacillin,1
401,Flucloxacillin 8g in nacl + buffer (17.4mg/ml) infusion,Flucloxacillin,1
402,Flucloxacillin in sodium chloride 0.9% 240ml 8000mg elastometric pump (24hr),Flucloxacillin,1
408,Fosfomycin 3g granules sachets,Fosfomycin_oral,1
474,Isoniazid 300mg/5ml Injection,Isoniazid,0
475,Isoniazid 300mg/5ml injection,Isoniazid,0
502,Levofloxacin 5mg in 1ml intravenous infusion,Levofloxacin,1
504,Linezolid 2mg in 1ml intravenous infusion,Linezolid,1
506,Linezolid 600mg/300ml infusion,Linezolid,1
510,Meropenem 1.6g powder for solution for injection vials,Meropenem,1
515,Meropenem 530mg powder for solution for injection vials,Meropenem,1
516,Meropenem 560mg powder for solution for injection vials,Meropenem,1
517,Meropenem 570mg powder for solution for injection vials,Meropenem,1
522,Metronidazole 125mg suppositories,Metronidazole,1
530,Metronidazole 500mg/100ml infusion 100ml,Metronidazole_IV,1
543,Moxifloxacin 100mg in 5ml suspension,Moxifloxacin,1
544,Moxifloxacin 100mg/1ml oral solution,Moxifloxacin,1
545,Moxifloxacin 200mg in 5ml suspension,Moxifloxacin,1
550,Moxifloxacin 500mg in 5ml liquid,Moxifloxacin,1
557,Neomycin Sulf_Tab 500mg,Neomycin,0
662,Penicillin combinations,Penicillin combinations,1
663,Penicillin combinations,Penicillin combinations,1
670,Piperacillin,Piperacillin,1
672,Piperacillin 2g / tazobactam 250mg powder for solution for injection vials,Piperacillin/tazobactam,1
675,Piperacillin 4g / tazobactam 500mg in 50ml sodium chloride,Piperacillin/tazobactam,1
676,Piperacillin 4g / tazobactam 500mg powder and solvent for solution for infusion vials,Piperacillin/tazobactam,1
677,Piperacillin 4g / tazobactam 500mg powder and solvent for solution for injection,Piperacillin/tazobactam,1
681,Piperacillin 4g / tazobactam 500mg powder for solution for injection vials,Piperacillin/tazobactam,1
682,Piperacillin 8g / Tazobactam 1g powder and solvent for solution for injection vials,Piperacillin/tazobactam,1
683,Piperacillin 8g / tazobactam 1g powder and solvent for solution for injection vials,Piperacillin/tazobactam,1
684,Piperacillin with tazobactam 12g/1.5g in 24 hours pre-filled infusion,Piperacillin/tazobactam,1
685,Piperacillin with tazobactam 8g/1g in 24 hours pre-filled infusion,Piperacillin/tazobactam,1
686,Pipericillin 12g / tazobactam 1.5g in sodium chloride 0.9% elastometric pump (24hr),Piperacillin/tazobactam,1
692,Procaine benzylpenicillin 1.2mu injection,Procaine-benzylpenicillin,1
694,Procaine benzylpenicillin 600000unit powder and solvent for suspension for injection vials,Procaine-benzylpenicillin,1
765,Rifampicin 120mg/ isoniazid 50mg/ pyrazinamide 300mg (rifater tablets),Rifampicin/isoniazid/pyrazinamide,0
776,Rifampicin 225mg/5ml oral suspension,Rifampicin,0
777,Rifampicin 240mg/5ml oral suspension,Rifampicin,0
785,Rifampicin 375mg/5ml oral suspension,Rifampicin,0
793,"Spiramycin 1,500,000 units tablets",Spiramycin,0
795,Spiramycin 375000units/5ml oral solution,Spiramycin,0
828,Ticarcillin 3g / clavulanic acid 100mg powder for solution for infusion vials,Ticarcillin/clavulanic-acid,1
831,Tigecycline 50mg injection,Tigecycline,1
833,Timentin 3.1g injection,Ticarcillin/clavulanic-acid,1
834,Timentin 3.2g injection,Ticarcillin/clavulanic-acid,1
835,Tinidazole 500mg film coated tablet,Tinidazole,0
837,Tobramycin 1.2 g injection,Tobramycin,1
839,Tobramycin 145mg solution for injection vials,Tobramycin,1
840,Tobramycin 160mg solution for injection vials,Tobramycin,1
842,Tobramycin 190mg solution for injection vials,Tobramycin,1
843,Tobramycin 200mg solution for injection vials,Tobramycin,1
847,Tobramycin 210mg solution for injection vials,Tobramycin,1
848,Tobramycin 220mg/100ml solution for injection vials,Tobramycin,1
849,Tobramycin 227mg solution for injection vials,Tobramycin,1
850,Tobramycin 230mg/100ml solution for injection vials,Tobramycin,1
851,Tobramycin 240mg solution for injection vials,Tobramycin,1
852,Tobramycin 240mg/100ml solution for injection vials,Tobramycin,1
854,Tobramycin 250mg solution for injection vials,Tobramycin,1
855,Tobramycin 256mg solution for injection vials,Tobramycin,1
856,Tobramycin 260mg solution for injection vials,Tobramycin,1
857,Tobramycin 272mg solution for injection vials,Tobramycin,1
858,Tobramycin 280mg/100ml solution for injection vials,Tobramycin,1
860,Tobramycin 290mg solution for injection vials,Tobramycin,1
861,Tobramycin 300mg/100ml solution for injection vials,Tobramycin,1
864,Tobramycin 310mg solution for injection vials,Tobramycin,1
865,Tobramycin 318mg solution for injection vials,Tobramycin,1
866,Tobramycin 332mg solution for injection vials,Tobramycin,1
867,Tobramycin 350mg solution for injection vials,Tobramycin,1
868,Tobramycin 360mg/100ml solution for injection vials,Tobramycin,1
869,Tobramycin 370mg/100ml solution for injection vials,Tobramycin,1
870,Tobramycin 375mg solution for injection vials,Tobramycin,1
871,Tobramycin 380mg/100ml solution for injection vials,Tobramycin,1
876,Tobramycin 420mg solution for injection vials,Tobramycin,1
877,Tobramycin 440mg solution for injection vials,Tobramycin,1
878,Tobramycin 444mg solution for injection vials,Tobramycin,1
879,Tobramycin 450mg/100ml solution for injection vials,Tobramycin,1
880,Tobramycin 470mg/100ml solution for injection vials,Tobramycin,1
881,Tobramycin 480mg solution for injection vials,Tobramycin,1
882,Tobramycin 490mg solution for injection vials,Tobramycin,1
883,Tobramycin 500mg/100ml solution for injection vials,Tobramycin,1
884,Tobramycin 510mg/100ml solution for injection vials,Tobramycin,1
885,Tobramycin 520mg solution for injection vials,Tobramycin,1
886,Tobramycin 530mg solution for injection vials,Tobramycin,1
887,Tobramycin 536mg solution for injection vials,Tobramycin,1
890,Tobramycin 84mg solution for injection vials,Tobramycin,1
900,Trimethoprim 50mg/5ml oral suspension,Trimethoprim,1
905,Vancomycin 1.5g/30ml solution for injection pre-filled syringes,Vancomycin_IV,1
908,Vancomycin 1.5mg powder for solution for infusion vials,Vancomycin_IV,1
909,Vancomycin 1000mg/250ml infusion bags,Vancomycin_IV,1
912,Vancomycin 1250mg/250ml infusion bags,Vancomycin_IV,1
914,Vancomycin 125mg in glucose 5% 30ml (syringe),Vancomycin_IV,1
917,Vancomycin 1500mg/500ml infusion bags,Vancomycin_IV,1
928,Vancomycin 2g powder for solution for infusion vials,Vancomycin_IV,1
929,Vancomycin 2g/40ml solution for injection pre-filled syringes,Vancomycin_IV,1
933,Vancomycin 3mg/0.3ml solution for injection pre-filled syringes,Vancomycin_IV,1
935,Vancomycin 500mg injection ( for oral use only),Vancomycin_oral,1
936,Vancomycin 500mg injection (for oral use only),Vancomycin_oral,1
940,Vancomycin 500mg/250ml infusion bags,Vancomycin_IV,1
942,Vancomycin 50mg/1ml oral solution,Vancomycin_oral,1
947,Vancomycin 850mg powder for solution for infusion vials,Vancomycin_IV,1

From a manual review these are the rows from the above which have potential matches - but may not have matched above due to variations in wording used.

In [32]:

selected_ids = [
    48, 49, 50, 51, 53, 54, 164, 173, 178, 181, 228, 241, 269, 286, 290,
    306, 310, 315, 317, 340, 372, 373, 385, 389, 390, 408, 474, 475, 502,
    504, 506, 530, 672, 676, 677, 681, 692, 694, 765, 793, 831, 835, 851,
    900, 909, 912, 917, 935, 936
]

# Filter rows_without_vmpid using those index numbers
selected_rows = rows_without_vmpid.loc[rows_without_vmpid.index.isin(selected_ids)]

# Display the selected rows with full column width
with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
    display(selected_rows[['dmd', 'Antibiotic', 'Include']])

,dmd,Antibiotic,Include
48,Benzathine benzylpenicillin 600000unit powder and solvent for suspension for injection vials,Benzathine-benzylpenicillin,1
49,Benzathine benzylpenicllin 900mg injection,Benzathine-benzylpenicillin,1
50,Benzylpenicillin 1.2g powder for solution for injection vials,Benzylpenicillin,1
51,Benzylpenicillin 1.2g/50ml infusion bags,Benzylpenicillin,1
53,Benzylpenicillin 600mg powder for solution for injection vials,Benzylpenicillin,1
54,Benzylpenicillin 600mg/50ml infusion bags,Benzylpenicillin,1
164,Cefuroxime 1.5g powder for injection vials,Cefuroxime,1
173,Cefuroxime 250mg powder for injection vials,Cefuroxime,1
178,Cefuroxime 3mg in 0.3ml solution for injection pre-filled syringes,Cefuroxime,1
181,Cefuroxime 750mg powder for injection vials,Cefuroxime,1
228,Clindamycin 100mg/5ml suspension,Clindamycin,1
241,Clindamycin 50mg in 5ml sugar-free suspension,Clindamycin,1
269,Colistimethate (colomycin) (nebulisation only) vial 1million units inj,Colistin_INH,1
286,Colistin 2million unit powder vials,Colistin_IV,1
290,Co-trimoxazole 40mg/200mg/5ml oral suspension,Sulfamethoxazole/trimethoprim,1
306,Demeclocycline 300mg capsule,Demeclocycline,0
310,Demeclocycline 50mg/5ml suspension,Demeclocycline,0
315,Doxycycline 100mg dispersible tablets,Doxycycline,1
317,Doxycycline 100mg injection,Doxycycline,1
340,Erythromycin lactobionate 1g injection,Erythromycin,1
372,Flucloxacillin 125mg/5ml oral elixir,Flucloxacillin,1
373,Flucloxacillin 125mg/5ml oral elixir/suspension,Flucloxacillin,1
385,Flucloxacillin 250mg/5ml oral elixir/suspension,Flucloxacillin,1
389,Flucloxacillin 2g in 100ml,Flucloxacillin,1
390,Flucloxacillin 2g in sodium chloride 0.9% infusion 100ml,Flucloxacillin,1
408,Fosfomycin 3g granules sachets,Fosfomycin_oral,1
474,Isoniazid 300mg/5ml Injection,Isoniazid,0
475,Isoniazid 300mg/5ml injection,Isoniazid,0
502,Levofloxacin 5mg in 1ml intravenous infusion,Levofloxacin,1
504,Linezolid 2mg in 1ml intravenous infusion,Linezolid,1
506,Linezolid 600mg/300ml infusion,Linezolid,1
530,Metronidazole 500mg/100ml infusion 100ml,Metronidazole_IV,1
672,Piperacillin 2g / tazobactam 250mg powder for solution for injection vials,Piperacillin/tazobactam,1
676,Piperacillin 4g / tazobactam 500mg powder and solvent for solution for infusion vials,Piperacillin/tazobactam,1
677,Piperacillin 4g / tazobactam 500mg powder and solvent for solution for injection,Piperacillin/tazobactam,1
681,Piperacillin 4g / tazobactam 500mg powder for solution for injection vials,Piperacillin/tazobactam,1
692,Procaine benzylpenicillin 1.2mu injection,Procaine-benzylpenicillin,1
694,Procaine benzylpenicillin 600000unit powder and solvent for suspension for injection vials,Procaine-benzylpenicillin,1
765,Rifampicin 120mg/ isoniazid 50mg/ pyrazinamide 300mg (rifater tablets),Rifampicin/isoniazid/pyrazinamide,0
793,"Spiramycin 1,500,000 units tablets",Spiramycin,0
831,Tigecycline 50mg injection,Tigecycline,1
835,Tinidazole 500mg film coated tablet,Tinidazole,0
851,Tobramycin 240mg solution for injection vials,Tobramycin,1
900,Trimethoprim 50mg/5ml oral suspension,Trimethoprim,1
909,Vancomycin 1000mg/250ml infusion bags,Vancomycin_IV,1
912,Vancomycin 1250mg/250ml infusion bags,Vancomycin_IV,1
917,Vancomycin 1500mg/500ml infusion bags,Vancomycin_IV,1
935,Vancomycin 500mg injection ( for oral use only),Vancomycin_oral,1
936,Vancomycin 500mg injection (for oral use only),Vancomycin_oral,1

Matching all products under a specific VTM may give a more systematic approach to creating/updating this list in dm+d. We can check for how many match to a VMP but miss a VTM ID.

In [33]:
no_vtm_id_count = ukhsa_original_matched_analysis[
    (ukhsa_original_matched_analysis['vmp_id'].notna()) &
    (ukhsa_original_matched_analysis['vmp_id'] != 0) &
    (ukhsa_original_matched_analysis['vtm_id'].isna())
].shape[0]

print(f"Rows with a vmp_id but missing vtm_id: {no_vtm_id_count}")

Rows with a vmp_id but missing vtm_id: 3

In [34]:

# Filter rows where vmp_id is present but vtm_id is missing
filtered_rows = ukhsa_original_matched_analysis[
    (ukhsa_original_matched_analysis['vmp_id'].notna()) &
    (ukhsa_original_matched_analysis['vmp_id'] != 0) &
    (ukhsa_original_matched_analysis['vtm_id'].isna())
]

# Display the filtered rows
filtered_rows

,dmd,Antibiotic,Class,atccode,route,VmpUnit,WHO_AWaRe_2023,UK_AWaRe_2024,Include,Notes,vmp_id,vmp_nm,invalid_vmp,vtm_id,vtm_nm,atc_route,atc
371,Flucloxacillin 125mg / 5ml oral solution sugar...,Flucloxacillin,Penicillins,J01CF05,O,ml,a,a,1,NaN,7526011000001106,Flucloxacillin 125mg / 5ml oral solution sugar...,True,<NA>,NaN,O,NaN
413,Generic deteclo 300mg tablets,Chlortetracycline hydrochloride/demeclocycline...,Tetracyclines,J01AA20,O,tablet,o,o,0,"excl, discontinued in UK since 2007",34819711000001101,Generic Deteclo 300mg tablets,False,<NA>,NaN,O,J01AA20
415,Generic voractiv tablets,Ethambutol hydrochloride/isoniazid/pyrazinamid...,Antimycobacterials,J04AM06,O,tablet,o,o,0,anti-TB,21733111000001101,Generic Voractiv tablets,False,<NA>,NaN,O,J04AM06

Of these results, "Flucloxacillin 125mg / 5ml oral solution sugar free" is an invalid VMP in dm+d so can be disregareded. The other 2 products are combination treatments for TB and are excluded from the AWaRe list.

In [35]:
grouped_vtm_include = ukhsa_original_matched_analysis.groupby(['vtm_nm', 'Include'], dropna=False).size().reset_index(name='count')

# Display the selected rows with full column width
with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
    display(grouped_vtm_include)

                                 vtm_nm  Include  count
0                              Amikacin        1      5
1                    Amikacin liposomal        1      1
2                           Amoxicillin        1     14
3                            Ampicillin        1      6
4                          Azithromycin        1      6
5                             Aztreonam        1      5
6                 Aztreonam + Avibactam        1      1
7                           Bedaquiline        0      1
8           Benzathine benzylpenicillin        1      4
9                      Benzylpenicillin        1      4
10                          Capreomycin        0      1
11                             Cefaclor        1      7
12                           Cefadroxil        1      4
13                            Cefalexin        1      9
14                          Cefamandole        1      1
15                            Cefazolin        1      3
16                             Cefepime        1      2
17                          Cefiderocol        1      1
18                             Cefixime        1      3
19                           Cefotaxime        1      3
20                            Cefoxitin        1      2
21                            Cefpirome        1      2
22                          Cefpodoxime        1      2
23                            Cefprozil        1      3
24                            Cefradine        1      5
25                  Ceftaroline fosamil        1      1
26                          Ceftazidime        1      9
27              Ceftazidime + Avibactam        1      2
28                         Ceftobiprole        1      1
29             Ceftolozane + Tazobactam        1      2
30                          Ceftriaxone        1      5
31                           Cefuroxime        1     13
32                      Chloramphenicol        1      2
33   Cilastatin + Imipenem + Relebactam        1      1
34                        Ciprofloxacin        1     26
35                       Clarithromycin        1      8
36                          Clindamycin        1     20
37                          Clofazimine        0      2
38                         Co-amoxiclav        1     15
39                        Co-fluampicil        1      3
40                       Co-trimoxazole        1      6
41                             Colistin        0      5
42                             Colistin        1      8
43                          Cycloserine        0      1
44                          Dalbavancin        1      1
45                           Daptomycin        1      2
46                         Delafloxacin        1      2
47                            Delamanid        0      1
48                       Demeclocycline        0      9
49                            Doripenem        1      1
50                          Doxycycline        0      1
51                          Doxycycline        1     10
52                         Eravacycline        1      1
53                            Ertapenem        1      1
54                         Erythromycin        1      2
55         Erythromycin ethyl succinate        1      7
56            Erythromycin lactobionate        1      1
57                Erythromycin stearate        1      2
58                           Ethambutol        0     25
59                          Fidaxomicin        1      2
60                       Flucloxacillin        1     22
61                           Fosfomycin        1      7
62                         Fusidic acid        1      1
63                           Gentamicin        0      5
64                           Gentamicin        1     20
65                Imipenem + Cilastatin        1      4
66                            Isoniazid        0     47
67                         Levofloxacin        1      8
68                            Linezolid        1      4
69                          Lymecycline        1      1
70                            Meropenem        1      3
71              Meropenem + Vaborbactam        1      1
72                          Methenamine        1      1
73                        Metronidazole        1     14
74                          Minocycline        1      7
75                         Moxifloxacin        1      5
76                       Nalidixic acid        1      3
77                             Neomycin        0      3
78                           Netilmicin        1      5
79                       Nitrofurantoin        1     86
80                          Norfloxacin        1      1
81                            Ofloxacin        1      9
82                          Oritavancin        1      1
83                      Oxytetracycline        1      2
84              Phenoxymethylpenicillin        1      6
85            Piperacillin + Tazobactam        1      6
86                        Pivmecillinam        1      2
87                        Pristinamycin        1      2
88            Procaine benzylpenicillin        1      2
89                         Pyrazinamide        0     67
90          Quinupristin + Dalfopristin        1      2
91                           Rifampicin        0     19
92               Rifampicin + Isoniazid        0      2
93                        Roxithromycin        1      1
94                      Sodium fusidate        1      2
95                        Spectinomycin        0      1
96                           Spiramycin        0      2
97                         Streptomycin        1      1
98                         Sulfadiazine        1      5
99               Sulfamethoxypyridazine        1      1
100                       Sulfapyridine        1      1
101                           Tedizolid        1      2
102                         Teicoplanin        1     14
103                          Telavancin        0      2
104                       Telithromycin        0      1
105                          Temocillin        1      1
106                        Tetracycline        1      3
107       Ticarcillin + Clavulanic acid        1      2
108                         Tigecycline        1      1
109                          Tinidazole        0      1
110                          Tobramycin        0      5
111                          Tobramycin        1     10
112                        Trimethoprim        1     12
113                          Vancomycin        1     30
114                                 NaN        0     15
115                                 NaN        1    174

In this list only 1 VTM has rows considered both included and excluded.

In [36]:
tobramycin_rows = ukhsa_original_matched_analysis[
    ukhsa_original_matched_analysis['vtm_nm'] == 'Tobramycin'
]

tobramycin_rows

,dmd,Antibiotic,Class,atccode,route,VmpUnit,WHO_AWaRe_2023,UK_AWaRe_2024,Include,Notes,vmp_id,vmp_nm,invalid_vmp,vtm_id,vtm_nm,atc_route,atc
838,Tobramycin 135mg/5ml oral solution,Tobramycin,Aminoglycosides,J01GB01,O,ml,w,w,0,no WHO DDD,21718511000001106,Tobramycin 135mg/5ml oral solution,False,777791002.0,Tobramycin,O,NaN
841,Tobramycin 170mg/1.7ml nebuliser liquid ampoules,Tobramycin,Aminoglycosides,J01GB01,INH,ml,w,w,1,NaN,32936811000001108,Tobramycin 170mg/1.7ml nebuliser liquid ampoules,False,777791002.0,Tobramycin,Inhal.solution,J01GB01
844,Tobramycin 200mg/5ml oral solution,Tobramycin,Aminoglycosides,J01GB01,O,ml,w,w,0,no WHO DDD,35084911000001108,Tobramycin 200mg/5ml oral solution,False,777791002.0,Tobramycin,O,NaN
845,Tobramycin 20mg/2ml solution for injection vials,Tobramycin,Aminoglycosides,J01GB01,P,ml,w,w,1,NaN,34194211000001103,Tobramycin 20mg/2ml solution for injection vials,False,777791002.0,Tobramycin,P,J01GB01
846,Tobramycin 20mg/5ml oral solution,Tobramycin,Aminoglycosides,J01GB01,O,ml,w,w,0,no WHO DDD,23676411000001103,Tobramycin 20mg/5ml oral solution,False,777791002.0,Tobramycin,O,J01GB01
853,Tobramycin 240mg/6ml solution for injection vials,Tobramycin,Aminoglycosides,J01GB01,P,ml,w,w,1,NaN,4516011000001106,Tobramycin 240mg/6ml solution for injection vials,False,777791002.0,Tobramycin,P,J01GB01
859,Tobramycin 28mg inhalation powder capsules wit...,Tobramycin,Aminoglycosides,J01GB01,INH,capsule,w,w,1,NaN,19544811000001101,Tobramycin 28mg inhalation powder capsules wit...,False,777791002.0,Tobramycin,Inhal.powder,J01GB01
862,Tobramycin 300mg/4ml nebuliser liquid ampoules,Tobramycin,Aminoglycosides,J01GB01,INH,ml,w,w,1,NaN,14801411000001105,Tobramycin 300mg/4ml nebuliser liquid ampoules,False,777791002.0,Tobramycin,Inhal.solution,J01GB01
863,Tobramycin 300mg/5ml nebuliser liquid ampoules,Tobramycin,Aminoglycosides,J01GB01,INH,ml,w,w,1,NaN,4145111000001102,Tobramycin 300mg/5ml nebuliser liquid ampoules,False,777791002.0,Tobramycin,Inhal.solution,J01GB01
872,Tobramycin 400mg/5ml oral solution,Tobramycin,Aminoglycosides,J01GB01,O,ml,w,w,0,no WHO DDD,21717911000001100,Tobramycin 400mg/5ml oral solution,False,777791002.0,Tobramycin,O,NaN
873,Tobramycin 40mg/1ml solution for injection amp...,Tobramycin,Aminoglycosides,J01GB01,P,ml,w,w,1,NaN,35919711000001100,Tobramycin 40mg/1ml solution for injection amp...,False,777791002.0,Tobramycin,P,J01GB01
874,Tobramycin 40mg/1ml solution for injection vials,Tobramycin,Aminoglycosides,J01GB01,P,ml,w,w,1,NaN,4957911000001108,Tobramycin 40mg/1ml solution for injection vials,False,777791002.0,Tobramycin,P,J01GB01
875,Tobramycin 40mg/5ml oral solution,Tobramycin,Aminoglycosides,J01GB01,O,ml,w,w,0,no WHO DDD,32656811000001108,Tobramycin 40mg/5ml oral solution,False,777791002.0,Tobramycin,O,NaN
888,Tobramycin 80mg/2ml solution for infusion ampo...,Tobramycin,Aminoglycosides,J01GB01,P,ml,w,w,1,NaN,35919811000001108,Tobramycin 80mg/2ml solution for infusion ampo...,False,777791002.0,Tobramycin,P,J01GB01
889,Tobramycin 80mg/2ml solution for injection vials,Tobramycin,Aminoglycosides,J01GB01,P,ml,w,w,1,NaN,4145011000001103,Tobramycin 80mg/2ml solution for injection vials,False,777791002.0,Tobramycin,P,J01GB01

Looking at the rows we can see oral tobramycin has been excluded as there is no WHO DDD. We will keep in for now but in later code can exclude any VMPs without a DDD if needed.

<a id='s3'></a>
## Section 3: Validate dm+d list/SQL method

We have generated a list of VMPs by matching VTMs to UKHSA descriptions published online. We want to compare the results of this with the provided data.

In [37]:
vtm_method = pd.read_csv("vtm_method.csv", dtype={'vmp_id': 'string', 'vtm_id': 'string'})
vtm_method

,Antibiotic,vtm_nm,vtm_id,vmp_nm,vmp_id,vmp_atc_route,atc_route,aware_2019,aware_2024
0,Amikacin,Amikacin,774534000,Amikacin 500mg/2ml solution for injection ampo...,44422511000001103,P,NaN,Watch,Watch
1,Amikacin,Amikacin,774534000,Amikacin 25mg/5ml solution for injection ampoules,44007311000001107,NaN,NaN,Watch,Watch
2,Amikacin,Amikacin,774534000,Amikacin 500mg/100ml infusion polyethylene bot...,41823511000001108,P,NaN,Watch,Watch
3,Amikacin,Amikacin,774534000,Amikacin 400micrograms/0.1ml intravitreal inje...,38244211000001108,NaN,NaN,Watch,Watch
4,Amikacin,Amikacin,774534000,Amikacin 25mg/5ml solution for injection vials,35111911000001104,NaN,NaN,Watch,Watch
...,...,...,...,...,...,...,...,...,...
591,Vancomycin,Vancomycin,777914002,Vancomycin 250mg/5ml oral suspension,8818711000001109,O,NaN,Watch,Watch
592,Vancomycin,Vancomycin,777914002,Vancomycin 50mg/5ml oral solution,12940811000001109,O,NaN,Watch,Watch
593,Vancomycin,Vancomycin,777914002,Vancomycin 62.5mg/5ml oral solution,13455811000001106,O,NaN,Watch,Watch
594,Vancomycin,Vancomycin,777914002,Vancomycin 125mg/5ml oral solution,15453011000001107,O,NaN,Watch,Watch
595,Vancomycin,Vancomycin,777914002,Vancomycin 125mg/5ml oral suspension,15453111000001108,O,NaN,Watch,Watch

The VTM/VMP methodology should allow us to accurately identify all appropriate VMPs assuming we have a matching list of VTMs.  

We can compare the list of VTMs in our methodology against the list of VTMs in the UKHSA list to ensure we have identified the list correctly.

In [38]:
ukhsa_original_matched_analysis_VTM = ukhsa_original_matched

Firstly get a list of unique VTMs in the UKHSA list where Include = 1 - i.e. where they are considered as part of the AWaRe categorisation.

In [39]:
# Step 1: Get full unique VTM rows with AWaRe columns where Include == 1
ukhsa_unique_vtm_aware_included = ukhsa_original_matched_analysis.loc[
    ukhsa_original_matched_analysis['Include'] == 1,
    ['vtm_nm', 'route', 'WHO_AWaRe_2023', 'UK_AWaRe_2024']
].dropna(subset=['vtm_nm']).drop_duplicates()

# Step 2: Extract just the vtm_nm column without duplicates
ukhsa_unique_vtm_included = ukhsa_unique_vtm_aware_included['vtm_nm'].drop_duplicates()
ukhsa_unique_vtm_included

0                           Amikacin
9                 Amikacin liposomal
10                       Amoxicillin
24                        Ampicillin
30                      Azithromycin
                   ...
829    Ticarcillin + Clavulanic acid
832                      Tigecycline
841                       Tobramycin
891                     Trimethoprim
904                       Vancomycin
Name: vtm_nm, Length: 93, dtype: object

Get a list of unique VTMs from the VTM method list.

In [40]:
vtm_method_unique_vtm = vtm_method.loc[:, 'vtm_nm'].dropna().drop_duplicates()
vtm_method_unique_vtm

0                Amikacin
8      Amikacin liposomal
9             Amoxicillin
24             Ampicillin
30           Azithromycin
              ...
536           Tigecycline
537            Tinidazole
538            Tobramycin
553          Trimethoprim
565            Vancomycin
Name: vtm_nm, Length: 91, dtype: object

The UKHSA provided dataset has 93 unique VTMs. Our generated VTM list only contains 91. We can find the discrepancies.

In [41]:
# Start with full UKHSA DataFrame (including AWaRe columns)
ukhsa_df = ukhsa_unique_vtm_aware_included[['vtm_nm', 'WHO_AWaRe_2023', 'UK_AWaRe_2024']]

# Convert vtm_method list to DataFrame
vtm_method_df = pd.DataFrame({'vtm_nm': vtm_method_unique_vtm})

# Merge with indicator
merged_vtm = pd.merge(
    ukhsa_df,
    vtm_method_df,
    on='vtm_nm',
    how='outer',
    indicator=True
)

# Rename categories of the _merge column
merged_vtm['_merge'] = merged_vtm['_merge'].cat.rename_categories({
    'left_only': 'ukhsa_provided_only',
    'right_only': 'vtm_method_only',
    'both': 'both'
})

# Filter out matches if you only want differences
vtm_differences = merged_vtm[merged_vtm['_merge'] != 'both']

# Sort by source
vtm_differences = vtm_differences.sort_values(by='_merge')

# Result: vtm_differences includes AWaRe columns where available
vtm_differences.drop_duplicates()

,vtm_nm,WHO_AWaRe_2023,UK_AWaRe_2024,_merge
24,Cefpirome,w,r,ukhsa_provided_only
25,Cefpodoxime,w,w,ukhsa_provided_only
26,Cefprozil,w,w,ukhsa_provided_only
48,Co-fluampicil,NR,o,ukhsa_provided_only
91,Nalidixic acid,o,o,ukhsa_provided_only
122,Ticarcillin + Clavulanic acid,o,o,ukhsa_provided_only
93,Netilmicin,w,o,ukhsa_provided_only
106,Roxithromycin,w,o,ukhsa_provided_only
107,Sodium fusidate,w,w,ukhsa_provided_only
19,Cefepime + Enmetazobactam,NaN,NaN,vtm_method_only
119,Telavancin,NaN,NaN,vtm_method_only
110,Spiramycin,NaN,NaN,vtm_method_only
92,Neomycin,NaN,NaN,vtm_method_only
58,Demeclocycline,NaN,NaN,vtm_method_only
109,Spectinomycin,NaN,NaN,vtm_method_only
124,Tinidazole,NaN,NaN,vtm_method_only

Reviewing the results above.  
**ukhsa_provided_only**
- Cefpirome, cefpodoxime, cefprozil, nalidixic acid, ticarcillin + clavulanic acid, netilmicin, roxithromycin - not listed on AWaRe list on UKHSA website. All appear either not in use or rarely used.
- Co-fluampicil - we have this in the VTM method list under ampicillin + flucloxacillin - it's unclear why there are 2 seperate VTMs for apparently the same thing but possibly in part due to neither VTM having an active VMP. We can classify both with the category 'Other'.
- Sodium fusidate is covered by fusidic acid listed in the original - we need to add the specific VTM sodium fusidate.

**vtm_method_only**
- Cefepime + Enmetazobactam	- has been identified due to cefepime component.
- Telavancin, tinidazole, neomycin - all listed in the online UKHSA list
- Spiramycin, demeclocycline, spectinomycin - listed in the online UKHSA list under 'Other'

<a id='s4'></a>
## Section 4: Extend/refine the SQL/VTM method
This section expands the SQL logic in section 1 to add in the additional VTMs identified in section 3.

Get the original list of VTMs and extend with the additional VTMS identified in section 3.

In [42]:
vtm_match_cleaned = pd.read_csv("vtm_match_clean.csv")

# Step 1: Define manually added unique rows with full AWaRe labels
vtm_manual_additions = [
    {'Antibiotic': 'Cefpirome', 'aware_2019': 'Watch', 'aware_2024': 'Reserve'},
    {'Antibiotic': 'Cefpodoxime', 'aware_2019': 'Watch', 'aware_2024': 'Watch'},
    {'Antibiotic': 'Cefprozil', 'aware_2019': 'Watch', 'aware_2024': 'Watch'},
    {'Antibiotic': 'Co-fluampicil', 'aware_2019': 'Other', 'aware_2024': 'Other'},
    {'Antibiotic': 'Nalidixic acid', 'aware_2019': 'Other', 'aware_2024': 'Other'},
    {'Antibiotic': 'Ticarcillin + Clavulanic acid', 'aware_2019': 'Other', 'aware_2024': 'Other'},
    {'Antibiotic': 'Netilmicin', 'aware_2019': 'Watch', 'aware_2024': 'Other'},
    {'Antibiotic': 'Roxithromycin', 'aware_2019': 'Watch', 'aware_2024': 'Other'},
    {'Antibiotic': 'Sodium fusidate', 'aware_2019': 'Watch', 'aware_2024': 'Watch'},
    {'Antibiotic': 'Cefepime + Enmetazobactam', 'aware_2019': '?', 'aware_2024': '?'}
]

# Step 2: Convert to DataFrame
vtm_manual_additions = pd.DataFrame(vtm_manual_additions)

# Step 3: Add required columns to match vtm_match_cleaned
vtm_manual_additions['nm'] = vtm_manual_additions['Antibiotic']
vtm_manual_additions['id'] = pd.NA
vtm_manual_additions['atc_route'] = pd.NA

# Step 4: Reorder columns
vtm_manual_additions = vtm_manual_additions[vtm_match_cleaned.columns]

# Step 5: Concatenate and assign to a new cleaned version
vtm_clean_extended = pd.concat([vtm_match_cleaned, vtm_manual_additions], ignore_index=True)

# Set Ampicillin + Flucloxacillin category to match Co-fluampicil
vtm_clean_extended.loc[
    vtm_clean_extended['Antibiotic'] == 'Ampicillin + Flucloxacillin',
    ['aware_2019', 'aware_2024']
] = 'Other'

vtm_clean_extended

/tmp/ipykernel_419/1384974639.py:29: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  vtm_clean_extended = pd.concat([vtm_match_cleaned, vtm_manual_additions], ignore_index=True)

,Antibiotic,nm,id,atc_route,aware_2019,aware_2024
0,Amikacin,Amikacin liposomal,782421008.0,NaN,Watch,Watch
1,Amikacin,Amikacin,774534000.0,NaN,Watch,Watch
2,Amoxicillin,Amoxicillin,774586009.0,NaN,Access,Access
3,Ampicillin,Ampicillin + Flucloxacillin,774592003.0,NaN,Access,Access
4,Ampicillin,Ampicillin,774590006.0,NaN,Access,Access
...,...,...,...,...,...,...
129,Ticarcillin + Clavulanic acid,Ticarcillin + Clavulanic acid,NaN,NaN,Other,Other
130,Netilmicin,Netilmicin,NaN,NaN,Watch,Other
131,Roxithromycin,Roxithromycin,NaN,NaN,Watch,Other
132,Sodium fusidate,Sodium fusidate,NaN,NaN,Watch,Watch
133,Cefepime + Enmetazobactam,Cefepime + Enmetazobactam,NaN,NaN,?,?

We can upload the resulting table to BigQuery as table 'chris.aware_list_extended'

We can adjust our VTM_method SQL query to match this new list

In [43]:
sql = f"""
WITH matched_vtms AS ( -- This query does the fuzzy matching of Antibiotic name to VTM name
  SELECT  
    aware.Antibiotic,
    aware.atc_route,
    aware.aware_2019,
    aware.aware_2024,
    vtm.nm,
    vtm.id,
    CASE
      WHEN aware.Antibiotic = vtm.nm THEN 'DIRECT'
      ELSE 'ASSUMED'
    END AS match_type
  FROM `ebmdatalab.chris.aware_list_extended` aware
  LEFT JOIN `ebmdatalab.dmd.vtm` vtm 
    ON vtm.nm LIKE CONCAT('%', aware.Antibiotic, '%')
  WHERE vtm.invalid IS NOT TRUE
),

duplicate_vtms AS ( -- This produces a list of duplicate rows where a direct match already exists
  SELECT *
  FROM matched_vtms
  WHERE nm IN (
    SELECT nm
    FROM matched_vtms
    WHERE atc_route IS NULL
    GROUP BY nm
    HAVING COUNT(*) > 1
  )
  AND match_type = 'ASSUMED'
),

vmp_with_route AS (
  SELECT DISTINCT
    vmp.id AS id,
    vmp.vtm AS vtm,
    vmp.nm AS nm,
    COALESCE(sroute.route, routelookup.who_route) AS vmp_atc_route
  FROM `ebmdatalab.dmd.vmp` vmp
  LEFT JOIN dmd.ont ont ON vmp.id = ont.vmp
  LEFT JOIN dmd.ontformroute ofr ON ont.form = ofr.cd
  LEFT JOIN chris.vmp_single_route_identifier sroute ON vmp.id = sroute.vmp_id
  LEFT JOIN `scmd_dmd_views.dmd_to_atc_route` routelookup ON ofr.descr = routelookup.dmd_ofr
  WHERE ofr.descr NOT LIKE '%.auricular'
  AND ofr.descr NOT LIKE '%.cutaneous'
  AND ofr.descr NOT LIKE '%.ophthalmic'
  AND ofr.descr NOT LIKE '%.oromucosal'
  AND ofr.descr NOT LIKE '%.intralesional'
  AND ofr.descr NOT LIKE '%.nasal'
)

SELECT DISTINCT
  matched_vtms.Antibiotic,
  matched_vtms.nm as vtm_nm,
  matched_vtms.id as vtm_id,
  vmp.nm as vmp_nm,
  vmp.id as vmp_id,
  vmp.vmp_atc_route,
  matched_vtms.atc_route,
  matched_vtms.aware_2019,
  matched_vtms.aware_2024
FROM matched_vtms
LEFT JOIN vmp_with_route vmp
  ON matched_vtms.id = vmp.vtm
  AND (
    matched_vtms.atc_route IS NULL
    OR matched_vtms.atc_route = vmp.vmp_atc_route
  )
WHERE NOT EXISTS ( -- removes the duplicates identified above
  SELECT 1
  FROM duplicate_vtms
  WHERE matched_vtms.Antibiotic = duplicate_vtms.Antibiotic AND matched_vtms.nm = duplicate_vtms.nm
) AND vmp.id IS NOT NULL
ORDER BY matched_vtms.Antibiotic ASC;
"""

# Define the CSV path for caching the results.
csv_path = os.path.join('..', 'data', 'vmps_matched_extended.csv')

# Use the cached_read function from the bq library to run the query.
vmps_matched_extended = bq.cached_read(sql, csv_path=csv_path)

# Force vmp_id and vtm_id to proper string type
vmps_matched_extended['vmp_id'] = vmps_matched_extended['vmp_id'].astype('string')
vmps_matched_extended['vtm_id'] = vmps_matched_extended['vtm_id'].astype('string')

display(vmps_matched_extended)

,Antibiotic,vtm_nm,vtm_id,vmp_nm,vmp_id,vmp_atc_route,atc_route,aware_2019,aware_2024
0,Amikacin,Amikacin liposomal,782421008,Amikacin liposomal 590mg nebuliser dispersion ...,39601711000001109,Inhal.solution,NaN,Watch,Watch
1,Amikacin,Amikacin,774534000,Amikacin 500mg/2ml solution for injection ampo...,44422511000001103,P,NaN,Watch,Watch
2,Amikacin,Amikacin,774534000,Amikacin 25mg/5ml solution for injection ampoules,44007311000001107,NaN,NaN,Watch,Watch
3,Amikacin,Amikacin,774534000,Amikacin 500mg/100ml infusion polyethylene bot...,41823511000001108,P,NaN,Watch,Watch
4,Amikacin,Amikacin,774534000,Amikacin 400micrograms/0.1ml intravitreal inje...,38244211000001108,NaN,NaN,Watch,Watch
...,...,...,...,...,...,...,...,...,...
613,Vancomycin,Vancomycin,777914002,Vancomycin 250mg/5ml oral suspension,8818711000001109,O,NaN,Watch,Watch
614,Vancomycin,Vancomycin,777914002,Vancomycin 50mg/5ml oral solution,12940811000001109,O,NaN,Watch,Watch
615,Vancomycin,Vancomycin,777914002,Vancomycin 62.5mg/5ml oral solution,13455811000001106,O,NaN,Watch,Watch
616,Vancomycin,Vancomycin,777914002,Vancomycin 125mg/5ml oral solution,15453011000001107,O,NaN,Watch,Watch
617,Vancomycin,Vancomycin,777914002,Vancomycin 125mg/5ml oral suspension,15453111000001108,O,NaN,Watch,Watch

### Comparing VMPs

We now have a list of VMPs from the VTM method. We can compare these against the UKHSA supplied list to ensure we capture everything.

In [44]:
vmps_matched_extended[['vmp_id', 'vmp_nm', 'aware_2024']]

,vmp_id,vmp_nm,aware_2024
0,39601711000001109,Amikacin liposomal 590mg nebuliser dispersion ...,Watch
1,44422511000001103,Amikacin 500mg/2ml solution for injection ampo...,Watch
2,44007311000001107,Amikacin 25mg/5ml solution for injection ampoules,Watch
3,41823511000001108,Amikacin 500mg/100ml infusion polyethylene bot...,Watch
4,38244211000001108,Amikacin 400micrograms/0.1ml intravitreal inje...,Watch
...,...,...,...
613,8818711000001109,Vancomycin 250mg/5ml oral suspension,Watch
614,12940811000001109,Vancomycin 50mg/5ml oral solution,Watch
615,13455811000001106,Vancomycin 62.5mg/5ml oral solution,Watch
616,15453011000001107,Vancomycin 125mg/5ml oral solution,Watch
617,15453111000001108,Vancomycin 125mg/5ml oral suspension,Watch

In [45]:
ukhsa_filtered = ukhsa_original_matched_analysis[
    (ukhsa_original_matched_analysis['vmp_id'] != 0) &
    (ukhsa_original_matched_analysis['Include'] == 1)
][['vmp_id', 'vmp_nm', 'UK_AWaRe_2024']]
ukhsa_filtered

,vmp_id,vmp_nm,UK_AWaRe_2024
0,35899811000001104,Amikacin 100mg/2ml solution for injection vials,w
5,35111911000001104,Amikacin 25mg/5ml solution for injection vials,w
6,41823511000001108,Amikacin 500mg/100ml infusion polyethylene bot...,w
7,35899911000001109,Amikacin 500mg/2ml solution for injection vials,w
8,44422511000001103,Amikacin 500mg/2ml solution for injection ampo...,w
...,...,...,...
941,35049111000001102,Vancomycin 50mg/10ml solution for injection pr...,w
943,12940811000001109,Vancomycin 50mg/5ml oral solution,w
944,21278311000001101,Vancomycin 5mg/0.5ml solution for injection pr...,w
945,13455811000001106,Vancomycin 62.5mg/5ml oral solution,w
946,35051211000001109,Vancomycin 750mg/250ml infusion bags,w

In [46]:
# Step 1: Rename columns for consistency
ukhsa_df = ukhsa_filtered.rename(columns={'UK_AWaRe_2024': 'ukhsa_aware_2024'})
vmps_df = vmps_matched_extended.rename(columns={'aware_2024': 'vmps_aware_2024'})

# Step 2: Perform outer merge on vmp_id only
merged_vmps = pd.merge(
    ukhsa_df,
    vmps_df,
    on='vmp_id',
    how='outer',
    indicator=True
)

# Step 3: Label the source of each row
merged_vmps['_merge'] = merged_vmps['_merge'].replace({
    'left_only': 'ukhsa_list_only',
    'right_only': 'vtm_method_ext_only',
    'both': 'both'
})

/tmp/ipykernel_419/189286236.py:15: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  merged_vmps['_merge'] = merged_vmps['_merge'].replace({

In [47]:
merged_vmps_differences = merged_vmps[merged_vmps['_merge'] != 'both']
merged_vmps_differences = merged_vmps_differences.sort_values(by='_merge')

In [48]:
with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
    display(merged_vmps_differences)

,vmp_id,vmp_nm_x,ukhsa_aware_2024,Antibiotic,vtm_nm,vtm_id,vmp_nm_y,vmp_atc_route,atc_route,aware_2019,vmps_aware_2024,_merge
241,32936911000001103,Colistimethate 2million unit powder for nebuliser solution unit dose vials,r,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,ukhsa_list_only
645,7526011000001106,Flucloxacillin 125mg / 5ml oral solution sugar free,a,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,ukhsa_list_only
195,22399111000001107,Vancomycin 20mg pastilles,w,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,ukhsa_list_only
203,22555311000001104,"Colistimethate 1,662,500unit inhalation powder capsules",r,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,ukhsa_list_only
607,4256011000001107,Colistimethate 1million unit powder for nebuliser solution unit dose vials,r,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,ukhsa_list_only
1,10150911000001107,NaN,NaN,Benzathine benzylpenicillin,Benzathine benzylpenicillin,1234764000,"Benzathine benzylpenicillin 600,000unit powder and solvent for suspension for injection vials",P,NaN,Access,Access,vtm_method_ext_only
429,41882411000001108,NaN,NaN,Telavancin,Telavancin,777693006,Telavancin 750mg powder for solution for infusion vials,P,NaN,Reserve,Reserve,vtm_method_ext_only
428,41882311000001101,NaN,NaN,Telavancin,Telavancin,777693006,Telavancin 250mg powder for solution for infusion vials,P,NaN,Reserve,Reserve,vtm_method_ext_only
416,41742911000001107,NaN,NaN,Metronidazole,Metronidazole,776774005,Metronidazole 25% oromucosal gel sugar free,NaN,NaN,Access,Access,vtm_method_ext_only
415,41742711000001105,NaN,NaN,Metronidazole,Metronidazole,776774005,Metronidazole 0.75% vaginal gel,V,NaN,Access,Access,vtm_method_ext_only
407,40558111000001101,NaN,NaN,Ceftazidime,Ceftazidime,775115003,Ceftazidime 2mg/0.1ml solution for injection pre-filled syringes,NaN,NaN,Watch,Watch,vtm_method_ext_only
480,41945711000001107,NaN,NaN,Cefuroxime,Cefuroxime,775121004,Cefuroxime 125mg granules for oral suspension sachets,O,NaN,Watch,Watch,vtm_method_ext_only
406,40548411000001108,NaN,NaN,Vancomycin,Vancomycin,777914002,Vancomycin 500micrograms/0.1ml solution for injection pre-filled syringes,NaN,NaN,Watch,Watch,vtm_method_ext_only
405,40529511000001103,NaN,NaN,Vancomycin,Vancomycin,777914002,Vancomycin 2mg/0.1ml intravitreal injection kit,NaN,NaN,Watch,Watch,vtm_method_ext_only
389,39707811000001100,NaN,NaN,Colistin,Colistin,775373006,Colistin 1.5million unit tablets,O,O,Reserve,Reserve,vtm_method_ext_only
381,39700011000001105,NaN,NaN,Clindamycin,Clindamycin,775288004,Clindamycin 2% vaginal cream,V,NaN,Watch,Watch,vtm_method_ext_only
341,38244211000001108,NaN,NaN,Amikacin,Amikacin,774534000,Amikacin 400micrograms/0.1ml intravitreal injection kit,NaN,NaN,Watch,Watch,vtm_method_ext_only
309,36091411000001104,NaN,NaN,Colistin,Colistin,775373006,"Colistin 250,000units/5ml oral solution",O,O,Reserve,Reserve,vtm_method_ext_only
411,41109011000001101,NaN,NaN,Co-amoxiclav,Co-amoxiclav,774587000,Co-amoxiclav 2000mg/200mg powder for solution for infusion vials,P,NaN,Watch,Watch,vtm_method_ext_only
497,41948011000001102,NaN,NaN,Demeclocycline,Demeclocycline,775476004,Demeclocycline 150mg capsules,O,NaN,Watch,Other,vtm_method_ext_only
498,41948111000001101,NaN,NaN,Demeclocycline,Demeclocycline,775476004,Demeclocycline 150mg tablets,O,NaN,Watch,Other,vtm_method_ext_only
561,41952611000001105,NaN,NaN,Neomycin,Neomycin,776885003,Neomycin 125mg/5ml oral solution,O,NaN,Watch,Watch,vtm_method_ext_only
660,9742311000001103,NaN,NaN,Clarithromycin,Clarithromycin,775277005,Clarithromycin 125mg granules for oral suspension straws,O,NaN,Watch,Watch,vtm_method_ext_only
652,8523611000001103,NaN,NaN,Gentamicin,Gentamicin,776094005,Gentamicin 50mg/5ml oral solution,O,NaN,Access,Access,vtm_method_ext_only
641,4977911000001105,NaN,NaN,Clarithromycin,Clarithromycin,775277005,Clarithromycin 125mg granules for oral suspension sachets,O,NaN,Watch,Watch,vtm_method_ext_only
627,44947711000001105,NaN,NaN,Meropenem,Meropenem,776694006,Meropenem 500mg powder and 50ml solvent infusion bags,P,NaN,Reserve,Reserve,vtm_method_ext_only
626,44947611000001101,NaN,NaN,Meropenem,Meropenem,776694006,Meropenem 1g powder and 50ml solvent infusion bags,P,NaN,Reserve,Reserve,vtm_method_ext_only
624,44456411000001100,NaN,NaN,Amoxicillin,Amoxicillin,774586009,Amoxicillin 500mg tablets,O,NaN,Access,Access,vtm_method_ext_only
620,44100011000001102,NaN,NaN,Teicoplanin,Teicoplanin,777691008,Teicoplanin 200mg/50ml infusion bags,P,NaN,Watch,Watch,vtm_method_ext_only
619,44028111000001104,NaN,NaN,Gentamicin,Gentamicin,776094005,Gentamicin 240mg/6ml solution for injection pre-filled syringes,P,NaN,Access,Access,vtm_method_ext_only
618,44009011000001100,NaN,NaN,Cefotaxime,Cefotaxime,775103002,Cefotaxime 1g/50ml infusion bags,P,NaN,Watch,Watch,vtm_method_ext_only
617,44007911000001108,NaN,NaN,Cefotaxime,Cefotaxime,775103002,Cefotaxime 2g/100ml infusion bags,P,NaN,Watch,Watch,vtm_method_ext_only
616,44007311000001107,NaN,NaN,Amikacin,Amikacin,774534000,Amikacin 25mg/5ml solution for injection ampoules,NaN,NaN,Watch,Watch,vtm_method_ext_only
609,42894511000001102,NaN,NaN,Cefepime,Cefepime + Enmetazobactam,42894211000001100,Cefepime 2g / Enmetazobactam 500mg powder for solution for infusion vials,P,NaN,Watch,Watch,vtm_method_ext_only
605,41978311000001100,NaN,NaN,Nitrofurantoin,Nitrofurantoin,776927008,Nitrofurantoin 50mg/5ml oral suspension sugar free,O,NaN,Access,Access,vtm_method_ext_only
591,41956011000001104,NaN,NaN,Tinidazole,Tinidazole,777775000,Tinidazole 500mg tablets,O,NaN,Other,Access,vtm_method_ext_only
562,41952711000001101,NaN,NaN,Neomycin,Neomycin,776885003,Neomycin 500mg tablets,O,NaN,Watch,Watch,vtm_method_ext_only
276,35900311000001105,NaN,NaN,Spiramycin,Spiramycin,777602007,"Spiramycin 375,000units/5ml oral solution",O,NaN,Other,Other,vtm_method_ext_only
264,35104511000001105,NaN,NaN,Amikacin,Amikacin,774534000,Amikacin 25mg/5ml solution for injection pre-filled syringes,NaN,NaN,Watch,Watch,vtm_method_ext_only
255,35030211000001102,NaN,NaN,Colistin,Colistin,775373006,"Colistin 2,500,000units/5ml oral solution",O,O,Reserve,Reserve,vtm_method_ext_only
661,9742411000001105,NaN,NaN,Clarithromycin,Clarithromycin,775277005,Clarithromycin 187.5mg granules for oral suspension straws,O,NaN,Watch,Watch,vtm_method_ext_only
46,12090011000001100,NaN,NaN,Gentamicin,Gentamicin,776094005,Gentamicin 75mg/5ml oral solution,O,NaN,Access,Access,vtm_method_ext_only
45,12089911000001108,NaN,NaN,Gentamicin,Gentamicin,776094005,Gentamicin 62.5mg/5ml oral solution,O,NaN,Access,Access,vtm_method_ext_only
34,12020411000001104,NaN,NaN,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 45mg/5ml oral suspension,O,NaN,Watch,Watch,vtm_method_ext_only
33,12020311000001106,NaN,NaN,Ciprofloxacin,Ciprofloxacin,775261009,Ciprofloxacin 40mg/5ml oral suspension,O,NaN,Watch,Watch,vtm_method_ext_only
24,11713811000001100,NaN,NaN,Demeclocycline,Demeclocycline,775476004,Demeclocycline 75mg/5ml oral suspension,O,NaN,Watch,Other,vtm_method_ext_only
23,11713711000001108,NaN,NaN,Demeclocycline,Demeclocycline,775476004,Demeclocycline 75mg/5ml oral solution,O,NaN,Watch,Other,vtm_method_ext_only
22,11713611000001104,NaN,NaN,Demeclocycline,Demeclocycline,775476004,Demeclocycline 300mg/5ml oral suspension,O,NaN,Watch,Other,vtm_method_ext_only
21,11713511000001103,NaN,NaN,Demeclocycline,Demeclocycline,775476004,Demeclocycline 300mg/5ml oral solution,O,NaN,Watch,Other,vtm_method_ext_only
20,11713411000001102,NaN,NaN,Demeclocycline,Demeclocycline,775476004,Demeclocycline 150mg/5ml oral suspension,O,NaN,Watch,Other,vtm_method_ext_only
19,11713311000001109,NaN,NaN,Demeclocycline,Demeclocycline,775476004,Demeclocycline 150mg/5ml oral solution,O,NaN,Watch,Other,vtm_method_ext_only
18,11397011000001102,NaN,NaN,Spiramycin,Spiramycin,777602007,Spiramycin 1.5million unit powder for solution for infusion vials,P,NaN,Other,Other,vtm_method_ext_only
17,11381711000001105,NaN,NaN,Spiramycin,Spiramycin,777602007,Spiramycin 3million unit tablets,O,NaN,Other,Other,vtm_method_ext_only
16,11381211000001103,NaN,NaN,Spiramycin,Spiramycin,777602007,Spiramycin 1.5million unit tablets,O,NaN,Other,Other,vtm_method_ext_only
7,10532311000001101,NaN,NaN,Spectinomycin,Spectinomycin,777600004,Spectinomycin 2g powder and solvent for suspension for injection vials,P,NaN,Other,Other,vtm_method_ext_only
6,10523211000001101,NaN,NaN,Procaine benzylpenicillin,Procaine benzylpenicillin,1234762001,Procaine benzylpenicillin 1.5g/3.4ml suspension for injection pre-filled syringes,P,NaN,Access,Access,vtm_method_ext_only
47,12301911000001109,NaN,NaN,Neomycin,Neomycin,776885003,Neomycin 100mg/5ml oral solution,O,NaN,Watch,Watch,vtm_method_ext_only
263,35084911000001108,NaN,NaN,Tobramycin,Tobramycin,777791002,Tobramycin 200mg/5ml oral solution,O,NaN,Watch,Watch,vtm_method_ext_only
48,12302011000001102,NaN,NaN,Neomycin,Neomycin,776885003,Neomycin 500mg/5ml oral solution,O,NaN,Watch,Watch,vtm_method_ext_only
135,13003911000001104,NaN,NaN,Oxytetracycline,Oxytetracycline,777035003,Oxytetracycline 250mg/5ml oral suspension,O,NaN,Watch,Watch,vtm_method_ext_only
251,34607211000001108,NaN,NaN,Metronidazole,Metronidazole,776774005,Metronidazole 200mg suppositories,R,NaN,Access,Access,vtm_method_ext_only
242,33158911000001106,NaN,NaN,Moxifloxacin,Moxifloxacin,776831003,Moxifloxacin 0.5mg/0.5ml solution for injection pre-filled syringes,NaN,NaN,Watch,Watch,vtm_method_ext_only
238,32785511000001100,NaN,NaN,Demeclocycline,Demeclocycline,775476004,Demeclocycline 300mg capsules,O,NaN,Watch,Other,vtm_method_ext_only
236,32749211000001108,NaN,NaN,Gentamicin,Gentamicin,776094005,Gentamicin 45mg/5ml oral solution,O,NaN,Access,Access,vtm_method_ext_only
234,32656811000001108,NaN,NaN,Tobramycin,Tobramycin,777791002,Tobramycin 40mg/5ml oral solution,O,NaN,Watch,Watch,vtm_method_ext_only
233,32655011000001106,NaN,NaN,Metronidazole,Metronidazole,776774005,Metronidazole 500mg/5ml oral suspension,O,NaN,Access,Access,vtm_method_ext_only
227,30956811000001100,NaN,NaN,Colistin,Colistin,775373006,"Colistin 15,000,000units/5ml oral solution",O,O,Reserve,Reserve,vtm_method_ext_only
221,29827911000001102,NaN,NaN,Gentamicin,Gentamicin,776094005,Gentamicin 35mg/5ml oral suspension,O,NaN,Access,Access,vtm_method_ext_only
215,27800411000001108,NaN,NaN,Gentamicin,Gentamicin,776094005,Gentamicin 30mg/5ml oral suspension,O,NaN,Access,Access,vtm_method_ext_only
212,24666511000001106,NaN,NaN,Colistin,Colistin,775373006,"Colistin 10,000,000units/5ml oral solution",O,O,Reserve,Reserve,vtm_method_ext_only
211,24665911000001106,NaN,NaN,Colistin,Colistin,775373006,"Colistin 5,000,000units/5ml oral solution",O,O,Reserve,Reserve,vtm_method_ext_only
209,23676411000001103,NaN,NaN,Tobramycin,Tobramycin,777791002,Tobramycin 20mg/5ml oral solution,O,NaN,Watch,Watch,vtm_method_ext_only
185,21718511000001106,NaN,NaN,Tobramycin,Tobramycin,777791002,Tobramycin 135mg/5ml oral solution,O,NaN,Watch,Watch,vtm_method_ext_only
184,21717911000001100,NaN,NaN,Tobramycin,Tobramycin,777791002,Tobramycin 400mg/5ml oral solution,O,NaN,Watch,Watch,vtm_method_ext_only
136,13004011000001101,NaN,NaN,Oxytetracycline,Oxytetracycline,777035003,Oxytetracycline 500mg/5ml oral suspension,O,NaN,Watch,Watch,vtm_method_ext_only
134,13003811000001109,NaN,NaN,Oxytetracycline,Oxytetracycline,777035003,Oxytetracycline 125mg/5ml oral suspension,O,NaN,Watch,Watch,vtm_method_ext_only
662,9742511000001109,NaN,NaN,Clarithromycin,Clarithromycin,775277005,Clarithromycin 250mg granules for oral suspension straws,O,NaN,Watch,Watch,vtm_method_ext_only

Of the remaining discrepancies:  
**ukhsa_list_only**  
- Colistimethate nebuliser solution/inhalation capsules - the UKHSA online list specifies only Colistin IV and Colistin oral.  
- Vancomycin 20mg pastilles - these have been excluded from our list as oromucosal so presumably for localised infection.  
  
**vtm_method_ext_only**  
- Metronidazole 25% oromucosal gel sugar free, metronidazole 0.75% vaginal gel, clindamycin 2% vaginal cream - these have presumably been excluded from the UKHSA list as for localised infection.  
- The remainder of unmatched VMPs here seem to be uncommonly used products.

We can refine our SQL code to exclude the oromucosal gel and vaginal gel/cream:

In [49]:
sql = f"""
WITH matched_vtms AS ( -- This query does the fuzzy matching of Antibiotic name to VTM name
  SELECT  
    aware.Antibiotic,
    aware.atc_route,
    aware.aware_2019,
    aware.aware_2024,
    vtm.nm,
    vtm.id,
    CASE
      WHEN aware.Antibiotic = vtm.nm THEN 'DIRECT'
      ELSE 'ASSUMED'
    END AS match_type
  FROM `ebmdatalab.chris.aware_list_extended` aware
  LEFT JOIN `ebmdatalab.dmd.vtm` vtm 
    ON vtm.nm LIKE CONCAT('%', aware.Antibiotic, '%')
  WHERE vtm.invalid IS NOT TRUE
),

duplicate_vtms AS ( -- This produces a list of duplicate rows where a direct match already exists
  SELECT *
  FROM matched_vtms
  WHERE nm IN (
    SELECT nm
    FROM matched_vtms
    WHERE atc_route IS NULL
    GROUP BY nm
    HAVING COUNT(*) > 1
  )
  AND match_type = 'ASSUMED'
),

vmp_with_route AS (
  SELECT DISTINCT
    vmp.id AS id,
    vmp.vtm AS vtm,
    vmp.nm AS nm,
    COALESCE(sroute.route, routelookup.who_route) AS vmp_atc_route
  FROM `ebmdatalab.dmd.vmp` vmp
  LEFT JOIN dmd.ont ont ON vmp.id = ont.vmp
  LEFT JOIN dmd.ontformroute ofr ON ont.form = ofr.cd
  LEFT JOIN chris.vmp_single_route_identifier sroute ON vmp.id = sroute.vmp_id
  LEFT JOIN `scmd_dmd_views.dmd_to_atc_route` routelookup ON ofr.descr = routelookup.dmd_ofr
  WHERE ofr.descr NOT LIKE '%.auricular'
  AND ofr.descr NOT LIKE '%.cutaneous'
  AND ofr.descr NOT LIKE '%.ophthalmic'
  AND ofr.descr NOT LIKE '%.oromucosal'
  AND ofr.descr NOT LIKE '%.intralesional'
  AND ofr.descr NOT LIKE '%.nasal'
  AND ofr.descr NOT LIKE '%.gingival'
  AND ofr.descr != 'gel.vaginal'
  AND ofr.descr != 'cream.vaginal'
)

SELECT DISTINCT
  matched_vtms.Antibiotic,
  matched_vtms.nm as vtm_nm,
  matched_vtms.id as vtm_id,
  vmp.nm as vmp_nm,
  vmp.id as vmp_id,
  vmp.vmp_atc_route,
  matched_vtms.atc_route,
  matched_vtms.aware_2019,
  matched_vtms.aware_2024
FROM matched_vtms
LEFT JOIN vmp_with_route vmp
  ON matched_vtms.id = vmp.vtm
  AND (
    matched_vtms.atc_route IS NULL
    OR matched_vtms.atc_route = vmp.vmp_atc_route
  )
WHERE NOT EXISTS ( -- removes the duplicates identified above
  SELECT 1
  FROM duplicate_vtms
  WHERE matched_vtms.Antibiotic = duplicate_vtms.Antibiotic AND matched_vtms.nm = duplicate_vtms.nm
) AND vmp.id IS NOT NULL
ORDER BY matched_vtms.Antibiotic ASC;
"""

# Define the CSV path for caching the results.
csv_path = os.path.join('..', 'data', 'vmps_matched_extended.csv')

# Use the cached_read function from the bq library to run the query.
vmps_matched_extended = bq.cached_read(sql, csv_path=csv_path)

# Force vmp_id and vtm_id to proper string type
vmps_matched_extended['vmp_id'] = vmps_matched_extended['vmp_id'].astype('string')
vmps_matched_extended['vtm_id'] = vmps_matched_extended['vtm_id'].astype('string')

display(vmps_matched_extended)

Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|

,Antibiotic,vtm_nm,vtm_id,vmp_nm,vmp_id,vmp_atc_route,atc_route,aware_2019,aware_2024
0,Amikacin,Amikacin,774534000,Amikacin 500mg/2ml solution for injection vials,35899911000001109,P,None,Watch,Watch
1,Amikacin,Amikacin,774534000,Amikacin 100mg/2ml solution for injection vials,35899811000001104,P,None,Watch,Watch
2,Amikacin,Amikacin,774534000,Amikacin 500mg/2ml solution for injection ampo...,44422511000001103,P,None,Watch,Watch
3,Amikacin,Amikacin,774534000,Amikacin 500mg/100ml infusion polyethylene bot...,41823511000001108,P,None,Watch,Watch
4,Amikacin,Amikacin,774534000,Amikacin 25mg/5ml solution for injection pre-f...,35104511000001105,None,None,Watch,Watch
...,...,...,...,...,...,...,...,...,...
610,Vancomycin,Vancomycin,777914002,Vancomycin 1mg/0.1ml solution for injection pr...,21277311000001102,None,None,Watch,Watch
611,Vancomycin,Vancomycin,777914002,Vancomycin 5mg/0.5ml solution for injection pr...,21278311000001101,None,None,Watch,Watch
612,Vancomycin,Vancomycin,777914002,Vancomycin 2.5mg/0.5ml solution for injection ...,28047511000001105,None,None,Watch,Watch
613,Vancomycin,Vancomycin,777914002,Vancomycin 2mg/0.1ml intravitreal injection kit,40529511000001103,None,None,Watch,Watch
614,Vancomycin,Vancomycin,777914002,Vancomycin 500micrograms/0.1ml solution for in...,40548411000001108,None,None,Watch,Watch

<a id='s5'></a>
## Section 5: Summary
We have created a method using SQL logic to produce a list of VMPs categorised with UK AWaRe categorisation.  

We have validated the method through comparison against a UKHSA provided list and extended / refined where needed.

### Final SQL code

In [50]:
sql = f"""
WITH matched_vtms AS ( -- This query does the fuzzy matching of Antibiotic name to VTM name
  SELECT  
    aware.Antibiotic,
    aware.atc_route,
    aware.aware_2019,
    aware.aware_2024,
    vtm.nm,
    vtm.id,
    CASE
      WHEN aware.Antibiotic = vtm.nm THEN 'DIRECT'
      ELSE 'ASSUMED'
    END AS match_type
  FROM `ebmdatalab.chris.aware_list_extended` aware
  LEFT JOIN `ebmdatalab.dmd.vtm` vtm 
    ON vtm.nm LIKE CONCAT('%', aware.Antibiotic, '%')
  WHERE vtm.invalid IS NOT TRUE
),

duplicate_vtms AS ( -- This produces a list of duplicate rows where a direct match already exists
  SELECT *
  FROM matched_vtms
  WHERE nm IN (
    SELECT nm
    FROM matched_vtms
    WHERE atc_route IS NULL
    GROUP BY nm
    HAVING COUNT(*) > 1
  )
  AND match_type = 'ASSUMED'
),

vmp_with_route AS (
  SELECT DISTINCT
    vmp.id AS id,
    vmp.vtm AS vtm,
    vmp.nm AS nm,
    COALESCE(sroute.route, routelookup.who_route) AS vmp_atc_route
  FROM `ebmdatalab.dmd.vmp` vmp
  LEFT JOIN dmd.ont ont ON vmp.id = ont.vmp
  LEFT JOIN dmd.ontformroute ofr ON ont.form = ofr.cd
  LEFT JOIN chris.vmp_single_route_identifier sroute ON vmp.id = sroute.vmp_id
  LEFT JOIN `scmd_dmd_views.dmd_to_atc_route` routelookup ON ofr.descr = routelookup.dmd_ofr
  WHERE ofr.descr NOT LIKE '%.auricular'
  AND ofr.descr NOT LIKE '%.cutaneous'
  AND ofr.descr NOT LIKE '%.ophthalmic'
  AND ofr.descr NOT LIKE '%.oromucosal'
  AND ofr.descr NOT LIKE '%.intralesional'
  AND ofr.descr NOT LIKE '%.nasal'
  AND ofr.descr NOT LIKE '%.gingival'
  AND ofr.descr != 'gel.vaginal'
  AND ofr.descr != 'cream.vaginal'
)

SELECT DISTINCT
  matched_vtms.Antibiotic,
  matched_vtms.nm as vtm_nm,
  matched_vtms.id as vtm_id,
  vmp.nm as vmp_nm,
  vmp.id as vmp_id,
  vmp.vmp_atc_route,
  matched_vtms.atc_route,
  matched_vtms.aware_2019,
  matched_vtms.aware_2024
FROM matched_vtms
LEFT JOIN vmp_with_route vmp
  ON matched_vtms.id = vmp.vtm
  AND (
    matched_vtms.atc_route IS NULL
    OR matched_vtms.atc_route = vmp.vmp_atc_route
  )
WHERE NOT EXISTS ( -- removes the duplicates identified above
  SELECT 1
  FROM duplicate_vtms
  WHERE matched_vtms.Antibiotic = duplicate_vtms.Antibiotic AND matched_vtms.nm = duplicate_vtms.nm
) AND vmp.id IS NOT NULL
ORDER BY matched_vtms.Antibiotic ASC;
"""

### Outstanding questions

The UKHSA online list specifies only Colistin IV and Colistin oral. Should Colistin inhalation be included?
Cefepime + Enmetazobactam isn't included in the UKHSA list. Should it be included for potential future use? With what categorisation?
Vancomycin 20mg pastilles - these have been excluded from our list as oromucosal so presumably for localised infection. Should they be included?